/*Copyright (c) 1997,2026 Gary William Flake*/
#include<unistd.h>
#include<errno.h>
typedef char D;macro Statement$d(Expr$x...)=>{fprintf(stderr,$x...);}typedef int I;macro Statement$q(Expr$x)=>{return$x;}keyword q$q;class C struct{C a,b;String s;I k,m;}*;C h,f,z,t,e;I n=10240;Map m;Array r;D b[256],*s;I o(D*s)=>fputs(s,stdout);
C H(C c)=>r.push(c);
C F(D*s)=>(o("Error: "),o(s),e);
void M(C c){for(;c&&!c.m;c=c.b)c.m=1,M(c.a);}
C C.new(I k,C a,C b){if(!f){$d("Garbage collecting...");fflush(stderr);M(a);M(b);foreach(C c,m)M(c);foreach(C c,r)M(c);I j=0;for(I i=0;i<n;i++){C c=h+i;if(!c.m)c.a=f,f=c,j++;c.m=0;}if(!j){$d("\nGarbage collection failed!\n");exit(1);}$d("harvested %d cells.\n",j);}C c=f;f=c.a;*c=(struct C){a,b,0,k};q(c);}
C A(String s){if(s in m)q(m[s]);C c=C.new(0,0,0);c.s=s;q(m[s]=c);}
C P(C c,I b)=>!c||c==z?z:c==e?c:c.k==1?b?c.b:c.a:F(%"${b?"cdr":"car"}: argument is not a list.");
C L(C a,C b)=>a==e||b==e?e:b!=z&&(!b||b.k!=1)?F("cons: second argument is not a list."):C.new(1,a,b);
String T(I g){for(;;)if(!s||strchr("\n;",*s)){if(!(s=fgets(b,256,stdin)))q(0);}else if(strchr(" \t",*s))s++;else{D*a=s,*b=s+1;if(!strchr("()'",*a))while(!strchr("()' \t\n;",*b))b++;if(g)s=b;q(String.new_len(a,b-a));}}
C R(void){String x=T(1);if(!x)q(0);if(x=="'")q(L(m["quote"],L(R(),z)));if(x==")")q((s=0,o("parse error: unexpected ')'\n"),e));if(x!="(")q(A(x));I j=r.len();defer r.truncate(j);while((x=T(0))&&x!=")")if(H(R())==e)q(e);if(!x)q((o("parse error: unexpected EOF.\n"),e));T(1);C c=z;for(I i=r.len()-1;i>=j;i--)c=L(r[i],c);q(c);}
C E(C c){if(!c||c==e)q(c);if(!c.k)q(c.a?c.a:F(%"unbound atom \"${c.s}\"."));if(c.k!=1)q(c);I j=r.len();H(c);defer r.truncate(j);C f=H(E(c.a)),a=c.b;if(!f||f.k<2)q(f==e?e:c);if(f.k==2){for(C p=f.a;p!=z;p=p.b){C v=a==z?z:E(a.a);if(v==e)q(v);H(p.a);H(v);H(0);if(a!=z)a=a.b;}I v=r.len();for(I i=v-3;i>j+1;i-=3){C p=r[i];r[i+2]=p.a;p.a=r[i+1];}defer for(I i=j+2;i<v;i+=3){C p=r[i];p.a=r[i+2];}q(E(f.b));}C b=P(P(a,1),0),d=a;a=P(a,0);if(f.k<8)a=H(E(a)),b=E(b);switch(f.k){case 3:case 4:q(P(a,f.k==4));case 5:q(L(a,b));case 6:if(a==e||b==e)q(e);if(!a||a.k)q(F("set: first argument is not an atom."));q(a.a=b);case 7:q(a&&!a.k&&a==b?t:z);case 10:q(E(E(a)!=z?b:P(P(P(d,1),1),0)));case 9:for(C p=a;p!=z;p=p.b)if(!p||p.k!=1||!p.a||p.a.k)q(F("bad argument list supplied."));q(C.new(2,a,b));}q(a);}
void O(C c){if(!c)o("<NULL>");else if(c==e);else if(!c.k)o(c.s);else if(c.k>2)o(c.k<8?"<internal-value-function>":"<internal-special-function>");else{o(c.k==1?"(":"(lambda ");O(c.a);if(c.k==2)o(" "),O(c.b);else for(c=c.b;c!=z;c=c.b)o(" "),O(c.a);o(")");}}
I U(D*p){$d("Usage: %s [ options ]\n\n    Stutter understands car, cdr, cons, if, set, equal,\n    quote, and lambda. Programs use atoms and proper lists,\n    dynamically scoped functions, and a mark-and-sweep heap.\n    Read expressions from standard input.\n\nOptions with defaults in parentheses are:\n\n    -heap  Number of cells in the heap. (%d)\n\n",p,n);q(1);}
I main(I c,char**v){for(I i=1;i<c;i++){String a=v[i];if(a=="-help")q(U(v[0]));if(a!="-heap"||i+1==c){$d("%s: unknown or incorrectly used option \"%s\".\n",v[0],v[i]);q(U(v[0]));}D*p;errno=0;long j=strtol(v[++i],&p,10);if(errno||*p||j<=0||j>INT_MAX){$d("Error: -heap requires a positive cell count.\n");q(1);}n=j;}$scope(){m=%{};r=%[];h=Scope.calloc(n,sizeof*h);for(I i=n;i--;)(h+i)->a=f,f=h+i;z=A("nil");z.a=z;t=A("t");t.a=t;e=A("<error>");e.a=e;I k=3;foreach(Symbol s,%(car cdr cons set equal quote lambda if)){C c=A(s.str());c.a=C.new(k++,0,0);}for(;;){o("> ");fflush(stdout);C c=R();if(!c)break;if(!isatty(0))O(c),o("\n");O(E(c));o("\n");}o("\n");}q(0);}
