/* auto-generated by x2c.  Do not edit! */

#pragma once

#ifndef __GUARD_0xD09CF48E__
#define __GUARD_0xD09CF48E__

#include "x2c.h"
#include "machine.h"
typedef Var(* NativeScalarLoad)(const void * bytes, Scope * owner);

typedef void(* NativeScalarStore)(void * bytes, Var value);

typedef struct NativeScalarAccess{
  Symbol tag;
  size_t size, alignment;
  NativeScalarLoad load;
  NativeScalarStore store;
}
* NativeScalarAccess;

NativeScalarAccess native_scalar_access(List exact_type);

typedef struct Lisp * Lisp;

typedef struct LispAutoStats{
  long invocations, machine_entries, machine_errors;
  long analyses, published, ineligible;
  long guard_failures, remembered_fallbacks;
  long inlined_scopes;
  long inline_declines;
  long program_bytes;
}
LispAutoStats;

int Lisp_program(Var callable, MachineView * view, int * nparam, Var * body);

int Lisp_resolve(void * storage, Var name, Var * value);

void Lisp_enter(void * storage, Var callable, const Var * values, int count);

void Lisp_leave(void * storage);

void Lisp_retarget(void * storage, Var callable, const Var * values, int count);

int Lisp_step(void * storage);

void Lisp_reslot(void * storage, List params, int count);

Var Lisp_apply_values(void * storage, Var callable, const Var * values, int count);

int Lisp_precall(void * storage, Var callable, List raw, Var * value);

Var Lisp_immediate(void * storage, Var callable);

Var Lisp_evaluate(void * storage, Var form);

int Lisp_expanded(void * storage, List site, Var * out);

Lisp Lisp_kernel(void);

Lisp Lisp_new(void);

void Lisp_destroy(Lisp lisp);

void Lisp_adopt(Lisp lisp, Lisp parent);

void Lisp_freeze(Lisp lisp);

Symbol Lisp_read(Lisp lisp, String source, unsigned * cursor, Var * out);

Var lisp_truth(Var value);

Var lisp_atom(Var value);

Var lisp_car(Var value);

Var lisp_cdr(Var value);

Var lisp_eq(Var a, Var b);

Var lisp_pair(Var value);

Var lisp_list(Var value);

Var lisp_number(Var value);

Var lisp_string(Var value);

Var lisp_symbol(Var value);

Var lisp_procedure(Var value);

Var lisp_compare(Var a, Var b);

Symbol lisp_type(Var value);

Var lisp_add(Var a, Var b);

Var lisp_plus(List values);

Var lisp_minus(List values);

Var lisp_times(List values);

Var lisp_divide(List values);

Var lisp_eq_chain(List values);

Var lisp_lt_chain(List values);

Var lisp_le_chain(List values);

Var lisp_gt_chain(List values);

Var lisp_ge_chain(List values);

Var lisp_str(Var value);

Var lisp_repr(Var value);

Var lisp_string_append(String left, String right);

Var lisp_substring(String string, int start, int stop);

Var lisp_string_downcase(String string);

String lisp_string_strip(String string, Var chars);

String lisp_string_lstrip(String string, Var chars);

String lisp_string_rstrip(String string, Var chars);

Var lisp_match_replace(List input, Var pat, Var template);

Var lisp_read_file(String path);

Var lisp_write_file(String path, String text);

Var lisp_void(void);

Var lisp_cell(Var value);

Var lisp_address(Var cell, Symbol tag);

Var lisp_load(Var cell);

Var lisp_store(Var cell, Var value);

Var lisp_bytes(long size);

Var lisp_at(Var base, Var offset, Symbol tag);

Var lisp_zero(Var destination, Var size);

Var lisp_copy(Var destination, Var source, long size);

Var lisp_record_result(Var source, long size);

Var lisp_session_copy(Var source, long size);

Var lisp_box(Symbol tag, Var value);

Var lisp_peek(Var pointer, Var offset, List layout);

Var lisp_poke(Var pointer, Var offset, List layout, Var value);

Var lisp_array(List layout, List values);

Var lisp_source_function(Var callable);

Var lisp_unwind(Var body, Var cleanup, List arguments);

Func lisp_func_new(Var adapter, List signature);

void * lisp_func_arguments(unsigned count);

void * lisp_func_value(FuncArg * argv, unsigned index, Var value);

void * lisp_func_reference(FuncArg * argv, unsigned index, Var address, List source);

Var lisp_func_invalid(Func fn, unsigned index, List source);

LispAutoStats Lisp_auto_stats(Lisp lisp);

void Lisp_auto_instrument(Lisp lisp, MachineStats * stats);

void Lisp_call_budget(Lisp lisp, long budget);

void Lisp_auto_disable(Lisp lisp, int disabled);

int Lisp_auto_prepare(Lisp lisp);

Var Lisp_eval(Lisp lisp, Var expression);

Var Lisp_apply(Lisp lisp, Var callable, List values);

Var Lisp_eval_string(Lisp lisp, String source);

Var Lisp_eval_file(Lisp lisp, File source);

int Lisp_try_get(Lisp lisp, String name, Var * out);

void Lisp_set_global(Lisp lisp, String name, Var value);

void Lisp_bind(Lisp lisp, String name, Func function);

void Lisp_cleanup(Lisp value);


#endif /* __GUARD_0xD09CF48E__ */
