/* auto-generated by x2c.  Do not edit! */

#pragma once

#ifndef __GUARD_0xA5BC2A2E__
#define __GUARD_0xA5BC2A2E__

#include "common.h"
#include "macro-value.h"
Map native_scalar_types(void);

List _scalar_access_units(Macro access);


#endif /* __GUARD_0xA5BC2A2E__ */
