/* auto-generated by x2c.  Do not edit! */

#pragma once

#ifndef __GUARD_0x78E69167__
#define __GUARD_0x78E69167__

#include "x2c.h"
typedef struct _RegexNode * _RegexNode;

typedef struct Regex{
  String pattern;
  _RegexNode program;
  int capture_count;
  List capture_names;
  int caseless, multiline, dotall;
}
* Regex;

void Regex_free(Regex value);

void Regex_cleanup(Regex value);

Var Regex_var(Regex value);

Regex Var_regex(Var value);

int Regex_equal(Regex left, Regex right);

unsigned Regex_hash(Regex value);

Buffer Regex_write_str(Regex value, Buffer out);

String Regex_str(Regex value);

Buffer Regex_write_repr(Regex value, Buffer out);

String Regex_repr(Regex value);

typedef List RegexCapture;

typedef List RegexMatch;

Regex Regex_compile(String pattern);

String Regex_pattern(Regex regex);

int Regex_capture_count(Regex regex);

List Regex_capture_names(Regex regex);

String Regex_escape(String literal);

RegexMatch Regex_match_from(Regex r, String subject, int offset);

RegexMatch Regex_match(Regex r, String subject);

List Regex_find_all(Regex r, String subject);

List Regex_split(Regex regex, String subject);

String Regex_replace(Regex regex, String subject, String replacement);

String Regex_replace_all(Regex regex, String subject, String replacement);

String Regex_replace_fn(Regex regex, String subject, Func fn);

RegexCapture RegexMatch_capture(RegexMatch found, Var key);

String RegexMatch_getindex(RegexMatch found, Var key);

int RegexCapture_index(RegexCapture capture);

String RegexCapture_name(RegexCapture capture);

int RegexCapture_matched(RegexCapture capture);

String RegexCapture_text(RegexCapture capture);

int RegexCapture_start(RegexCapture capture);

int RegexCapture_end(RegexCapture capture);

RegexCapture Var_regexcapture(Var value);

RegexMatch Var_regexmatch(Var value);


#endif /* __GUARD_0x78E69167__ */
