/* auto-generated by x2c.  Do not edit! */

#pragma once

#ifndef __GUARD_0x8309C62D__
#define __GUARD_0x8309C62D__

#include "x2c.h"
#include "cli.h"
#include "deps.h"
#include "toolchain.h"
typedef struct Build{
  CliRequest request;
  Toolchain toolchain;
  String work_dir,  gen_root,  obj_root,  dep_root,  state_root,  output;
  int temporary;
  Array c_sources,  gen_dirs,  native_inputs,  objects;
  String compile_directory;
  Array compile_commands;
  unsigned long started_at;
  unsigned long xlat_start;
  unsigned long cc_start;
  unsigned long final_at;
  unsigned long long gen_bytes;
  int xlat_n,  xlat_done,  xlat_cached,  cc_n,  cc_done,  cc_cached,  final_cached;
}
* Build;

int _build_mkdirs(String path);

Build CliRequest_prepare(CliRequest c);

String Build_generated_dir(Build state,  String input);

int Build_translation_current(Build state,  String input,  String directory);

void Build_record_translation(Build state,  String input,  String directory);

void Build_add_generated(Build state,  String input,  String directory);

void Build_begin_translation(Build state,  String input);

void Build_end_translation(Build state,  String input,  int cached);

int compile_commands_write(String path,  Array commands);

int Build_finish(Build b);

void Build_report_success(Build b);

int Build_run_program(Build state);

int _build_remove_tree(String path);

void Build_cleanup(Build state,  int success);


#endif /* __GUARD_0x8309C62D__ */
