#define _x2c_initializer_choice_AB8728A9_0_expanded(_x2c_static_input_0) static void _x2c_static_initialize_0(void){\
  _x2c_static_input_0;\
}
#define _x2c_initializer_choice_AB8728A9_0(_x2c_static_input_0) _x2c_initializer_choice_AB8728A9_0_expanded(_x2c_static_input_0)
#define _x2c_initializer_choice_AB8728A9_1_expanded(_x2c_static_input_1) static void _x2c_static_initialize_1(void){\
  _x2c_static_input_1;\
}
#define _x2c_initializer_choice_AB8728A9_1(_x2c_static_input_1) _x2c_initializer_choice_AB8728A9_1_expanded(_x2c_static_input_1)
#define _x2c_initializer_choice_AB8728A9_2_expanded(_x2c_static_input_2) static void _x2c_static_initialize_2(void){\
  _x2c_static_input_2;\
}
#define _x2c_initializer_choice_AB8728A9_2(_x2c_static_input_2) _x2c_initializer_choice_AB8728A9_2_expanded(_x2c_static_input_2)
#define _x2c_initializer_choice_AB8728A9_3_expanded(_x2c_static_input_3) static void _x2c_static_initialize_3(void){\
  _x2c_static_input_3;\
}
#define _x2c_initializer_choice_AB8728A9_3(_x2c_static_input_3) _x2c_initializer_choice_AB8728A9_3_expanded(_x2c_static_input_3)
#define _x2c_initializer_choice_AB8728A9_4_expanded(_x2c_static_input_4) static void _x2c_static_initialize_4(void){\
  _x2c_static_input_4;\
}
#define _x2c_initializer_choice_AB8728A9_4(_x2c_static_input_4) _x2c_initializer_choice_AB8728A9_4_expanded(_x2c_static_input_4)
#define _x2c_initializer_choice_AB8728A9_5_expanded(_x2c_static_input_5) static void _x2c_static_initialize_5(void){\
  _x2c_static_input_5;\
}
#define _x2c_initializer_choice_AB8728A9_5(_x2c_static_input_5) _x2c_initializer_choice_AB8728A9_5_expanded(_x2c_static_input_5)
/* auto-generated by x2c.  Do not edit! */

#include "collect.h"

#include "exception.h"

static List _157, _155, _153, _152, _151, _149, _147, _145, _143, _141, _139, _138, _137, _136, _135, _134, _133, _132, _130, _129, _128, _127, _126, _125, _94, _92, _91, _87, _85, _83, _81, _80, _79, _78, _66, _65, _64, _63, _62, _51, _44, _42, _38, _36, _31, _29, _27, _25, _24, _22, _15, _13, _12;

static String _165, _164, _163, _162, _161, _160, _159, _158, _102, _101, _100, _99, _98, _97, _96, _95, _73, _72, _71, _70, _69, _68, _67, _56, _55, _54, _53, _52, _48, _47, _45, _9, _7, _6, _4, _3, _2, _1, _0;

static Var _154, _150, _148, _146, _144, _142, _140, _131, _115, _113, _111, _109, _107, _105, _104, _103, _93, _88, _86, _84, _82, _77, _74, _61, _60, _59, _58, _57, _50, _49, _46, _43, _37, _32, _30, _28, _26, _23, _21, _16, _14, _11, _10, _8, _5;

#include "buffer.h"
#include "utils.h"
#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
static int _init_guard_ = 0;

__attribute__((constructor)) static void _file_init_(void);

static int _starts_line(Token first, Token token);

static int _visibility_pragma(String directive);

static String _canonical_path(String path);

static String _cached_canonical(char * cache, String dir);

static String _canonical_lib(void);

static String _canonical_include(void);

static String _canonical_src(void);

static String _canonical_cwd(void);

static String _resolve_include_dirs(SourceView sources, List extra_dirs, String includer_dir, String target, int angle, int * covered);

static String _resolve_include(Compiler compiler, String includer_dir, String target, int angle, int * covered);

static Map process_cache;

_x2c_initializer_choice_AB8728A9_0((process_cache = NULL))
static Scope process_cache_scope;

_x2c_initializer_choice_AB8728A9_1((process_cache_scope = NULL))
static void _cache_shutdown(void);

static Map _process_cache(void);

static List _entry(Compiler c, String canonical);

static void _cache_dependency(Map dependencies, String path, Var content_hash);

static void _cache_dependencies(Map dependencies, Map additions);

static void _replay_cached(Compiler compiler, List entry, Map globs, Map visited);

static String _include_text(Compiler c, String target, String path);

static List _walk_cold(Compiler c, String target, String canonical, Map globs, Map visited);

static void _parse_segment(Compiler c, String path, String source, String text, int start_line, int start_pos, Map globs, Map overlay, Map definitions, Map dependencies, int private);

static int _external_function(Map statics, String name, Var type);

static void _keep_published_rows(Map statics, Map overlay);

static void _publish_unit_statics(Map statics, Map overlay, String path);

static void _flush_segment(Compiler compiler, String path, String source, String text, int start_line, int start_pos, Map globs, Array parts, Map definitions, Map dependencies, int private);

static String _include(Compiler c, String target, int angle, String dir, Map globs, Map visited, Map dependencies);

static void _require_retained(int owned);

static void _file(Compiler c, String path, String text, String dir, Map globs, Map visited);

static String _runtime_text(Compiler c, String runtime);

static List _prelude_entry(Compiler c, String runtime, String canonical);

static String _package_entry(Compiler compiler, String name, String * directory);

static String _package_key_spelling(List key);

static int _package_protocol_row(List key, Var value);

static void _package_merge(Compiler compiler, String name, String root, String path, Map part, Map merged, Token token);

static void _package_contributions(Compiler compiler, String name, String root, String path, List entry, Map merged, Map visited, Token token);

static String interface_out_dir, interface_mirror;

_x2c_initializer_choice_AB8728A9_2((interface_out_dir = NULL))
_x2c_initializer_choice_AB8728A9_3((interface_mirror = NULL))
static List _interface_candidates(String canonical);

static Map source_hashes;

_x2c_initializer_choice_AB8728A9_4((source_hashes = NULL))
static Lisp interface_reader;

_x2c_initializer_choice_AB8728A9_5((interface_reader = NULL))
static void _interface_shutdown(void);

static Lisp _interface_lisp(void);

static int _hash_matches(Compiler compiler, String path, Var expected);

static List _interface_load(Compiler c, String canonical, String path);

static List _interface_entry(Compiler c, String canonical, String hash, List stored_parts, List definitions, List stored_dependencies);

static List _interface_read(Compiler c, String canonical);

static List _renumber_bindings(List node, Map identities);

static int _write_datum(Buffer out, Var value);

static int _write_interface_entry(Buffer out, String canonical, List entry);

typedef struct _x2c_defer_env_0{
  const void * _x2c_defer_capture_0;
  const void * _x2c_defer_capture_1;
}
_x2c_defer_env_0;

static void _x2c_defer_cleanup_0(void * _x2c_defer_opaque_0);

typedef struct _x2c_defer_env_1{
  const void * _x2c_defer_capture_2;
  const void * _x2c_defer_capture_3;
}
_x2c_defer_env_1;

static void _x2c_defer_cleanup_1(void * _x2c_defer_opaque_1);

typedef struct _x2c_defer_env_2{
  const void * _x2c_defer_capture_4;
  const void * _x2c_defer_capture_5;
}
_x2c_defer_env_2;

static void _x2c_defer_cleanup_2(void * _x2c_defer_opaque_2);

typedef struct _x2c_defer_env_3{
  const void * _x2c_defer_capture_6;
}
_x2c_defer_env_3;

static void _x2c_defer_cleanup_3(void * _x2c_defer_opaque_3);

Var String_var(String);

Var Symbol_var(Symbol);

List cons(Var, List);

Var List_var(List);

Var int_var(int);

__attribute__((constructor)) static void _file_init_(void){
  x2c_initialize_protocols();
  if(_init_guard_) return;
  _init_guard_ = 1;
  _0 = String_new("/lib");
  _1 = String_new("/include/x2c");
  _2 = String_new("/src");
  _3 = String_new("/");
  _4 = String_new("stage: collect");
  _5 = String_var(_4);
  _6 = String_new("include: ");
  _7 = String_new("path: ");
  _8 = Symbol_var(458361162716);
  _9 = String_new("source-node");
  _10 = String_var(_9);
  _11 = Symbol_var(54);
  _12 = cons(_11, NULL);
  _13 = cons(_10, _12);
  _14 = List_var(_13);
  _15 = cons(_14, NULL);
  _16 = Symbol_var(61737802);
  _21 = Symbol_var(1318210446);
  _22 = cons(_21, NULL);
  _23 = Symbol_var(1362954);
  _24 = cons(_23, _22);
  _25 = cons(_16, _24);
  _26 = Symbol_var(62054);
  _27 = cons(_26, _25);
  _28 = List_var(_27);
  _29 = cons(_28, NULL);
  _30 = List_var(_29);
  _31 = cons(_30, NULL);
  _32 = Symbol_var(1256204);
  _36 = cons(_32, _29);
  _37 = List_var(_36);
  _38 = cons(_37, NULL);
  _42 = cons(_8, _29);
  _43 = List_var(_42);
  _44 = cons(_43, NULL);
  _45 = String_new("unit-static");
  _46 = String_var(_45);
  _47 = String_new("%08x");
  _48 = String_new("generated-protocol");
  _49 = String_var(_48);
  _50 = Symbol_var(15767198343496);
  _51 = cons(_50, NULL);
  _52 = String_new("/lib/x2c.x");
  _53 = String_new("/src/");
  _54 = String_new(".x");
  _55 = String_new("source-node");
  _56 = String_new("source-typedef");
  _57 = Symbol_var(1139215899608);
  _58 = Symbol_var(2391080);
  _59 = Atom_intern(String_new("meta-protocol"));
  _60 = Atom_intern(String_new("declaration-source"));
  _61 = Atom_intern(String_new("native-meta"));
  _62 = cons(_61, NULL);
  _63 = cons(_60, _62);
  _64 = cons(_59, _63);
  _65 = cons(_58, _64);
  _66 = cons(_57, _65);
  _67 = String_new("__");
  _68 = String_new("below #pragma private, or move it into \'");
  _69 = String_new("/src\'");
  _70 = String_new("package \'");
  _71 = String_new("\' exposes unprefixed top-level declaration \'");
  _72 = String_new("\'");
  _73 = String_new("\' is x2c source outside the package; include it ");
  _74 = Atom_intern(String_new("?declarations"));
  _77 = Symbol_var(26720);
  _78 = cons(_77, NULL);
  _79 = cons(_23, _78);
  _80 = cons(_74, _79);
  _81 = cons(_26, _80);
  _82 = List_var(_81);
  _83 = cons(_82, NULL);
  _84 = Symbol_var(35588017418);
  _85 = cons(_84, NULL);
  _86 = Symbol_var(1117938246);
  _87 = cons(_86, NULL);
  _88 = Atom_intern(String_new("?dependency"));
  _91 = cons(_88, _24);
  _92 = cons(_26, _91);
  _93 = List_var(_92);
  _94 = cons(_93, NULL);
  _95 = String_new("unknown package \'");
  _96 = String_new("searched: <root>/");
  _97 = String_new(".x, <root>/");
  _98 = String_new("cannot read package \'");
  _99 = String_new(".xi");
  _100 = String_new("/../");
  _101 = String_new("/builds/");
  _102 = String_new("/../builds/");
  _103 = Symbol_var(20796605335754);
  _104 = int_var(3);
  _105 = Symbol_var(64010951680356);
  _107 = Symbol_var(1979150692);
  _109 = Symbol_var(61344976);
  _111 = Atom_intern(String_new("?stored_parts"));
  _113 = Atom_intern(String_new("?definitions"));
  _115 = Atom_intern(String_new("?stored_dependencies"));
  _125 = cons(_105, _24);
  _126 = cons(_26, _125);
  _127 = cons(_107, _24);
  _128 = cons(_26, _127);
  _129 = cons(_109, _24);
  _130 = cons(_26, _129);
  _131 = Symbol_var(806120);
  _132 = cons(_131, NULL);
  _133 = cons(_23, _132);
  _134 = cons(_111, _133);
  _135 = cons(_26, _134);
  _136 = cons(_113, _133);
  _137 = cons(_26, _136);
  _138 = cons(_115, _133);
  _139 = cons(_26, _138);
  _140 = List_var(_139);
  _141 = cons(_140, NULL);
  _142 = List_var(_137);
  _143 = cons(_142, _141);
  _144 = List_var(_135);
  _145 = cons(_144, _143);
  _146 = List_var(_130);
  _147 = cons(_146, _145);
  _148 = List_var(_128);
  _149 = cons(_148, _147);
  _150 = List_var(_126);
  _151 = cons(_150, _149);
  _152 = cons(_104, _151);
  _153 = cons(_103, _152);
  _154 = Atom_intern(String_new("?content_hash"));
  _155 = cons(_154, NULL);
  _157 = cons(_28, _155);
  _158 = String_new("\n");
  _159 = String_new("pragma private");
  _160 = String_new("pragma public");
  _161 = String_new(".");
  _162 = String_new("/");
  _163 = String_new("cannot read include");
  _164 = String_new("cannot read runtime source");
  _165 = String_new("failed to write interface file");
  _x2c_static_initialize_0();
  _x2c_static_initialize_1();
  _x2c_static_initialize_2();
  _x2c_static_initialize_3();
  _x2c_static_initialize_4();
  _x2c_static_initialize_5();
}

int String_contains(String, String);

static int _starts_line(Token first, Token token){
  while(token -- > first){
    if(token -> type != 40896714 && token -> type != 7477210024) return 0;
    if(String_contains(token -> text, _158)) return 1;
  }
  return 1;
}

static int _visibility_pragma(String directive){
  if(String_contains(directive, _159)) return 1;
  return String_contains(directive, _160) ? 0 : - 1;
}

static String _canonical_path(String path){
  char buffer[PATH_MAX];
  return realpath(path, buffer) ? String_new(buffer) : path;
}

static String _cached_canonical(char * cache, String dir){
  if(! * cache && ! realpath(dir, cache)) snprintf(cache, PATH_MAX, "%s", (char *) dir);
  return String_new(cache);
}

String x2c_get_root(void);

static String _canonical_lib(void){
  static char cache[PATH_MAX];
  if(* cache) return String_new(cache);
  return _cached_canonical(cache, String_join(NULL, cons(String_var(x2c_get_root()), cons(String_var(_0), NULL))));
}

static String _canonical_include(void){
  static char cache[PATH_MAX];
  if(* cache) return String_new(cache);
  return _cached_canonical(cache, String_join(NULL, cons(String_var(x2c_get_root()), cons(String_var(_1), NULL))));
}

static String _canonical_src(void){
  static char cache[PATH_MAX];
  if(* cache) return String_new(cache);
  return _cached_canonical(cache, String_join(NULL, cons(String_var(x2c_get_root()), cons(String_var(_2), NULL))));
}

static String _canonical_cwd(void){
  static char cache[PATH_MAX];
  return _cached_canonical(cache, _161);
}

int String_startswith(String, String);

int SourceView_exists(SourceView, String);

int String_truth(String);

Var Array_push(Array, Var);

int List_try_next(List, List *, Var *);

int Var_is_row(Var, unsigned, unsigned long, unsigned long);

String Var_string(Var);

int Array_try_next(Array, int *, Var *);

int String_equal(String, String);

static String _resolve_include_dirs(SourceView sources, List extra_dirs, String includer_dir, String target, int angle, int * covered){
  * covered = 0;
  if(String_startswith(target, _162)) return SourceView_exists(sources, target) ? target : NULL;
  String lib_dir = _canonical_lib(), include_dir = _canonical_include();
  Array dirs = Array_new();
  if(! angle && String_truth(includer_dir)) Array_push(dirs, String_var(_canonical_path(includer_dir)));
  Array_push(dirs, String_var(_canonical_cwd()));
  Array_push(dirs, String_var(_canonical_src()));
  Array_push(dirs, String_var(lib_dir));
  {
    Var value;
    List _x2c_macro_object_0 = extra_dirs;
    List _x2c_macro_cursor_0 = _x2c_macro_object_0;
    Var _x2c_macro_cursor_output_0;
    while(List_try_next(_x2c_macro_object_0, & _x2c_macro_cursor_0, & _x2c_macro_cursor_output_0)){
      value = _x2c_macro_cursor_output_0;
      {
        if(! Var_is_row(value, 11, 7, 1)) continue;
        String dir = Var_string(value);
        Array_push(dirs, String_var(_canonical_path(dir)));
      }

    }

  }
  String found = NULL;
  {
    String dir;
    Array _x2c_macro_object_1 = dirs;
    int _x2c_macro_cursor_1 = 0;
    Var _x2c_macro_cursor_output_1;
    while(Array_try_next(_x2c_macro_object_1, & _x2c_macro_cursor_1, & _x2c_macro_cursor_output_1)){
      dir = Var_string(_x2c_macro_cursor_output_1);
      {
        String path = String_join(NULL, cons(String_var(dir), cons(String_var(_3), cons(String_var(target), NULL))));
        if(! SourceView_exists(sources, path)) continue;
        found = path;
        * covered = String_equal(dir, lib_dir) || String_equal(dir, include_dir);
        break;
      }

    }

  }
  Array_free(dirs);
  return found;
}

static String _resolve_include(Compiler compiler, String includer_dir, String target, int angle, int * covered){
  return _resolve_include_dirs(compiler -> sources, compiler -> include_dirs, includer_dir, target, angle, covered);
}

void Scope_destroy(Scope);

static void _cache_shutdown(void){
  Scope_destroy(process_cache_scope);
  process_cache_scope = NULL;
  process_cache = NULL;
}

void Scope_push(Scope *);

void Scope_shutdown_hook(void(*)(void));

void Scope_pop(void);

static Map _process_cache(void){
  if((void *) process_cache != NULL) return process_cache;
  Scope_push(& process_cache_scope);
  Scope_shutdown_hook(_cache_shutdown);
  process_cache = Map_new();
  Scope_pop();
  return process_cache;
}

Var Map_getindex(Map, Var);

List Var_list(Var);

int Var_is_void(Var);

static List _entry(Compiler c, String canonical){
  Var cached = Map_getindex(_process_cache(), String_var(canonical));
  return Var_list(Var_is_void(cached) ? List_var(_interface_read(c, canonical)) : cached);
}

int String_try_own(String);

void Map_merge_translation_dependency(Map, String, Var);

static void _cache_dependency(Map dependencies, String path, Var content_hash){
  _require_retained(String_try_own(path));
  if(Var_is_row(content_hash, 11, 7, 1)) _require_retained(String_try_own(Var_string(content_hash)));
  Map_merge_translation_dependency(dependencies, path, content_hash);
}

int Map_try_next(Map, unsigned *, Var *, Var *);

static void _cache_dependencies(Map dependencies, Map additions){
  {
    Var path, content_hash;
    Map _x2c_macro_object_2 = additions;
    unsigned _x2c_macro_cursor_2 = 0;
    Var _x2c_macro_cursor_output_2;
    Var _x2c_macro_cursor_output_3;
    while(Map_try_next(_x2c_macro_object_2, & _x2c_macro_cursor_2, & _x2c_macro_cursor_output_2, & _x2c_macro_cursor_output_3)){
      path = _x2c_macro_cursor_output_2;
      content_hash = _x2c_macro_cursor_output_3;
      _cache_dependency(dependencies, Var_string(path), content_hash);
    }

  }

}

Iter Var_iter(Var, Iter);

Var List_caddr(List);

int Iter_try_next(Iter, Var *);

Var Map_setindex(Map, Var, Var);

void Compiler_merge_translation_dependencies(Compiler, Map);

Map Var_map(Var);

Var List_getindex(List, int);

Var List_car(List);

int Var_is(Var, Symbol);

Map Map_merge(Map, Map);

void Compiler_merge_source_declarations(Compiler, Map, Map);

void Compiler_add_translation_dependency(Compiler, String);

int Map_contains(Map, Var);

int List_truth(List);

static void _replay_cached(Compiler compiler, List entry, Map globs, Map visited){
  {
    Var definition;
    Iter _x2c_macro_iterator_3 = Var_iter(List_caddr(entry), &(struct Iter){
      int_var(0)
    }
    );
    Var _x2c_macro_item_3;
    while(Iter_try_next(_x2c_macro_iterator_3, & _x2c_macro_item_3)){
      definition = _x2c_macro_item_3;
      Map_setindex(compiler -> fn_defs, definition, int_var(1));
    }

  }
  Compiler_merge_translation_dependencies(compiler, Var_map(List_getindex(entry, 3)));
  {
    Var part;
    Iter _x2c_macro_iterator_4 = Var_iter(List_car(entry), &(struct Iter){
      int_var(0)
    }
    );
    Var _x2c_macro_item_4;
    while(Iter_try_next(_x2c_macro_iterator_4, & _x2c_macro_item_4)){
      part = _x2c_macro_item_4;
      {
        if(Var_is(part, 26720)){
          Map_merge(globs, Var_map(part));
          Compiler_merge_source_declarations(compiler, globs, Var_map(part));
          continue;
        }
        if(Var_is(part, 1328354264)) continue;
        String dep_path = Var_string(part);
        Compiler_add_translation_dependency(compiler, dep_path);
        if(Map_contains(visited, String_var(dep_path))) continue;
        Map_setindex(visited, String_var(dep_path), int_var(1));
        List resolved = _entry(compiler, dep_path);
        if(! List_truth(resolved)) resolved = _walk_cold(compiler, dep_path, dep_path, globs, visited);
        _replay_cached(compiler, resolved, globs, visited);
      }

    }

  }

}

int Compiler_read_source(Compiler, String, volatile String *);

void Compiler_report_error(Compiler, Symbol, String, Token, List);

static String _include_text(Compiler c, String target, String path){
  String text = NULL;
  if(! Compiler_read_source(c, path, & text)) Compiler_report_error(c, 306819428, _163, c -> token, cons(_5, cons(String_var(String_join(NULL, cons(String_var(_6), cons(String_var(target), NULL)))), cons(String_var(String_join(NULL, cons(String_var(_7), cons(String_var(path), NULL)))), NULL))));
  return text;
}

Path Path_dirname(Path);

Map Map_copy(Map);

static List _walk_cold(Compiler c, String target, String canonical, Map globs, Map visited){
  String text = _include_text(c, target, canonical);
  _file(c, canonical, text, Path_dirname(canonical), Map_copy(globs), Map_copy(visited));
  return Var_list(Map_getindex(_process_cache(), String_var(canonical)));
}

Compiler Compiler_new_shared(Compiler);

int x2c_source_file(String);

void Compiler_take_unit_state(Compiler, Compiler);

void Compiler_tokenize(Compiler, char *);

Path Path_absolute(Path);

void Compiler_shallow_parse_overlay(Compiler, Map, Map);

void Compiler_return_unit_state(Compiler, Compiler);

Map Sym_file_statics(Sym);

static void _parse_segment(Compiler c, String path, String source, String text, int start_line, int start_pos, Map globs, Map overlay, Map definitions, Map dependencies, int private){
  Compiler shadow = Compiler_new_shared(c);
  {
  _x2c_defer_env_0 _x2c_defer_env_4 = {._x2c_defer_capture_0 =(const void *) & c, ._x2c_defer_capture_1 =(const void *) & shadow};

  X2CCleanup _x2c_defer_record_0 = {
    .fn = _x2c_defer_cleanup_0,
    .env = & _x2c_defer_env_4
  };
  x2c_cleanup_push(&_x2c_defer_record_0);
  {
    int unit = x2c_source_file(path);
    if(! unit) shadow -> package = NULL;
    shadow -> filename = path;
    shadow -> source_private = private;
    Compiler_take_unit_state(shadow, c);
    Compiler_tokenize(shadow, text);
    shadow -> text = source;
    if(c -> source_facts) Map_setindex(c -> source_texts, String_var(Path_absolute(path)), String_var(source));
    for(size_t i = 0;  i < Bytes_len(shadow -> tokenizer -> tokens);  i ++){
      Token token = &((struct Token *) shadow -> tokenizer -> tokens)[i];
      token -> line += start_line - 1;
      token -> pos += start_pos;
    }
    Compiler_shallow_parse_overlay(shadow, globs, overlay);
    Compiler_return_unit_state(shadow, c);
    if(unit){
      Map_merge(c -> fn_defs, shadow -> fn_defs);
      Map_merge(definitions, shadow -> fn_defs);
    }
    _cache_dependencies(dependencies, shadow -> deps);
    Compiler_merge_translation_dependencies(c, shadow -> deps);
    Map_merge(globs, overlay);
    Compiler_merge_source_declarations(c, globs, overlay);
    if(private) _keep_published_rows(Sym_file_statics(shadow -> sym), overlay);
    if(unit) _publish_unit_statics(Sym_file_statics(shadow -> sym), overlay, path);
  }
  x2c_cleanup_leave(& _x2c_defer_record_0);

}
}

int Type_is_function(Type);

Type List_type(List);

static int _external_function(Map statics, String name, Var type){
  return Var_is_row(type, 9, 7, 4) && Type_is_function(List_type(Var_list(type))) && ! Map_contains(statics, List_var(cons(_8, cons(String_var(name), NULL))));
}

Var Map_del(Map, Var);

static void _keep_published_rows(Map statics, Map overlay){
  Array dropped = Array_new();
  {
    Var key, value;
    Map _x2c_macro_object_5 = overlay;
    unsigned _x2c_macro_cursor_5 = 0;
    Var _x2c_macro_cursor_output_4;
    Var _x2c_macro_cursor_output_5;
    while(Map_try_next(_x2c_macro_object_5, & _x2c_macro_cursor_5, & _x2c_macro_cursor_output_4, & _x2c_macro_cursor_output_5)){
      key = _x2c_macro_cursor_output_4;
      value = _x2c_macro_cursor_output_5;
      {
        int crosses = 0;

  {
    List _x2c_match_expr = cons(key, NULL);
    Var _x2c_match_values[1];
        MatchCaptureBuffer _x2c_match_capture = { .values = _x2c_match_values, .capacity = 1 };

    switch (0) {
      default: ;  static MatchCaptureSite _x2c_match_site_0;  if (x2c_match_site_try_capture(& _x2c_match_site_0, _x2c_match_expr, List_var(_15), &_x2c_match_capture)) {crosses = 1;  break;
      }
      static MatchCaptureSite _x2c_match_site_1;  if (x2c_match_site_try_capture(& _x2c_match_site_1, _x2c_match_expr, List_var(_31), &_x2c_match_capture)) {Var name = _x2c_match_values[0]; {
        Var _x2c_match_value_0 = name; {
          String name = Var_string(_x2c_match_value_0);  crosses = _external_function(statics, name, value);
        }

      }
      break;
    }
    static MatchCaptureSite _x2c_match_site_2;  if (x2c_match_site_try_capture(& _x2c_match_site_2, _x2c_match_expr, List_var(_38), &_x2c_match_capture)) {Var name = _x2c_match_values[0]; {
      Var _x2c_match_value_1 = name; {
        String name = Var_string(_x2c_match_value_1);  crosses = _external_function(statics, name, value);
      }

    }
    break;
  }

    }
  }
if(! crosses) Array_push(dropped, key);
}
}
}
{
  Var key;  Array _x2c_macro_object_6 = dropped;  int _x2c_macro_cursor_6 = 0;  Var _x2c_macro_cursor_output_6;  while(Array_try_next(_x2c_macro_object_6, & _x2c_macro_cursor_6, & _x2c_macro_cursor_output_6)){
    key = _x2c_macro_cursor_output_6;  Map_del(overlay, key);
  }

}
Array_free(dropped);
}

Iter Map_keys(Map, Iter);
static void _publish_unit_statics(Map statics, Map overlay, String path){
  List owner = cons(String_var(path), NULL); {
    Var key;  Iter _x2c_macro_iterator_7 = Map_keys(statics, &(struct Iter){
      int_var(0)
    }
    );  Var _x2c_macro_item_7;  while(Iter_try_next(_x2c_macro_iterator_7, & _x2c_macro_item_7)){
      key = _x2c_macro_item_7;
  {
    List _x2c_match_expr = cons(key, NULL);
    Var _x2c_match_values[1];  MatchCaptureBuffer _x2c_match_capture = { .values = _x2c_match_values, .capacity = 1 };
    switch (0) {
      default: ;  static MatchCaptureSite _x2c_match_site_3;  if (x2c_match_site_try_capture(& _x2c_match_site_3, _x2c_match_expr, List_var(_44), &_x2c_match_capture)) {Var name = _x2c_match_values[0]; {
        Var _x2c_match_value_2 = name; {
          String name = Var_string(_x2c_match_value_2); {
            Map_del(overlay, List_var(cons(String_var(name), NULL)));  Map_del(overlay, List_var(cons(_32, cons(String_var(name), NULL))));  Map_setindex(overlay, List_var(cons(_46, cons(String_var(name), NULL))), List_var(owner));
          }

        }

      }
      break;
    }

    }
  }
  }

}
}

unsigned Map_len(Map);
Var Map_var(Map);
static void _flush_segment(Compiler compiler, String path, String source, String text, int start_line, int start_pos, Map globs, Array parts, Map definitions, Map dependencies, int private){
  if(! String_truth(text) || ! * text) return;  Scope_push(& process_cache_scope);  Map overlay = Map_new();  Scope_pop();  _parse_segment(compiler, path, source, text, start_line, start_pos, globs, overlay, definitions, dependencies, private);  if(! Map_len(overlay)) return;  Var overlay_var = Map_var(overlay);  Array_push(parts, overlay_var);
}

String String_printf(String, ...);
unsigned String_hash(String);
Var List_cadr(List);
static String _include(Compiler c, String target, int angle, String dir, Map globs, Map visited, Map dependencies){
  int covered = 0;  String path = _resolve_include(c, dir, target, angle, & covered);  if(! String_truth(path)) return NULL;  if(covered && ! x2c_source_file(path)) return NULL;  String canonical = _canonical_path(path);  List entry = _entry(c, canonical);  Compiler_add_translation_dependency(c, canonical);  if(! Map_contains(visited, String_var(canonical))){
    Map_setindex(visited, String_var(canonical), int_var(1));  if(! List_truth(entry)) entry = _walk_cold(c, target, canonical, globs, visited);  _replay_cached(c, entry, globs, visited);
  }
  Var walked = Map_getindex(_process_cache(), String_var(canonical));  String content_hash = Var_string(Var_is_void(walked) ? String_var(String_printf(_47, String_hash(_include_text(c, target, canonical)))) : List_cadr(Var_list(walked)));  _cache_dependency(dependencies, canonical, String_var(content_hash));  return canonical;
}

static void _require_retained(int owned){
  if(owned) return;  fprintf(stderr, "x2c: could not retain process cache entry\n");  abort();
}

int List_try_own(List);
List Type_list(Type);
void Compiler_record_generated_symbol(Compiler c, String name, Type signature){
  if(! _init_guard_) _file_init_();  Var cached = Map_getindex(_process_cache(), String_var(_canonical_path(c -> filename)));  if(Var_is_void(cached)) return;  Map contribution = NULL; {
    Var part;  Iter _x2c_macro_iterator_8 = Var_iter(List_car(Var_list(cached)), &(struct Iter){
      int_var(0)
    }
    );  Var _x2c_macro_item_8;  while(Iter_try_next(_x2c_macro_iterator_8, & _x2c_macro_item_8)){
      part = _x2c_macro_item_8;  if(Var_is(part, 26720)) contribution = Var_map(part);
    }

  }
  if((void *) contribution == NULL) return;  List key = cons(String_var(name), NULL), marker_key = cons(_49, cons(String_var(name), NULL));  List marker = _51;  _require_retained(List_try_own(key));  _require_retained(List_try_own(marker_key));  _require_retained(List_try_own(marker));  _require_retained(List_try_own(Type_list(signature)));  Map_setindex(contribution, List_var(key), List_var(signature));  Map_setindex(contribution, List_var(marker_key), List_var(marker));
}

Tokenizer Tokenizer_new(char *);
void Tokenizer_scan(Tokenizer);
String preproc_include_target(String, int *);
Map Compiler_select_declaration_defaults(Compiler, String, Map, Array, Map);
int Map_truth(Map);
List Array_list_free(Array);
Array Array_sort(Array);
static void _file(Compiler c, String path, String text, String dir, Map globs, Map visited){
  Map enclosing_aliases = c -> kw_aliases, enclosing_alias_imports = c -> kw_seen; {
    List * _x2c_macro_address_0 = & c -> declaration_effects;  List _x2c_macro_previous_0 = * _x2c_macro_address_0; {
  _x2c_defer_env_1 _x2c_defer_env_5 = {._x2c_defer_capture_2 =(const void *) & _x2c_macro_address_0, ._x2c_defer_capture_3 =(const void *) & _x2c_macro_previous_0};
  X2CCleanup _x2c_defer_record_1 = {
    .fn = _x2c_defer_cleanup_1,
    .env = & _x2c_defer_env_5
  };
  x2c_cleanup_push(&_x2c_defer_record_1);
  {
      * _x2c_macro_address_0 = NULL; {
        c -> kw_aliases = Map_new();  c -> kw_seen = Map_new();  Array parts = Array_new();  Scope_push(& process_cache_scope);  Map dependencies = Map_new();  Scope_pop();  Map definitions = Map_new();  int private = 0;  String content_hash = String_printf(_47, String_hash(text));  Tokenizer tokenizer = Tokenizer_new(text);  Tokenizer_scan(tokenizer);  Token first = tokenizer -> tokens;  int segment_line = 1, segment_position = 0;  for(Token token = first;  token -> type != 11212;  token ++){
          if(token -> type != 35579270086 || ! _starts_line(first, token)) continue;  int angle = 0, visibility = _visibility_pragma(token -> text);  String target = preproc_include_target(token -> text, & angle);  if(! String_truth(target) && visibility < 0) continue;  _flush_segment(c, path, text, String_getslice(text, segment_position, token -> pos, 1), segment_line, segment_position, globs, parts, definitions, dependencies, private);  if(String_truth(target)){
            String canonical = _include(c, target, angle, dir, globs, visited, dependencies);  if(String_truth(canonical)) Array_push(parts, String_var(canonical));
          }
          else{
            private = visibility;  Symbol marker = private ? 35588017418 : 1117938246;  Array_push(parts, Symbol_var(marker));
          }
          Token next = token + 1;  segment_line = next -> line;  segment_position = next -> pos;
        }
        _flush_segment(c, path, text, String_getslice(text, segment_position, -2147483648, 1), segment_line, segment_position, globs, parts, definitions, dependencies, private);  Map generated = Compiler_select_declaration_defaults(c, path, globs, parts, definitions);  if(Map_truth(generated) && Map_len(generated)){
          Scope_push(& process_cache_scope);  Map retained = Map_copy(generated);  Scope_pop();  Array_push(parts, Map_var(retained));
        }
        List part_list = Array_list_free(parts);  _require_retained(String_try_own(path)); {
          Var part;  List _x2c_macro_object_10 = part_list;  List _x2c_macro_cursor_10 = _x2c_macro_object_10;  Var _x2c_macro_cursor_output_9;  while(List_try_next(_x2c_macro_object_10, & _x2c_macro_cursor_10, & _x2c_macro_cursor_output_9)){
            part = _x2c_macro_cursor_output_9; {
              if(! Var_is(part, 26720)) continue;  Map rows = Var_map(part); {
                Var key, value;  Map _x2c_macro_object_9 = rows;  unsigned _x2c_macro_cursor_9 = 0;  Var _x2c_macro_cursor_output_7;  Var _x2c_macro_cursor_output_8;  while(Map_try_next(_x2c_macro_object_9, & _x2c_macro_cursor_9, & _x2c_macro_cursor_output_7, & _x2c_macro_cursor_output_8)){
                  key = _x2c_macro_cursor_output_7;  value = _x2c_macro_cursor_output_8; {
                    if(Var_is_row(key, 9, 7, 4)) _require_retained(List_try_own(Var_list(key)));  if(Var_is_row(key, 11, 7, 1)) _require_retained(String_try_own(Var_string(key)));  if(Var_is_row(value, 9, 7, 4)) _require_retained(List_try_own(Var_list(value)));  if(Var_is_row(value, 11, 7, 1)) _require_retained(String_try_own(Var_string(value)));
                  }

                }

              }

            }

          }

        }
        Array names = Array_new(); {
          Var definition;  Iter _x2c_macro_iterator_11 = Map_keys(definitions, &(struct Iter){
            int_var(0)
          }
          );  Var _x2c_macro_item_11;  while(Iter_try_next(_x2c_macro_iterator_11, & _x2c_macro_item_11)){
            definition = _x2c_macro_item_11;  Array_push(names, definition);
          }

        }
        Array_sort(names);  List definition_list = Array_list_free(names);  List entry = cons(List_var(part_list), cons(String_var(content_hash), cons(List_var(definition_list), cons(Map_var(dependencies), NULL))));  _require_retained(List_try_own(entry));  if(! Map_contains(_process_cache(), String_var(path))) Map_setindex(_process_cache(), String_var(path), List_var(entry));  c -> kw_aliases = enclosing_aliases;  c -> kw_seen = enclosing_alias_imports;
      }

    }
    x2c_cleanup_leave(& _x2c_defer_record_1);
}
  }

}

static String _runtime_text(Compiler c, String runtime){
  String text = NULL;  if(! Compiler_read_source(c, runtime, & text)) Compiler_report_error(c, 306819428, _164, c -> token, cons(String_var(String_join(NULL, cons(String_var(_7), cons(String_var(runtime), NULL)))), NULL));
  return text;
}

static List _prelude_entry(Compiler c, String runtime, String canonical){
  List entry = _entry(c, canonical);
  if(List_truth(entry)) return entry;
  Map scratch = Map_new(), visited = Map_new();
  Map_setindex(visited, String_var(canonical), int_var(1));
  _file(c, canonical, _runtime_text(c, runtime), Path_dirname(runtime), scratch, visited);
  return Var_list(Map_getindex(_process_cache(), String_var(canonical)));
}

Map Compiler_collect_symbols(Compiler c, Map globs){
  if(! _init_guard_) _file_init_();
  if((void *) globs == NULL) globs = Map_new();
  c -> kw_aliases = NULL;
  c -> kw_seen = NULL;
  Map visited = Map_new();
  String canonical = _canonical_path(c -> filename);
  c -> deps = Map_new();
  Compiler_add_translation_dependency(c, canonical);
  if(c -> prelude){
    String runtime = String_join(NULL, cons(String_var(x2c_get_root()), cons(String_var(_52), NULL)));
    String runtime_canonical = _canonical_path(runtime);
    Map_setindex(visited, String_var(runtime_canonical), int_var(1));
    Compiler_add_translation_dependency(c, runtime_canonical);
    if(c -> runtime_hdrs) _file(c, runtime_canonical, _runtime_text(c, runtime), Path_dirname(runtime), globs, visited);
    else _replay_cached(c, _prelude_entry(c, runtime, runtime_canonical), globs, visited);
  }
  Map_setindex(visited, String_var(canonical), int_var(1));
  _file(c, canonical, c -> text, Path_dirname(c -> filename), globs, visited);
  return globs;
}

static String _package_entry(Compiler compiler, String name, String * directory){
  {
    String package_dir;
    List _x2c_macro_object_12 = compiler -> package_dirs;
    List _x2c_macro_cursor_12 = _x2c_macro_object_12;
    Var _x2c_macro_cursor_output_10;
    while(List_try_next(_x2c_macro_object_12, & _x2c_macro_cursor_12, & _x2c_macro_cursor_output_10)){
      package_dir = Var_string(_x2c_macro_cursor_output_10);
      {
        String root = String_join(NULL, cons(String_var(_canonical_path(package_dir)), cons(String_var(_3), cons(String_var(name), NULL))));
        String nested = String_join(NULL, cons(String_var(root), cons(String_var(_53), cons(String_var(name), cons(String_var(_54), NULL)))));
        String entry = SourceView_exists(compiler -> sources, nested) ? nested : String_join(NULL, cons(String_var(root), cons(String_var(_3), cons(String_var(name), cons(String_var(_54), NULL)))));
        if(! SourceView_exists(compiler -> sources, entry)) continue;
        if(directory) * directory = root;
        return _canonical_path(entry);
      }

    }

  }
  return NULL;
}

List List_cdr(List);

List List_cddr(List);

static String _package_key_spelling(List key){
  Var head, spelling_value;
  List _x2c_destructure_0 = key;
  head = List_getindex(_x2c_destructure_0, 0);
  spelling_value = List_getindex(_x2c_destructure_0, 1);
  if(Var_is_row(head, 11, 7, 1)){
    String spelling = Var_string(head);
    if(List_truth(List_cdr(key)) || String_equal(spelling, _55)) return NULL;
    return String_equal(spelling, _56) ? NULL : spelling;
  }
  if(Var_equal(head, Symbol_var(1256204))) return List_truth(List_cdr(key)) && ! List_truth(List_cddr(key)) && Var_is_row(spelling_value, 11, 7, 1) ? Var_string(spelling_value) : NULL;
  if(! Var_equal(head, Symbol_var(44661285196)) && ! Var_equal(head, Symbol_var(1318234344)) && ! Var_equal(head, Symbol_var(44977116)) && ! Var_equal(head, Symbol_var(357722))) return NULL;
  return List_truth(List_cdr(key)) && Var_is_row(spelling_value, 11, 7, 1) ? Var_string(spelling_value) : NULL;
}

int List_contains(List, Var);

static int _package_protocol_row(List key, Var value){
  if(! Var_equal(List_car(key), String_var(_55)) || ! Var_is_row(value, 9, 7, 4)) return 0;
  List row = Var_list(value);
  return List_truth(row) && List_contains(_66, List_car(row));
}

int Var_is_nil(Var);

void Compiler_copy_source_declaration(Compiler, Map, Map, List);

Var List_last(List);

List String_split(String, String);

static void _package_merge(Compiler compiler, String name, String root, String path, Map part, Map merged, Token token){
  String prefix = String_join(NULL, cons(String_var(name), cons(String_var(_67), NULL)));
  int header = ! x2c_source_file(path) || String_startswith(path, String_join(NULL, cons(String_var(_canonical_lib()), cons(String_var(_3), NULL)))) || String_startswith(path, String_join(NULL, cons(String_var(_canonical_include()), cons(String_var(_3), NULL))));
  int foreign = ! String_startswith(path, String_join(NULL, cons(String_var(root), cons(String_var(_3), NULL))));
  {
    Var key, value;
    Map _x2c_macro_object_13 = part;
    unsigned _x2c_macro_cursor_13 = 0;
    Var _x2c_macro_cursor_output_11;
    Var _x2c_macro_cursor_output_12;
    while(Map_try_next(_x2c_macro_object_13, & _x2c_macro_cursor_13, & _x2c_macro_cursor_output_11, & _x2c_macro_cursor_output_12)){
      key = _x2c_macro_cursor_output_11;
      value = _x2c_macro_cursor_output_12;
      {
        if(! Var_is_row(key, 9, 7, 4) || Var_is_nil(key)) continue;
        if(_package_protocol_row(Var_list(key), value)){
          Map_setindex(merged, key, value);
          Compiler_copy_source_declaration(compiler, merged, part, Var_list(key));
          continue;
        }
        String spelling = _package_key_spelling(Var_list(key));
        if(! String_truth(spelling)) continue;
        if(header || String_startswith(spelling, prefix)){
          Map_setindex(merged, key, value);
          Compiler_copy_source_declaration(compiler, merged, part, Var_list(key));
          continue;
        }
        if(! foreign) continue;
        String unit = Var_string(List_last(String_split(path, _162)));
        String fix = String_join(NULL, cons(String_var(_68), cons(String_var(name), cons(String_var(_69), NULL))));
        Compiler_report_error(compiler, 306819428, String_join(NULL, cons(String_var(_70), cons(String_var(name), cons(String_var(_71), cons(String_var(spelling), cons(String_var(_72), NULL)))))), token, cons(String_var(String_join(NULL, cons(String_var(_72), cons(String_var(unit), cons(String_var(_73), cons(String_var(fix), NULL)))))), NULL));
      }

    }

  }

}

static void _package_contributions(Compiler compiler, String name, String root, String path, List entry, Map merged, Map visited, Token token){
  Compiler_merge_translation_dependencies(compiler, Var_map(List_getindex(entry, 3)));
  int private = 0;
  {
    Var part;
    Iter _x2c_macro_iterator_14 = Var_iter(List_car(entry), &(struct Iter){
      int_var(0)
    }
    );
    Var _x2c_macro_item_14;
    while(Iter_try_next(_x2c_macro_iterator_14, & _x2c_macro_item_14)){
      part = _x2c_macro_item_14;
      {

  {
    List _x2c_match_expr = cons(part, NULL);
    Var _x2c_match_values[1];
        MatchCaptureBuffer _x2c_match_capture = { .values = _x2c_match_values, .capacity = 1 };

    switch (0) {
      default: ;  static MatchCaptureSite _x2c_match_site_4;  if (x2c_match_site_try_capture(& _x2c_match_site_4, _x2c_match_expr, List_var(_83), &_x2c_match_capture)) {Var declarations = _x2c_match_values[0]; {
          Var _x2c_match_value_3 = declarations; {
            Map declarations = Var_map(_x2c_match_value_3); {
              _package_merge(compiler, name, root, path, declarations, merged, token);  continue;
            }

          }

        }
        break;
      }
      { List _x2c_match_cursor;  if (_x2c_match_expr && _x2c_match_expr->car.u64 == 9224497972349635850ULL && (_x2c_match_cursor = _x2c_match_expr->cdr, 1) && !_x2c_match_cursor) {{
        private = 1;  continue;
      }
      break; } }{ List _x2c_match_cursor;  if (_x2c_match_expr && _x2c_match_expr->car.u64 == 9224497937879556678ULL && (_x2c_match_cursor = _x2c_match_expr->cdr, 1) && !_x2c_match_cursor) {{
        private = 0;  continue;
      }
      break; } } static MatchCaptureSite _x2c_match_site_5;  if (x2c_match_site_try_capture(& _x2c_match_site_5, _x2c_match_expr, List_var(_94), &_x2c_match_capture)) {Var dependency = _x2c_match_values[0]; {
        Var _x2c_match_value_4 = dependency; {
          String dependency = Var_string(_x2c_match_value_4); {
            Compiler_add_translation_dependency(compiler, dependency);  if(private || Map_contains(visited, String_var(dependency))) continue;  Map_setindex(visited, String_var(dependency), int_var(1));  _package_contributions(compiler, name, root, dependency, Var_list(Map_getindex(_process_cache(), String_var(dependency))), merged, visited, token);  continue;
          }

        }

      }
      break;
    }

    }
  }
__builtin_unreachable();
  }

}
}
}

Map Sym_base_symbols(Sym);
void Sym_set(Sym, List, List);
Map Sym_current_symbols(Sym);
void Compiler_collect_package(Compiler c, String name, Token token){
  if(! _init_guard_) _file_init_();  if(Map_contains(c -> package_roots, String_var(name))) return;  String root = NULL, entry = _package_entry(c, name, & root);  if(! String_truth(entry)) Compiler_report_error(c, 306819428, String_join(NULL, cons(String_var(_95), cons(String_var(name), cons(String_var(_72), NULL)))), token, cons(String_var(String_join(NULL, cons(String_var(_96), cons(String_var(name), cons(String_var(_53), cons(String_var(name), cons(String_var(_97), cons(String_var(name), cons(String_var(_3), cons(String_var(name), cons(String_var(_54), NULL))))))))))), NULL));  Compiler package = Compiler_new_shared(c); {
  _x2c_defer_env_2 _x2c_defer_env_6 = {._x2c_defer_capture_4 =(const void *) & c, ._x2c_defer_capture_5 =(const void *) & package};
  X2CCleanup _x2c_defer_record_2 = {
    .fn = _x2c_defer_cleanup_2,
    .env = & _x2c_defer_env_6
  };
  x2c_cleanup_push(&_x2c_defer_record_2);
  {
    package -> package = name;  package -> filename = entry;  Map globs = Sym_base_symbols(c -> sym), visited = Map_new();
    Map_setindex(visited, String_var(entry), int_var(1));
    List cached = _entry(c, entry);
    if(List_truth(cached)) _replay_cached(package, cached, globs, visited);
    else{
      String text = NULL;
      if(! Compiler_read_source(package, entry, & text)) Compiler_report_error(c, 306819428, String_join(NULL, cons(String_var(_98), cons(String_var(name), cons(String_var(_72), NULL)))), token, cons(String_var(String_join(NULL, cons(String_var(_7), cons(String_var(entry), NULL)))), NULL));
      _file(package, entry, text, Path_dirname(entry), globs, visited);
    }
    Map_merge(c -> fn_defs, package -> fn_defs);
    Map merged = Map_new(), walked = Map_new();
    Map_setindex(walked, String_var(entry), int_var(1));
    Compiler_add_translation_dependency(c, entry);
    _package_contributions(c, name, root, entry, Var_list(Map_getindex(_process_cache(), String_var(entry))), merged, walked, token);
    Map_setindex(c -> package_roots, String_var(name), String_var(root));
    {
      Var key, value;
      Map _x2c_macro_object_15 = merged;
      unsigned _x2c_macro_cursor_15 = 0;
      Var _x2c_macro_cursor_output_13;
      Var _x2c_macro_cursor_output_14;
      while(Map_try_next(_x2c_macro_object_15, & _x2c_macro_cursor_15, & _x2c_macro_cursor_output_13, & _x2c_macro_cursor_output_14)){
        key = _x2c_macro_cursor_output_13;
        value = _x2c_macro_cursor_output_14;
        {
          Sym_set(c -> sym, Var_list(key), Var_list(value));
          Compiler_copy_source_declaration(c, Sym_current_symbols(c -> sym), merged, Var_list(key));
        }

      }

    }

  }
  x2c_cleanup_leave(& _x2c_defer_record_2);

}
}

String x2c_stage_dir(void);

void interface_configure(String out_dir){
  if(! _init_guard_) _file_init_();
  _process_cache();
  interface_out_dir = out_dir;
  String stage = x2c_stage_dir();
  interface_mirror = String_truth(stage) ? stage : x2c_get_root();
}

String Path_stem(Path);

String home_portable_path(String);

static List _interface_candidates(String canonical){
  String stem = Path_stem(canonical), relative = home_portable_path(canonical);
  String dir = Path_dirname(canonical);
  Array paths = Array_new();
  if(String_truth(interface_out_dir)) Array_push(paths, String_var(String_join(NULL, cons(String_var(interface_out_dir), cons(String_var(_3), cons(String_var(stem), cons(String_var(_99), NULL)))))));
  if(! String_equal(relative, canonical)){
    String mirror = String_join(NULL, cons(String_var(Path_dirname(relative)), cons(String_var(_3), cons(String_var(stem), cons(String_var(_99), NULL)))));
    if(String_truth(interface_out_dir)) Array_push(paths, String_var(String_join(NULL, cons(String_var(interface_out_dir), cons(String_var(_100), cons(String_var(mirror), NULL))))));
    Array_push(paths, String_var(String_join(NULL, cons(String_var(interface_mirror), cons(String_var(_3), cons(String_var(mirror), NULL))))));
  }
  Array_push(paths, String_var(String_join(NULL, cons(String_var(dir), cons(String_var(_101), cons(String_var(stem), cons(String_var(_99), NULL)))))));
  Array_push(paths, String_var(String_join(NULL, cons(String_var(dir), cons(String_var(_102), cons(String_var(stem), cons(String_var(_99), NULL)))))));
  return Array_list_free(paths);
}

String interface_prelude(void){
  if(! _init_guard_) _file_init_();
  String runtime = _canonical_path(String_join(NULL, cons(String_var(x2c_get_root()), cons(String_var(_52), NULL))));
  {
    String path;
    List _x2c_macro_object_16 = _interface_candidates(runtime);
    List _x2c_macro_cursor_16 = _x2c_macro_object_16;
    Var _x2c_macro_cursor_output_15;
    while(List_try_next(_x2c_macro_object_16, & _x2c_macro_cursor_16, & _x2c_macro_cursor_output_15)){
      path = Var_string(_x2c_macro_cursor_output_15);
      if(! access(path, R_OK)) return path;
    }

  }
  return NULL;
}

void Lisp_destroy(Lisp);

static void _interface_shutdown(void){
  Lisp_destroy(interface_reader);
  interface_reader = NULL;
  source_hashes = NULL;
}

Lisp Lisp_kernel(void);

static Lisp _interface_lisp(void){
  if(interface_reader) return interface_reader;
  _process_cache();
  Scope_push(& process_cache_scope);
  interface_reader = Lisp_kernel();
  source_hashes = Map_new();
  Scope_shutdown_hook(_interface_shutdown);
  Scope_pop();
  return interface_reader;
}

static int _hash_matches(Compiler compiler, String path, Var expected){
  if(! Var_is_row(expected, 11, 7, 1)) return 0;
  Var hash = Map_getindex(source_hashes, String_var(path));
  if(Var_is_void(hash)){
    String text = NULL;
    {
      ExceptionFrame _x2c_exception_frame_0;
      static MatchCaptureSite _x2c_catch_arms_0[3];
      static ErrorCatchSite _x2c_catch_site_0 = {  _x2c_catch_arms_0, -1, 3, ERROR_CATCH_PENDING, -1 };
      Var _x2c_catch_patterns_0[3];
      if (x2c_error_catch_site_pending(&_x2c_catch_site_0)) {List _x2c_catch_pattern_0 = cons(Symbol_var(20399393368), cons(Symbol_var(54), NULL));
      _x2c_catch_patterns_0[0] = List_var(_x2c_catch_pattern_0);
      List _x2c_catch_pattern_1 = cons(Symbol_var(4372499598), cons(Symbol_var(54), NULL));
      _x2c_catch_patterns_0[1] = List_var(_x2c_catch_pattern_1);
      List _x2c_catch_pattern_2 = cons(Symbol_var(1358596898646632), cons(Symbol_var(54), NULL));
      _x2c_catch_patterns_0[2] = List_var(_x2c_catch_pattern_2);
    }
    ErrorHandler volatile _x2c_error_handler_0 = x2c_error_catch_site_push(&_x2c_exception_frame_0, &_x2c_catch_site_0, _x2c_catch_patterns_0);  x2c_exception_push(& _x2c_exception_frame_0);  if (!sigsetjmp(_x2c_exception_frame_0.env, 0)){
      if(! Compiler_read_source(compiler, path, & text)){
        int _x2c_return_value_0 = 0; {
          x2c_error_catch_close(_x2c_error_handler_0);  _x2c_error_handler_0 = NULL;  x2c_exception_leave(& _x2c_exception_frame_0);  return _x2c_return_value_0;
        }

      }

    }
    else {x2c_exception_landed(& _x2c_exception_frame_0); {
      if (x2c_exception_is_error_target(&_x2c_exception_frame_0)){
        int _x2c_catch_selected_0 = x2c_error_catch_selected(_x2c_error_handler_0);
        x2c_error_catch_detach(_x2c_error_handler_0);
        x2c_exception_mark_handled(&_x2c_exception_frame_0);
        if (_x2c_catch_selected_0 == 0) {{
          int _x2c_return_value_1 = 0;
          {
            x2c_error_catch_close(_x2c_error_handler_0);
            _x2c_error_handler_0 = NULL;
            x2c_exception_leave(& _x2c_exception_frame_0);
            return _x2c_return_value_1;
          }

        }

      }
      else if (_x2c_catch_selected_0 == 1) {{
        int _x2c_return_value_2 = 0;
        {
          x2c_error_catch_close(_x2c_error_handler_0);
          _x2c_error_handler_0 = NULL;
          x2c_exception_leave(& _x2c_exception_frame_0);
          return _x2c_return_value_2;
        }

      }

    }
    else {{
      int _x2c_return_value_3 = 0;
      {
        x2c_error_catch_close(_x2c_error_handler_0);
        _x2c_error_handler_0 = NULL;
        x2c_exception_leave(& _x2c_exception_frame_0);
        return _x2c_return_value_3;
      }

    }

  }

}
else{
  x2c_error_catch_close(_x2c_error_handler_0);
  _x2c_error_handler_0 = NULL;
  x2c_exception_leave(& _x2c_exception_frame_0);
  __builtin_unreachable();
}
}
}
x2c_error_catch_close(_x2c_error_handler_0);
_x2c_error_handler_0 = NULL;
x2c_exception_leave(& _x2c_exception_frame_0);
}
String value = String_printf(_47, String_hash(text));
_require_retained(String_try_own(path));
_require_retained(String_try_own(value));
Map_setindex(source_hashes, String_var(path), String_var(value));
hash = String_var(value);
}
return String_equal(Var_string(hash), Var_string(expected));
}

String File_string_close(File);

Symbol Lisp_read(Lisp, String, unsigned *, Var *);

String x2c_compiler_identity(void);

String home_absolute_path(String);

static List _interface_load(Compiler c, String canonical, String path){
  String volatile source = NULL;
  File input = fopen(path, "r");
  if(! input) return NULL;
  {
    ExceptionFrame _x2c_exception_frame_1;
    static MatchCaptureSite _x2c_catch_arms_1[1];
    static ErrorCatchSite _x2c_catch_site_1 = {  _x2c_catch_arms_1, -1, 1, ERROR_CATCH_PENDING, -1 };
    Var _x2c_catch_patterns_1[1];
    if (x2c_error_catch_site_pending(&_x2c_catch_site_1)) {List _x2c_catch_pattern_3 = cons(Symbol_var(20399393368), cons(Symbol_var(54), NULL));
    _x2c_catch_patterns_1[0] = List_var(_x2c_catch_pattern_3);
  }
  ErrorHandler volatile _x2c_error_handler_1 = x2c_error_catch_site_push(&_x2c_exception_frame_1, &_x2c_catch_site_1, _x2c_catch_patterns_1);  x2c_exception_push(& _x2c_exception_frame_1);  if (!sigsetjmp(_x2c_exception_frame_1.env, 0)) source = File_string_close(input);  else {x2c_exception_landed(& _x2c_exception_frame_1); {
    if (x2c_exception_is_error_target(&_x2c_exception_frame_1)){
      x2c_error_catch_detach(_x2c_error_handler_1);
      x2c_exception_mark_handled(&_x2c_exception_frame_1);
       {{
        List _x2c_return_value_4 = NULL;
        {
          x2c_error_catch_close(_x2c_error_handler_1);
          _x2c_error_handler_1 = NULL;
          x2c_exception_leave(& _x2c_exception_frame_1);
          return _x2c_return_value_4;
        }

      }

    }

  }
  else{
    x2c_error_catch_close(_x2c_error_handler_1);
    _x2c_error_handler_1 = NULL;
    x2c_exception_leave(& _x2c_exception_frame_1);
    __builtin_unreachable();
  }

}
}
x2c_error_catch_close(_x2c_error_handler_1);
_x2c_error_handler_1 = NULL;
x2c_exception_leave(& _x2c_exception_frame_1);
}
unsigned cursor = 0;
Var record =((void) 0, Void);
Symbol volatile status = 0;
{
  ExceptionFrame _x2c_exception_frame_2;
  static MatchCaptureSite _x2c_catch_arms_2[2];
  static ErrorCatchSite _x2c_catch_site_2 = {  _x2c_catch_arms_2, -1, 2, ERROR_CATCH_PENDING, -1 };
  Var _x2c_catch_patterns_2[2];
  if (x2c_error_catch_site_pending(&_x2c_catch_site_2)) {List _x2c_catch_pattern_4 = cons(Symbol_var(664344300629258), cons(Symbol_var(54), NULL));
  _x2c_catch_patterns_2[0] = List_var(_x2c_catch_pattern_4);
  List _x2c_catch_pattern_5 = cons(Symbol_var(28682226919752), cons(Symbol_var(54), NULL));
  _x2c_catch_patterns_2[1] = List_var(_x2c_catch_pattern_5);
}
ErrorHandler volatile _x2c_error_handler_2 = x2c_error_catch_site_push(&_x2c_exception_frame_2, &_x2c_catch_site_2, _x2c_catch_patterns_2);  x2c_exception_push(& _x2c_exception_frame_2);  if (!sigsetjmp(_x2c_exception_frame_2.env, 0)) status = Lisp_read(_interface_lisp(), source, & cursor, & record);  else {x2c_exception_landed(& _x2c_exception_frame_2); {
  if (x2c_exception_is_error_target(&_x2c_exception_frame_2)){
    int _x2c_catch_selected_2 = x2c_error_catch_selected(_x2c_error_handler_2);
    x2c_error_catch_detach(_x2c_error_handler_2);
    x2c_exception_mark_handled(&_x2c_exception_frame_2);
    if (_x2c_catch_selected_2 == 0) {{
      List _x2c_return_value_5 = NULL;
      {
        x2c_error_catch_close(_x2c_error_handler_2);
        _x2c_error_handler_2 = NULL;
        x2c_exception_leave(& _x2c_exception_frame_2);
        return _x2c_return_value_5;
      }

    }

  }
  else {{
    List _x2c_return_value_6 = NULL;
    {
      x2c_error_catch_close(_x2c_error_handler_2);
      _x2c_error_handler_2 = NULL;
      x2c_exception_leave(& _x2c_exception_frame_2);
      return _x2c_return_value_6;
    }

  }

}
}
else{
  x2c_error_catch_close(_x2c_error_handler_2);
  _x2c_error_handler_2 = NULL;
  x2c_exception_leave(& _x2c_exception_frame_2);
  __builtin_unreachable();
}
}
}
x2c_error_catch_close(_x2c_error_handler_2);
_x2c_error_handler_2 = NULL;
x2c_exception_leave(& _x2c_exception_frame_2);
}
if(status != 46228810 || ! Var_is_row(record, 9, 7, 4)) return NULL;

  {
    List _x2c_match_expr = Var_list(record);
    Var _x2c_match_values[6];
MatchCaptureBuffer _x2c_match_capture = { .values = _x2c_match_values, .capacity = 6 };

    switch (Var_symbol(car(_x2c_match_expr))) {
      case 20796605335754: ;
static MatchCaptureSite _x2c_match_site_6;
if (x2c_match_site_try_capture(& _x2c_match_site_6, _x2c_match_expr, List_var(_153), &_x2c_match_capture)) {Var compiler = _x2c_match_values[0];  Var owner = _x2c_match_values[1];  Var hash = _x2c_match_values[2];  Var stored_parts = _x2c_match_values[3];  Var definitions = _x2c_match_values[4];  Var stored_dependencies = _x2c_match_values[5]; {
  Var _x2c_match_value_5 = compiler;  Var _x2c_match_value_6 = owner;  Var _x2c_match_value_7 = hash;  Var _x2c_match_value_8 = stored_parts;  Var _x2c_match_value_9 = definitions;  Var _x2c_match_value_10 = stored_dependencies; {
    String compiler = Var_string(_x2c_match_value_5);  String owner = Var_string(_x2c_match_value_6);  String hash = Var_string(_x2c_match_value_7);  List stored_parts = Var_list(_x2c_match_value_8);  List definitions = Var_list(_x2c_match_value_9);  List stored_dependencies = Var_list(_x2c_match_value_10); {
      String identity = x2c_compiler_identity();  if(! String_truth(identity) || ! String_equal(compiler, identity) || ! String_equal(home_absolute_path(owner), canonical) || ! _hash_matches(c, canonical, String_var(hash))) return NULL;  return _interface_entry(c, canonical, hash, stored_parts, definitions, stored_dependencies);
    }

  }

}
break;
}
default: break;
    }
  }
return NULL;
}

int List_len(List);
int Var_is_integer(Var);
long Var_integer(Var);
static List _interface_entry(Compiler c, String canonical, String hash, List stored_parts, List definitions, List stored_dependencies){
  Array parts = Array_new(); {
    Var part;  List _x2c_macro_object_18 = stored_parts;  List _x2c_macro_cursor_18 = _x2c_macro_object_18;  Var _x2c_macro_cursor_output_17;  while(List_try_next(_x2c_macro_object_18, & _x2c_macro_cursor_18, & _x2c_macro_cursor_output_17)){
      part = _x2c_macro_cursor_output_17; {
        if(Var_is_row(part, 11, 7, 1)){
          Array_push(parts, String_var(_canonical_path(home_absolute_path(Var_string(part)))));  continue;
        }
        if(Var_equal(part, Symbol_var(35588017418)) || Var_equal(part, Symbol_var(1117938246))){
          Array_push(parts, part);  continue;
        }
        if(! Var_is_row(part, 9, 7, 4)) return NULL;  Scope_push(& process_cache_scope);  Map contributions = Map_new();
        Scope_pop();
        {
          Var row;
          List _x2c_macro_object_17 = Var_list(part);
          List _x2c_macro_cursor_17 = _x2c_macro_object_17;
          Var _x2c_macro_cursor_output_16;
          while(List_try_next(_x2c_macro_object_17, & _x2c_macro_cursor_17, & _x2c_macro_cursor_output_16)){
            row = _x2c_macro_cursor_output_16;
            {
              if(! Var_is_row(row, 9, 7, 4) || List_len(Var_list(row)) != 2) return NULL;
              List pair = Var_list(row);
              _require_retained(List_try_own(pair));
              Var contribution_key, contribution_value;
              List _x2c_destructure_1 = pair;
              contribution_key = List_getindex(_x2c_destructure_1, 0);
              contribution_value = List_getindex(_x2c_destructure_1, 1);
              Map_setindex(contributions, contribution_key, contribution_value);
            }

          }

        }
        Var contributions_var = Map_var(contributions);
        Array_push(parts, contributions_var);
      }

    }

  }
  Scope_push(& process_cache_scope);
  Map dependencies = Map_new();
  Scope_pop();
  {
    Var dependency;
    List _x2c_macro_object_19 = stored_dependencies;
    List _x2c_macro_cursor_19 = _x2c_macro_object_19;
    Var _x2c_macro_cursor_output_18;
    while(List_try_next(_x2c_macro_object_19, & _x2c_macro_cursor_19, & _x2c_macro_cursor_output_18)){
      dependency = _x2c_macro_cursor_output_18;
      {
        if(! Var_is_row(dependency, 9, 7, 4)) return NULL;

  {
    List _x2c_match_expr = Var_list(dependency);
    Var _x2c_match_values[2];
        MatchCaptureBuffer _x2c_match_capture = { .values = _x2c_match_values, .capacity = 2 };

    switch (0) {
      default: ;  static MatchCaptureSite _x2c_match_site_7;  if (x2c_match_site_try_capture(& _x2c_match_site_7, _x2c_match_expr, List_var(_157), &_x2c_match_capture)) {Var name = _x2c_match_values[0];  Var content_hash = _x2c_match_values[1]; {
          Var _x2c_match_value_11 = name; {
            String name = Var_string(_x2c_match_value_11); {
              String dependency_path = _canonical_path(home_absolute_path(name));  int unhashed = Var_is_integer(content_hash) && Var_integer(content_hash) == 1;  if(! unhashed && ! _hash_matches(c, dependency_path, content_hash)) return NULL;  _cache_dependency(dependencies, dependency_path, content_hash);  continue;
            }

          }

        }
        break;
      }

    }
  }
return NULL;
    }

  }

}
{
  Var definition;  List _x2c_macro_object_20 = definitions;  List _x2c_macro_cursor_20 = _x2c_macro_object_20;  Var _x2c_macro_cursor_output_19;  while(List_try_next(_x2c_macro_object_20, & _x2c_macro_cursor_20, & _x2c_macro_cursor_output_19)){
    definition = _x2c_macro_cursor_output_19;  if(! Var_is_row(definition, 11, 7, 1)) return NULL;
  }

}
List part_list = Array_list_free(parts);  List entry = cons(List_var(part_list), cons(String_var(hash), cons(List_var(definitions), cons(Map_var(dependencies), NULL))));  _require_retained(String_try_own(canonical));  _require_retained(List_try_own(entry));  Map_setindex(_process_cache(), String_var(canonical), List_var(entry));  return entry;
}

static List _interface_read(Compiler c, String canonical){
  if(c -> source_facts || ! String_truth(interface_mirror)) return NULL; {
    String path;  List _x2c_macro_object_21 = _interface_candidates(canonical);  List _x2c_macro_cursor_21 = _x2c_macro_object_21;  Var _x2c_macro_cursor_output_20;  while(List_try_next(_x2c_macro_object_21, & _x2c_macro_cursor_21, & _x2c_macro_cursor_output_20)){
      path = Var_string(_x2c_macro_cursor_output_20); {
        List entry = _interface_load(c, canonical, path);  if(List_truth(entry)) return entry;
      }

    }

  }
  return NULL;
}

int binding_identity_try_parts(List, int *, String *);
Var Map_setdefault(Map, Var, Var);
Var unsigned_var(unsigned);
List binding_identity_new(int, String);
int Var_equal(Var, Var);
int List_equal(List, List);
static List _renumber_bindings(List node, Map identities){
  String spelling = NULL;  if(binding_identity_try_parts(node, NULL, & spelling)){
    Var identity = Map_setdefault(identities, List_var(node), unsigned_var(Map_len(identities) + 1));  return binding_identity_new(Var_int(Var_convert(identity, 3453797)), spelling);
  }
  Var child;  List _x2c_macro_original_0 = node;  Array _x2c_macro_rewritten_0 = NULL;  for(List _x2c_macro_cursor_22 = _x2c_macro_original_0;  List_truth(_x2c_macro_cursor_22);  _x2c_macro_cursor_22 = List_cdr(_x2c_macro_cursor_22)){
    Var _x2c_macro_item_22 = List_car(_x2c_macro_cursor_22), _x2c_macro_value_0 = _x2c_macro_item_22;  if(Var_is_row(_x2c_macro_item_22, 9, 7, 4)){
      child = _x2c_macro_item_22;  _x2c_macro_value_0 = List_var(_renumber_bindings(Var_list(child), identities));
    }
    if(!(void *) _x2c_macro_rewritten_0 && ! Var_equal(_x2c_macro_value_0, _x2c_macro_item_22)){
      _x2c_macro_rewritten_0 = Array_new();  for(List _x2c_macro_prefix_0 = _x2c_macro_original_0;  ! List_equal(_x2c_macro_prefix_0, _x2c_macro_cursor_22);  _x2c_macro_prefix_0 = List_cdr(_x2c_macro_prefix_0)) Array_push(_x2c_macro_rewritten_0, List_car(_x2c_macro_prefix_0));
    }
    if((void *) _x2c_macro_rewritten_0) Array_push(_x2c_macro_rewritten_0, _x2c_macro_value_0);
  }
  return(void *) _x2c_macro_rewritten_0 ? Array_list_free(_x2c_macro_rewritten_0) : _x2c_macro_original_0;
}

Buffer Buffer_write_char(Buffer, char);
int Var_is_atom(Var);
String Var_str(Var);
int Atom_bare_spelling(String);
Buffer Buffer_write(Buffer, const char *);
String Var_repr(Var);
Buffer Buffer_printf(Buffer, const char *, ...);
int Var_is_floating(Var);
double Var_floating(Var);
static int _write_datum(Buffer out, Var value){
  if(Var_is_row(value, 9, 7, 4)){
    List list = Var_list(value);  Buffer_write_char(out, '(');  for(List p = list;  List_truth(p);  p = List_cdr(p)){
      if(! List_equal(p, list)) Buffer_write_char(out, ' ');  if(! _write_datum(out, List_car(p))) return 0;
    }
    Buffer_write_char(out, ')');
  }
  else if(Var_is_atom(value)){
    String text = Var_str(value);  if(Atom_bare_spelling(text)) Buffer_write(out, text);  else if(Var_is(value, 1328354264)) Buffer_write(out, Var_repr(value));  else return 0;
  }
  else if(Var_is_row(value, 11, 7, 1)) Buffer_write(out, Var_repr(value));  else if(Var_is_integer(value)) Buffer_printf(out, "%ld", Var_integer(value));  else if(Var_is_floating(value)) Buffer_printf(out, "%.17g", Var_floating(value));  else return 0;  return 1;
}

static int _write_interface_entry(Buffer out, String canonical, List entry){
  List _x2c_destructure_2 = entry;  List cached_parts = Var_list(List_getindex(_x2c_destructure_2, 0));  Var hash = List_getindex(_x2c_destructure_2, 1);  List definitions = Var_list(List_getindex(_x2c_destructure_2, 2));  Map cached_dependencies = Var_map(List_getindex(_x2c_destructure_2, 3));  Array parts = Array_new();  Map identities = Map_new();
  {
    Var part;
    List _x2c_macro_object_23 = cached_parts;
    List _x2c_macro_cursor_24 = _x2c_macro_object_23;
    Var _x2c_macro_cursor_output_23;
    while(List_try_next(_x2c_macro_object_23, & _x2c_macro_cursor_24, & _x2c_macro_cursor_output_23)){
      part = _x2c_macro_cursor_output_23;
      {
        if(Var_is(part, 26720)){
          Array rows = Array_new();
          Map contributions = Var_map(part);
          {
            Var row_key, row_value;
            Map _x2c_macro_object_22 = contributions;
            unsigned _x2c_macro_cursor_23 = 0;
            Var _x2c_macro_cursor_output_21;
            Var _x2c_macro_cursor_output_22;
            while(Map_try_next(_x2c_macro_object_22, & _x2c_macro_cursor_23, & _x2c_macro_cursor_output_21, & _x2c_macro_cursor_output_22)){
              row_key = _x2c_macro_cursor_output_21;
              row_value = _x2c_macro_cursor_output_22;
              Array_push(rows, List_var(cons(row_key, cons(row_value, NULL))));
            }

          }
          Array_sort(rows);
          Var rows_var = List_var(_renumber_bindings(Array_list_free(rows), identities));
          Array_push(parts, rows_var);
          continue;
        }
        if(Var_is(part, 1328354264)) Array_push(parts, part);
        else Array_push(parts, String_var(home_portable_path(Var_string(part))));
      }

    }

  }
  Array dependencies = Array_new();
  {
    Var path, content_hash;
    Map _x2c_macro_object_24 = cached_dependencies;
    unsigned _x2c_macro_cursor_25 = 0;
    Var _x2c_macro_cursor_output_24;
    Var _x2c_macro_cursor_output_25;
    while(Map_try_next(_x2c_macro_object_24, & _x2c_macro_cursor_25, & _x2c_macro_cursor_output_24, & _x2c_macro_cursor_output_25)){
      path = _x2c_macro_cursor_output_24;
      content_hash = _x2c_macro_cursor_output_25;
      Array_push(dependencies, List_var(cons(String_var(home_portable_path(Var_string(path))), cons(content_hash, NULL))));
    }

  }
  Array_sort(dependencies);
  List dependency_list = Array_list_free(dependencies);
  List part_list = Array_list_free(parts);
  List record = cons(_103, cons(_104, cons(String_var(x2c_compiler_identity()), cons(String_var(home_portable_path(canonical)), cons(hash, cons(List_var(part_list), cons(List_var(definitions), cons(List_var(dependency_list), NULL))))))));
  if(! _write_datum(out, List_var(record))) return 0;
  Buffer_write_char(out, '\n');
  return 1;
}

Buffer Buffer_new(size_t);

String Buffer_str(Buffer);

String interface_text(Compiler compiler){
  if(! _init_guard_) _file_init_();
  String canonical = _canonical_path(compiler -> filename);
  Var cached = Map_getindex(_process_cache(), String_var(canonical));
  if(Var_is_void(cached)) return NULL;
  Buffer out = Buffer_new(0);
  {
  _x2c_defer_env_3 _x2c_defer_env_7 = {._x2c_defer_capture_6 =(const void *) & out};

  X2CCleanup _x2c_defer_record_3 = {
    .fn = _x2c_defer_cleanup_3,
    .env = & _x2c_defer_env_7
  };
  x2c_cleanup_push(&_x2c_defer_record_3);
  {
    if(! _write_interface_entry(out, canonical, Var_list(cached))) Compiler_report_error(compiler, 354920, _165, NULL, NULL);
    {
      String _x2c_return_value_7 = Buffer_str(out);
      {
        x2c_cleanup_leave(& _x2c_defer_record_3);
        return _x2c_return_value_7;
      }

    }

  }
  x2c_cleanup_leave(& _x2c_defer_record_3);

}
}

void Compiler_close_child(Compiler, Compiler);

static void _x2c_defer_cleanup_0(void * _x2c_defer_opaque_0){
  _x2c_defer_env_0 * _x2c_defer_data_0 =(_x2c_defer_env_0 *) _x2c_defer_opaque_0;
  Compiler_close_child((*(Compiler *) _x2c_defer_data_0->_x2c_defer_capture_0), (*(Compiler *) _x2c_defer_data_0->_x2c_defer_capture_1));
}

static void _x2c_defer_cleanup_1(void * _x2c_defer_opaque_1){
  _x2c_defer_env_1 * _x2c_defer_data_1 =(_x2c_defer_env_1 *) _x2c_defer_opaque_1;
  *(*(List * *) _x2c_defer_data_1->_x2c_defer_capture_2) =(*(List *) _x2c_defer_data_1->_x2c_defer_capture_3);
}

static void _x2c_defer_cleanup_2(void * _x2c_defer_opaque_2){
  _x2c_defer_env_2 * _x2c_defer_data_2 =(_x2c_defer_env_2 *) _x2c_defer_opaque_2;
  Compiler_close_child((*(Compiler *) _x2c_defer_data_2->_x2c_defer_capture_4), (*(Compiler *) _x2c_defer_data_2->_x2c_defer_capture_5));
}

void Buffer_cleanup(Buffer);

static void _x2c_defer_cleanup_3(void * _x2c_defer_opaque_3){
  _x2c_defer_env_3 * _x2c_defer_data_3 =(_x2c_defer_env_3 *) _x2c_defer_opaque_3;
  Buffer_cleanup((*(Buffer *) _x2c_defer_data_3->_x2c_defer_capture_6));
}

#undef _x2c_initializer_choice_AB8728A9_0_expanded
#undef _x2c_initializer_choice_AB8728A9_0
#undef _x2c_initializer_choice_AB8728A9_1_expanded
#undef _x2c_initializer_choice_AB8728A9_1
#undef _x2c_initializer_choice_AB8728A9_2_expanded
#undef _x2c_initializer_choice_AB8728A9_2
#undef _x2c_initializer_choice_AB8728A9_3_expanded
#undef _x2c_initializer_choice_AB8728A9_3
#undef _x2c_initializer_choice_AB8728A9_4_expanded
#undef _x2c_initializer_choice_AB8728A9_4
#undef _x2c_initializer_choice_AB8728A9_5_expanded
#undef _x2c_initializer_choice_AB8728A9_5
