/* auto-generated by x2c.  Do not edit! */

#define __GUARD_0x009943D3__
#include "x2c.h"

#include "rewrite.h"
static List _69, _68, _67, _65, _64, _62, _61, _57, _56, _55, _53, _52, _50, _49, _44, _41, _37, _36, _35, _33, _32, _30, _29, _23, _19, _14, _13, _9, _8, _5, _4, _3;

static String _59, _47, _42, _27, _17;

static Var _70, _66, _63, _60, _58, _54, _51, _48, _46, _45, _43, _40, _39, _38, _34, _31, _28, _26, _25, _24, _22, _21, _20, _18, _16, _15, _12, _11, _10, _7, _6, _2, _1, _0;

static int _init_guard_ = 0;

__attribute__((constructor, noinline, cold)) static void _file_init_(void);

__attribute__((constructor, noinline, cold)) static void _file_init_(void){
  x2c_initialize_protocols();
  if(_init_guard_) return;
  _init_guard_ = 1;
  _0 = Symbol_var(62436);
  _1 = Symbol_var(1286024736);
  _2 = Symbol_var(1286058084);
  _3 = cons(_2, NULL);
  _4 = cons(_1, _3);
  _5 = cons(_0, _4);
  _6 = List_var(_5);
  _7 = Symbol_var(1992385866);
  _8 = cons(_7, NULL);
  _9 = cons(_6, _8);
  _10 = Symbol_var(377892);
  _11 = Symbol_var(54);
  _12 = Symbol_var(213092);
  _13 = cons(_12, NULL);
  _14 = cons(_11, _13);
  _15 = List_var(_14);
  _16 = Symbol_var(26416091224);
  _17 = String_new("String");
  _18 = String_var(_17);
  _19 = cons(_18, NULL);
  _20 = List_var(_19);
  _21 = Symbol_var(199448);
  _22 = Symbol_var(917238582723620);
  _23 = cons(_22, NULL);
  _24 = List_var(_23);
  _25 = Symbol_var(19147688);
  _26 = Atom_intern(String_new("binding-name"));
  _27 = String_new("String_new");
  _28 = String_var(_27);
  _29 = cons(_28, NULL);
  _30 = cons(_26, _29);
  _31 = List_var(_30);
  _32 = cons(_31, NULL);
  _33 = cons(_25, _32);
  _34 = List_var(_33);
  _35 = cons(_34, NULL);
  _36 = cons(_24, _35);
  _37 = cons(_10, _36);
  _38 = List_var(_37);
  _39 = Symbol_var(102886);
  _40 = Symbol_var(29272);
  _41 = cons(_40, NULL);
  _42 = String_new("List");
  _43 = String_var(_42);
  _44 = cons(_43, NULL);
  _45 = List_var(_44);
  _46 = Symbol_var(228262);
  _47 = String_new("String_join");
  _48 = String_var(_47);
  _49 = cons(_48, NULL);
  _50 = cons(_26, _49);
  _51 = List_var(_50);
  _52 = cons(_51, NULL);
  _53 = cons(_25, _52);
  _54 = List_var(_53);
  _55 = cons(_54, NULL);
  _56 = cons(_24, _55);
  _57 = cons(_10, _56);
  _58 = List_var(_57);
  _59 = String_new("NULL");
  _60 = String_var(_59);
  _61 = cons(_60, NULL);
  _62 = cons(_26, _61);
  _63 = List_var(_62);
  _64 = cons(_63, NULL);
  _65 = cons(_25, _64);
  _66 = List_var(_65);
  _67 = cons(_66, NULL);
  _68 = cons(_24, _67);
  _69 = cons(_10, _68);
  _70 = List_var(_69);
}

Code interpolation(Code code){
  if(! _init_guard_) _file_init_();
  {
    List _x2c_match_expr = code; List _x2c_match_cursor, _x2c_match_cursor1;
    switch(_x2c_match_expr ? _x2c_match_expr->car.u64 : 0){
        case 9224497936761996324ULL: ;
       _x2c_match_cursor = _x2c_match_expr; if (_x2c_match_cursor && _x2c_match_cursor->car.u64 == 9224497936761996324ULL && (_x2c_match_cursor = _x2c_match_cursor->cdr, 1) && _x2c_match_cursor && (_x2c_match_cursor = _x2c_match_cursor->cdr, 1) && _x2c_match_cursor && Var_is(_x2c_match_cursor->car, 806120) && (_x2c_match_cursor1 = Var_list(_x2c_match_cursor->car), 1) && _x2c_match_cursor1 && _x2c_match_cursor1->car.u64 == 9224499253666477350ULL && (_x2c_match_cursor1 = _x2c_match_cursor1->cdr, 1)) { List segments = _x2c_match_cursor1; if ((_x2c_match_cursor = _x2c_match_cursor->cdr, 1) && !_x2c_match_cursor) {{
        Array parts = Array_new();
        {
          List segment;
          List _x2c_macro_object_0 = segments;
          List _x2c_macro_cursor_0 = _x2c_macro_object_0;
          Var _x2c_macro_cursor_output_0;
          while(List_try_next(_x2c_macro_object_0, &(_x2c_macro_cursor_0), &(_x2c_macro_cursor_output_0))){
            segment = Var_list(_x2c_macro_cursor_output_0);
            {
              List _x2c_match_expr = segment; List _x2c_match_cursor; Var _x2c_match_values[1]; MatchCaptureBuffer _x2c_match_capture = { .values = _x2c_match_values, .capacity = 1 };
              switch(0){
                  default: ;
                 static MatchCaptureSite _x2c_match_site_0; if (x2c_match_site_try_capture(&_x2c_match_site_0, _x2c_match_expr, List_var(_9), &_x2c_match_capture)) { Var value = _x2c_match_values[0];  Array_push(parts, value);  break; } _x2c_match_cursor = _x2c_match_expr; if (_x2c_match_cursor && _x2c_match_cursor->car.u64 == 9224497938047668334ULL && (_x2c_match_cursor = _x2c_match_cursor->cdr, 1) && _x2c_match_cursor) { Var text = _x2c_match_cursor->car; if ((_x2c_match_cursor = _x2c_match_cursor->cdr, 1) && !_x2c_match_cursor) {{
                  String raw = Var_string(text);  Code literal = cons(_10, cons(_15, cons(List_var(cons(_16, cons(_15, cons(String_var(String_repr(raw)), NULL)))), NULL)));  Array_push(parts, List_var(cons(_10, cons(_20, cons(List_var(cons(_21, cons(_38, cons(List_var(cons(_39, cons(Macro_inserted(List_var(literal), 1, 1), NULL))), NULL)))), NULL)))));
                }
                 break; } } Array_push(parts, List_var(cons(_10, cons(_20, cons(List_var(segment), NULL)))));  break;
              }

            }

          }

        }
        Var chain = List_var(_41);  while(Array_len(parts)) chain = List_var(cons(_10, cons(_45, cons(List_var(({
          Var _x2c_literal_part_0 = Array_take_last(parts);  cons(_46, cons(_x2c_literal_part_0, cons(chain, NULL)));
        }
        )), NULL))));  return cons(_10, cons(_20, cons(List_var(cons(_21, cons(_58, cons(List_var(cons(_39, cons(_70, cons(Macro_inserted(chain, 1, 1), NULL)))), NULL)))), NULL)));
      }
       break; } } default: break;
    }

  }
  return code;
}

