/* auto-generated by x2c.  Do not edit! */

#pragma once

#ifndef __GUARD_0xFC1683EE__
#define __GUARD_0xFC1683EE__

#include "x2c.h"
#include "common.h"
List _field_copies(List to, List from, List fields);

List _field_sets(List to, List value, List fields);


#endif /* __GUARD_0xFC1683EE__ */
