/* auto-generated by x2c.  Do not edit! */

#pragma once

#ifndef __GUARD_0x5DA47678__
#define __GUARD_0x5DA47678__

#include "x2c.h"
#include "common.h"
#include "list-selectors.h"
#include "meta.h"
#include "native-scalar-types.h"
#include "rewrite.h"
#include "system-macros.h"
#include "var-tags.h"
#include "varops.h"
#include "component-access.h"
#include "component-try.h"
#include "fields.h"
#include "grammar.h"
#include "operator-ledger.h"
List x2c_expr_field(List receiver, String name);

List x2c_expr_cast(List type, List expression);

List x2c_decl_make(List type, Var name, List initializer);

List x2c_param_make(List type, Var name);

List x2c_type_members(List type);

Code register_rewrite(Code function, Code pattern, List holes);

Code register_marked_rewrite(Code function, Code mark, Code pattern, List holes);

List _dedent_expand(List node);

List _macros_location(void);

List _tag_decode_group(List rows, Map counts, int top);

List _tag_decode_groups(void);

List _tag_id_checks(void);

Code collection_store(Code code);

Code collection_update(Code code);

Code collection_prefix(Code code);

Code collection_postfix(Code code);

List try_catch_cases(List selected, List arms);

Code try_lowering(Code node);

Map linked_meta_targets(void);

Map linked_meta_hashes(void);


#endif /* __GUARD_0x5DA47678__ */
