/* auto-generated by x2c.  Do not edit! */

#pragma once

#ifndef __GUARD_0x28FCBFDC__
#define __GUARD_0x28FCBFDC__

#include "x2c.h"
#include "compiler.h"
void Compiler_install_builtin_macros(Compiler compiler);

int Compiler_macro_form_is_definition(Compiler compiler);

int Compiler_local_macro_form_is_definition(Compiler c);

int Compiler_keyword_form_is_definition(Compiler c);

void Compiler_skip_macro_invocation(Compiler c);

int Compiler_macro_invocation_needs_shallow_expansion(Compiler c);

int Compiler_macro_starts_target_at(Compiler c, AstPos position);

Lisp Compiler_open_macro_library(Compiler compiler);

void Compiler_publish_macro_library(Compiler compiler, Lisp shared);

int Compiler_shared_definition(Compiler compiler, String key);

void macro_library_defer(void);

int macro_library_pending(void);

List Compiler_parse_macro_lisp_top_level(Compiler compiler);

List Compiler_parse_source_lisp(Compiler compiler);

void Compiler_evaluate_declaration_effect(Compiler compiler, String form, Token invocation);

void Compiler_install_meta_function(Compiler c, List fn, Token marker);

void Compiler_parse_macro_lisp_shallow(Compiler compiler);

List Compiler_lift_macro_lisp_expression(Compiler compiler, Var value, Token invocation);

List Compiler_parse_macro_lisp_expression(Compiler compiler);

Var Compiler_evaluate_declaration_recipe(Compiler compiler, Atom callback, List arguments);

Var Compiler_evaluate_macro_slot(Compiler compiler, Var value);

List Compiler_evaluate_macro_rows(Compiler compiler, Var value);

List Compiler_macro_introduced_name(Compiler compiler, String spelling);

List Compiler_peek_macro_hole(Compiler compiler);

int Compiler_macro_lisp_starts_declaration(Compiler compiler);

List Compiler_try_parse_macro_slot(Compiler c, Symbol role);

List Compiler_parse_macro_definition(Compiler c);

List Compiler_publish_macro_definition_node(Compiler compiler, List node);

void Compiler_parse_keyword_definition(Compiler c);

int Compiler_macro_targets_unit(Compiler c);

int Compiler_skip_named_type_declaration(Compiler c);

Token Compiler_macro_invocation_site(Compiler compiler, Var site);

List Compiler_expand_macro_invocation_node(Compiler c, Var stored, List arguments, Token invocation, AstPos position);

List Compiler_try_parse_macro_expression(Compiler c);

List Compiler_try_parse_macro_target_at(Compiler c, AstPos position);


#endif /* __GUARD_0x28FCBFDC__ */
