/* auto-generated by x2c.  Do not edit! */

#pragma once

#ifndef __GUARD_0x1E27A9AE__
#define __GUARD_0x1E27A9AE__

#include "x2c.h"
#include "build.h"
#include "bootstrap.h"
#include "project.h"
#include "toolchain.h"
int main(int argc,  char * * argv);


#endif /* __GUARD_0x1E27A9AE__ */
