/* auto-generated by x2c.  Do not edit! */

#define __GUARD_0x1E27A9AE__
#include "x2c.h"

#include "build.h"
#include "project.h"
#include "frontend.h"
#include "meta-project.h"
#include "editor.h"
#include "install.h"
#include "script.h"
#include "toolchain.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <limits.h>
#include <signal.h>
#include <unistd.h>
#include "report.h"
#include "collect.h"
#include "cli.h"
#include "compiler.h"
#include "deps.h"
#include "logger.h"
#include "utils.h"
#include "emit.h"
#include "generate.h"
#include "format.h"
#include "protocol.h"
static List _9, _8, _7, _4, _3;

static String _62, _61, _60, _59, _57, _55, _53, _51, _49, _47, _45, _43, _41, _39, _37, _36, _35, _34, _33, _32, _31, _30, _29, _28, _27, _26, _25, _24, _23, _22, _21, _20, _19, _18, _17, _16, _15, _14, _13, _12, _11, _10;

static Var _58, _56, _54, _52, _50, _48, _46, _44, _42, _40, _38, _6, _5, _2, _1, _0;

static int _init_guard_ = 0;

__attribute__((constructor, noinline, cold)) static void _file_init_(void);

static void _translate_unit(Frontend frontend, String filename, String output_dir);

_Noreturn static void _fail(Compiler c);

static void _report_diagnostics(Compiler c);

static List _transform_ast(Compiler c, List ast);

static int _inspect_collected(ParsedUnit * unit, Symbol dump);

static int _inspect_parsed(ParsedUnit * unit, String filename, Symbol dump);

static int _inspect_transformed(Compiler c, List ast, Symbol dump);

static void _print_conformance(Compiler c, String filename, Map globals);

static void _print_ast(List ast);

static String _node_repr(List node);

typedef struct Translation{
  CliRequest request;
  Frontend frontend;
  Map unit_dirs;
  Build build;
  int total;
}
Translation;

static int _run_translation(CliRequest request, Map unit_dirs, Build build);

static void Translation_preflight(Translation * t);

static void _check_out_dir(String out_dir);

_Noreturn static void _stem_collision(String stem, String first, String other, String out_dir);

static void _print_command(CliRequest request);

static void _preprocessor_errors(String text);

static void Translation_translate_serial(Translation * t);

static void Translation_translate(Translation * t, String input);

static String Translation_output_dir(Translation * t, String input);

static void Translation_report(Translation * t, unsigned long started_at);

typedef struct Workers{
  Translation * t;
  Array slices;
  long * pids;
  int * carried;
  File * captures;
  Block * output;
  int live, started, shown, failed, done;
}
Workers;

static Workers _workers;

static int Translation_translate_parallel(Translation * t);

static void Translation_preload_modules(Translation * t);

static Map Translation_package_names(Translation * t, List roots);

static List _imported_packages(String path);

static Array _slices(List inputs, int total, int count);

static int Translation_run_workers(Translation * t, Array slices);

static void Workers_start(Workers * w);

static void Translation_work(Translation * t, List slice);

static void Workers_reap(Workers * w);

static void Workers_show(Workers * w);

static int Workers_carries(Workers * w, int index);

static void _forward_stop(int number);

static void _forward_stop_signal(int number, struct sigaction * previous);

static sigset_t _block_stop_signals(void);

static int _run_build(CliRequest request);

static int _build_inputs(CliRequest request, Array commands);

static int _build_manifest(CliRequest request, Array commands);

static int _build_target(CliRequest request, Array commands);

static int _translate_target(CliRequest request, Build b);

static int _add_commands(CliRequest request, Build b, Context target, Array commands);

static int _translate_units(CliRequest request, Build b, List units);

static List _stale_inputs(Build b, List units, Map stale);

static void _register_units(CliRequest request, Build b, List units, Map stale);

static int _run_env(CliRequest request);

static List _env_rows(CliRequest request);

static void _run_external(int argc, char * * argv);

static String _external_path(const char * name);

static int _external_name(const char * name);

static void _exec(String path, char * * args);

static int _run_compiler(CliRequest request);

static void _configure_logging(int debugging);

typedef struct _x2c_defer_env_0{
  const void * _x2c_defer_capture_0;
}
_x2c_defer_env_0;

static void _x2c_defer_cleanup_0(void * _x2c_defer_opaque_0);

typedef struct _x2c_defer_env_1{
  const void * _x2c_defer_capture_1;
}
_x2c_defer_env_1;

static void _x2c_defer_cleanup_1(void * _x2c_defer_opaque_1);

typedef struct _x2c_defer_env_2{
  const void * _x2c_defer_capture_2;
}
_x2c_defer_env_2;

static void _x2c_defer_cleanup_2(void * _x2c_defer_opaque_2);

static void _x2c_defer_cleanup_3(void * _x2c_defer_opaque_3);

typedef struct _x2c_defer_env_3{
  const void * _x2c_defer_capture_3;
}
_x2c_defer_env_3;

static void _x2c_defer_cleanup_4(void * _x2c_defer_opaque_4);

#include "exception.h"




__attribute__((constructor, noinline, cold)) static void _file_init_(void){
  x2c_initialize_protocols();
  if(_init_guard_) return;
  _init_guard_ = 1;
  _0 = Symbol_var(895740748108);
  _1 = Symbol_var(920394);
  _2 = Symbol_var(61737802);
  _3 = cons(_2, NULL);
  _4 = cons(_1, _3);
  _5 = List_var(_4);
  _6 = Symbol_var(54);
  _7 = cons(_6, NULL);
  _8 = cons(_5, _7);
  _9 = cons(_0, _8);
  _10 = String_new("(macrodef <macro ");
  _11 = String_new(">)");
  _12 = String_new(".");
  _13 = String_new("translation input is not an .x file: ");
  _14 = String_new("output directory does not exist: ");
  _15 = String_new("output is not a directory: ");
  _16 = String_new("output directory is not writable: ");
  _17 = String_new("/");
  _18 = String_new(".c");
  _19 = String_new(".h");
  _20 = String_new("file");
  _21 = String_new("files");
  _22 = String_new("Translated ");
  _23 = String_new(" x2c ");
  _24 = String_new(" to ");
  _25 = String_new(" in ");
  _26 = String_new("/builds/");
  _27 = String_new(".module");
  _28 = String_new(".d");
  _29 = String_new("{");
  _30 = String_new("}");
  _31 = String_new("import");
  _32 = String_new("could not start a translation worker");
  _33 = String_new("/run");
  _34 = String_new("unknown env name \'");
  _35 = String_new("\'");
  _36 = String_new(":");
  _37 = String_new("home");
  _38 = String_var(_37);
  _39 = String_new("executable");
  _40 = String_var(_39);
  _41 = String_new("libexec");
  _42 = String_var(_41);
  _43 = String_new("identity");
  _44 = String_var(_43);
  _45 = String_new("include_dir");
  _46 = String_var(_45);
  _47 = String_new("runtime_lib");
  _48 = String_var(_47);
  _49 = String_new("prelude");
  _50 = String_var(_49);
  _51 = String_new("package_dirs");
  _52 = String_var(_51);
  _53 = String_new("cc");
  _54 = String_var(_53);
  _55 = String_new("ar");
  _56 = String_var(_55);
  _57 = String_new("cache_dir");
  _58 = String_var(_57);
  _59 = String_new("/x2c-");
  _60 = String_new("cannot run external command \'");
  _61 = String_new("\': ");
  _62 = String_new("cannot open diagnostics file \'");
}

void Compiler_dump_tokens(Compiler);

List Compiler_diagnostics(Compiler);

static void _translate_unit(Frontend frontend, String filename, String output_dir){
  CliRequest request = frontend -> request;
  Symbol dump = request -> dump;
  ParsedUnit unit;
  int started = Frontend_start(frontend, filename, &(unit));
  {
    _x2c_defer_env_0 _x2c_macro_environment_0 ={
      0
    }
    ;
    _x2c_macro_environment_0._x2c_defer_capture_0 =(const void *) & unit;
    X2CCleanup _x2c_defer_record_0 ={
      .fn = _x2c_defer_cleanup_0, .env = & _x2c_macro_environment_0
    }
    ;
    x2c_cleanup_push(& _x2c_defer_record_0);
    {
      Compiler c = unit.compiler;
      if(! started) _fail(c);
      Compiler_own_diagnostics(c);
      if(dump == 1374366630){
        Compiler_dump_tokens(c);
        {
          x2c_cleanup_leave(& _x2c_defer_record_0);
          return;
        }

      }
      int collected = ParsedUnit_collect(&(unit), frontend);
      _report_diagnostics(c);
      if(! collected) exit(1);
      if(_inspect_collected(&(unit), dump)){
        x2c_cleanup_leave(& _x2c_defer_record_0);
        return;
      }
      if(! ParsedUnit_parse(&(unit))) _fail(c);
      c -> recovery_depth = 0;
      if(_inspect_parsed(&(unit), filename, dump)){
        x2c_cleanup_leave(& _x2c_defer_record_0);
        return;
      }
      List ast = _transform_ast(c, Compiler_generate_protocol_adapters(c, unit.ast));
      if(_inspect_transformed(c, ast, dump)){
        x2c_cleanup_leave(& _x2c_defer_record_0);
        return;
      }
      generate_code(c, ast, output_dir);
      if(! translation_depfile_write(request, c, filename, output_dir)) exit(1);
      if(request -> fatal_warnings && List_truth(Compiler_diagnostics(c))) exit(1);
    }
    x2c_cleanup_leave(& _x2c_defer_record_0);
  }

}

_Noreturn static void _fail(Compiler c){
  _report_diagnostics(c);
  exit(1);
}

void Compiler_print_diagnostic(Compiler, List);

static void _report_diagnostics(Compiler c){
  if(c -> diagnostics -> printer) return;
  List entries = Compiler_diagnostics(c);
  if(List_truth(entries)) report_suspend();
  {
    Var entry;
    List _x2c_macro_object_0 = entries;
    List _x2c_macro_cursor_0 = _x2c_macro_object_0;
    Var _x2c_macro_cursor_output_0;
    while(List_try_next(_x2c_macro_object_0, &(_x2c_macro_cursor_0), &(_x2c_macro_cursor_output_0))){
      entry = _x2c_macro_cursor_output_0;
      Compiler_print_diagnostic(c, Var_list(entry));
    }

  }

}

List Compiler_transform(Compiler, List);

int Compiler_error_count(Compiler);

static List _transform_ast(Compiler c, List ast){
  ast = Compiler_transform(c, ast);
  if(Compiler_error_count(c)) _fail(c);
  return ast;
}

void Compiler_dump_symbol_table(Compiler, Map);

static int _inspect_collected(ParsedUnit * unit, Symbol dump){
  Compiler cpp =(* unit).preprocessor;
  String text =(* unit).preprocessor_output;
  switch(dump){
    case 320883072032 : if(String_truth(text)) printf("%s", text);
    break;
    case 247458062609318 : if(cpp) Compiler_dump_tokens(cpp);
    break;
    case 10268258311770 : if(cpp) Compiler_dump_symbol_table(cpp, (* unit).globals);
    break;
    default: return 0;
  }
  return 1;
}

void Compiler_dump_cache(Compiler);

Map Sym_current_symbols(Sym);

static int _inspect_parsed(ParsedUnit * unit, String filename, Symbol dump){
  Compiler c =(* unit).compiler;
  switch(dump){
    case 328584264751626 : Compiler_dump_cache(c);
    break;
    case 42507336486 : Compiler_dump_symbol_table(c, Sym_current_symbols(c -> sym));
    break;
    case 320883068136 : _print_ast((* unit).ast);
    break;
    case 7478869146 : _print_conformance(c, filename, (* unit).globals);
    break;
    default: return 0;
  }
  return 1;
}

static int _inspect_transformed(Compiler c, List ast, Symbol dump){
  switch(dump){
    case 1447057375073126 : _print_ast(ast);
    break;
    case 10268258347430 : Compiler_dump_definitions(c, ast);
    break;
    case 10268258302218 : puts(Compiler_code_pretty_string(c, Compiler_emit(c, ast, NULL), NULL));
    break;
    default: return 0;
  }
  return 1;
}

static void _print_conformance(Compiler c, String filename, Map globals){
  printf("(unit %s)\n", filename);
  Compiler_dump_conformance(c, globals);
}

static void _print_ast(List ast){
  {
    List node;
    List _x2c_macro_object_1 = ast;
    List _x2c_macro_cursor_1 = _x2c_macro_object_1;
    Var _x2c_macro_cursor_output_1;
    while(List_try_next(_x2c_macro_object_1, &(_x2c_macro_cursor_1), &(_x2c_macro_cursor_output_1))){
      node = Var_list(_x2c_macro_cursor_output_1);
      printf("\n%s\n", _node_repr(node));
    }

  }

}

static String _node_repr(List node){

  {
    List _x2c_match_expr = node;
    Var _x2c_match_values[1];
  MatchCaptureBuffer _x2c_match_capture = { .values = _x2c_match_values, .capacity = 1 };

    switch (Var_symbol(car(_x2c_match_expr))) {
      case 895740748108: ;
  static MatchCaptureSite _x2c_match_site_0;
  if (x2c_match_site_try_capture(& _x2c_match_site_0, _x2c_match_expr, List_var(_9), &_x2c_match_capture)) {Var name = _x2c_match_values[0];  return String_join(NULL, cons(String_var(_10), cons(String_var(Var_str(name)), cons(String_var(_11), NULL))));  break;
}
default: break;
    }
  }
return List_repr(node);
}

static int _run_translation(CliRequest request, Map unit_dirs, Build build){
  unsigned long started_at = report_now_us();  if(! String_truth(request -> out_dir)) request -> out_dir = _12;  Translation t ={
    .request = request, .unit_dirs = unit_dirs, .build = build, .total = List_len(request -> inputs)
  }
  ;  Translation_preflight(&(t));  if(request -> verbose || request -> dry_run) _print_command(request);  if(request -> dry_run) return 0;  t.frontend = Frontend_new(request);  t.frontend -> preprocessor_errors = _preprocessor_errors;  if(! Frontend_preload_macro_libraries(t.frontend)) return 1;  Frontend_prepare_meta(t.frontend, request -> inputs);  if(request -> jobs > 1 && t.total > 1 && ! CliRequest_inspects(request)){
    if(Translation_translate_parallel(&(t))) return 1;
  }
  else Translation_translate_serial(&(t));  if(! build && ! CliRequest_inspects(request)) Translation_report(&(t), started_at);  return 0;
}

String Path_stem(Path);
static void Translation_preflight(Translation * t){
  CliRequest request =(* t).request;  if(! CliRequest_inspects(request)) _check_out_dir(request -> out_dir);  int shared = ! CliRequest_inspects(request) && ! Map_truth((* t).unit_dirs);  Map stems = Map_new(); {
    String input;  List _x2c_macro_object_2 = request -> inputs;  List _x2c_macro_cursor_2 = _x2c_macro_object_2;  Var _x2c_macro_cursor_output_2;  while(List_try_next(_x2c_macro_object_2, &(_x2c_macro_cursor_2), &(_x2c_macro_cursor_output_2))){
      input = Var_string(_x2c_macro_cursor_output_2); {
        build_check_input(input);  if(! is_source_file(input)) driver_error(String_join(NULL, cons(String_var(_13), cons(String_var(input), NULL))));
        String stem = Path_stem(input);
        if(shared && Map_contains(stems, String_var(stem))) _stem_collision(stem, Var_string(Map_getindex(stems, String_var(stem))), input, request -> out_dir);
        Map_setindex(stems, String_var(stem), String_var(input));
      }

    }

  }

}

int Path_exists(Path);

int Path_is_dir(Path);

static void _check_out_dir(String out_dir){
  if(! Path_exists(out_dir)) driver_error(String_join(NULL, cons(String_var(_14), cons(String_var(out_dir), NULL))));
  if(! Path_is_dir(out_dir)) driver_error(String_join(NULL, cons(String_var(_15), cons(String_var(out_dir), NULL))));
  if(access(out_dir, W_OK | X_OK)) driver_error(String_join(NULL, cons(String_var(_16), cons(String_var(out_dir), NULL))));
}

_Noreturn static void _stem_collision(String stem, String first, String other, String out_dir){
  fprintf(stderr, "x2c: error: inputs produce the same output stem '%s'\n" "  first input: %s\n  other input: %s\n  output: %s/%s.c\n", stem, first, other, out_dir, stem);
  exit(2);
}

static void _print_command(CliRequest request){
  fprintf(stderr, "x2c: translate");
  fprintf(stderr, " --out-dir %s", request -> out_dir);
  {
    String input;
    List _x2c_macro_object_3 = request -> inputs;
    List _x2c_macro_cursor_3 = _x2c_macro_object_3;
    Var _x2c_macro_cursor_output_3;
    while(List_try_next(_x2c_macro_object_3, &(_x2c_macro_cursor_3), &(_x2c_macro_cursor_output_3))){
      input = Var_string(_x2c_macro_cursor_output_3);
      fprintf(stderr, " %s", input);
    }

  }
  fputc('\n', stderr);
}

static void _preprocessor_errors(String text){
  File_printf(Stderr, "%s", text);
}

static void Translation_translate_serial(Translation * t){
  int done = 0;
  {
    String input;
    List _x2c_macro_object_4 =(* t).request -> inputs;
    List _x2c_macro_cursor_4 = _x2c_macro_object_4;
    Var _x2c_macro_cursor_output_4;
    while(List_try_next(_x2c_macro_object_4, &(_x2c_macro_cursor_4), &(_x2c_macro_cursor_output_4))){
      input = Var_string(_x2c_macro_cursor_output_4);
      {
        if((* t).build) Build_begin_translation((* t).build, input);
        else report_progress(45220543335690, done, (* t).total, input);
        Translation_translate(&((* t)), input);
        done ++;
        if((* t).build) Build_end_translation((* t).build, input, 0);
        else report_progress(45220543335690, done, (* t).total, input);
      }

    }

  }

}

static void Translation_translate(Translation * t, String input){
  _translate_unit((* t).frontend, input, Translation_output_dir(&((* t)), input));
}

static String Translation_output_dir(Translation * t, String input){
  if(! Map_truth((* t).unit_dirs)) return(* t).request -> out_dir;
  return Var_string(Map_getindex((* t).unit_dirs, String_var(input)));
}

static void Translation_report(Translation * t, unsigned long started_at){
  String out_dir =(* t).request -> out_dir;
  unsigned long long bytes = 0;
  {
    String input;
    List _x2c_macro_object_5 =(* t).request -> inputs;
    List _x2c_macro_cursor_5 = _x2c_macro_object_5;
    Var _x2c_macro_cursor_output_5;
    while(List_try_next(_x2c_macro_object_5, &(_x2c_macro_cursor_5), &(_x2c_macro_cursor_output_5))){
      input = Var_string(_x2c_macro_cursor_output_5);
      {
        String stem = Path_stem(input);
        bytes += report_file_bytes(String_join(NULL, cons(String_var(out_dir), cons(String_var(_17), cons(String_var(stem), cons(String_var(_18), NULL))))));
        bytes += report_file_bytes(String_join(NULL, cons(String_var(out_dir), cons(String_var(_17), cons(String_var(stem), cons(String_var(_19), NULL))))));
      }

    }

  }
  String duration = report_duration(report_now_us() - started_at);
  int n =(* t).total;
  String noun = n == 1 ? _20 : _21;
  report_line(42217975014, String_join(NULL, cons(String_var(_22), cons(String_var(int_str(n)), cons(String_var(_23), cons(String_var(noun), cons(String_var(_24), cons(String_var(out_dir), cons(String_var(_25), cons(String_var(duration), NULL))))))))));
  report_generated(n, bytes);
}

static int Translation_translate_parallel(Translation * t){
  Translation_preload_modules(&((* t)));
  int count = Map_truth((* t).unit_dirs) ?(* t).total :(* t).request -> jobs;
  Array slices = _slices((* t).request -> inputs, (* t).total, count);
  int failed = Translation_run_workers(&((* t)), slices);
  Array_free(slices);
  return failed;
}

int Compiler_links_extension(String);

int Path_is_file(Path);

void Compiler_preload_native_module(String);

static void Translation_preload_modules(Translation * t){
  List roots = CliRequest_package_roots((* t).request);
  if(! List_truth(roots)) return;
  {
    String name;
    Iter _x2c_macro_iterator_6 = Map_keys(Translation_package_names(&((* t)), roots), &(struct Iter){
      int_var(0)
    }
    );
    Var _x2c_macro_item_6;
    while(Iter_try_next(_x2c_macro_iterator_6, &(_x2c_macro_item_6))){
      name = Var_string(_x2c_macro_item_6);
      {
        String root = NULL;
        if(! String_truth(package_entry((* t).request -> sources, roots, name, &(root))) || Compiler_links_extension(name)) continue;
        String module = String_join(NULL, cons(String_var(root), cons(String_var(_26), cons(String_var(name), cons(String_var(_27), NULL)))));
        if(Path_is_file(module)) Compiler_preload_native_module(module);
      }

    }

  }

}

String Path_read_text(Path);

Path Path_basename(Path);

#include "error.h"




static Map Translation_package_names(Translation * t, List roots){
  Map names = Map_new();
  {
    String input;
    List _x2c_macro_object_9 =(* t).request -> inputs;
    List _x2c_macro_cursor_9 = _x2c_macro_object_9;
    Var _x2c_macro_cursor_output_8;
    while(List_try_next(_x2c_macro_object_9, &(_x2c_macro_cursor_9), &(_x2c_macro_cursor_output_8))){
      input = Var_string(_x2c_macro_cursor_output_8);
      {
        {
          String name;
          List _x2c_macro_object_7 = _imported_packages(input);
          List _x2c_macro_cursor_7 = _x2c_macro_object_7;
          Var _x2c_macro_cursor_output_6;
          while(List_try_next(_x2c_macro_object_7, &(_x2c_macro_cursor_7), &(_x2c_macro_cursor_output_6))){
            name = Var_string(_x2c_macro_cursor_output_6);
            Map_setindex(names, String_var(name), int_var(1));
          }

        }
        String depfile =({
          Var _x2c_literal_part_0 = String_var(Translation_output_dir(&((* t)), input));  Var _x2c_literal_part_1 = String_var(Path_stem(input));  String_join(NULL, cons(_x2c_literal_part_0, cons(String_var(_17), cons(_x2c_literal_part_1, cons(String_var(_28), NULL)))));
        }
        );
        String volatile text = NULL;
        {
          ExceptionFrame _x2c_exception_frame_0;
          static MatchCaptureSite _x2c_macro_arms_0[1];
          Var _x2c_macro_patterns_0[1];
          static ErrorCatchSite _x2c_macro_site_0 ={
            _x2c_macro_arms_0, -1, 1, ERROR_CATCH_PENDING, - 1
          }
          ;
          if(x2c_error_catch_site_pending(& _x2c_macro_site_0)){
            _x2c_macro_patterns_0[0] = List_var(cons(List_var(cons(Symbol_var(62436), cons(Symbol_var(31862161386376), cons(Symbol_var(20399393368), NULL)))), cons(Symbol_var(54), NULL)));
          }
          volatile ErrorHandler _x2c_error_handler_0 = x2c_error_catch_site_push(& _x2c_exception_frame_0, & _x2c_macro_site_0, _x2c_macro_patterns_0);
          x2c_exception_push(& _x2c_exception_frame_0);
          if(! sigsetjmp(_x2c_exception_frame_0.env, 0)) text = Path_read_text(depfile);
          else{
            x2c_exception_landed(& _x2c_exception_frame_0);
            if(x2c_exception_is_error_target(& _x2c_exception_frame_0)){
              int _x2c_macro_selected_0 = x2c_error_catch_selected(_x2c_error_handler_0);
              x2c_error_catch_detach(_x2c_error_handler_0);
              x2c_exception_mark_handled(& _x2c_exception_frame_0);
              if(_x2c_macro_selected_0 == 0){
                {
                  {
                    x2c_error_catch_close(_x2c_error_handler_0);
                    _x2c_error_handler_0 = NULL;
                    x2c_exception_leave(& _x2c_exception_frame_0);
                    continue;
                  }

                }

              }

            }
            else{
              x2c_error_catch_close(_x2c_error_handler_0);
              _x2c_error_handler_0 = NULL;
              x2c_exception_leave(& _x2c_exception_frame_0);
              __builtin_unreachable();
            }

          }
          x2c_error_catch_close(_x2c_error_handler_0);
          _x2c_error_handler_0 = NULL;
          x2c_exception_leave(& _x2c_exception_frame_0);
        }
        {
          String dependency;
          List _x2c_macro_object_8 = translation_depfile_parse(text);
          List _x2c_macro_cursor_8 = _x2c_macro_object_8;
          Var _x2c_macro_cursor_output_7;
          while(List_try_next(_x2c_macro_object_8, &(_x2c_macro_cursor_8), &(_x2c_macro_cursor_output_7))){
            dependency = Var_string(_x2c_macro_cursor_output_7);
            {
              String package = package_directory(roots, dependency);
              if(String_truth(package)) Map_setindex(names, String_var(Path_basename(package)), int_var(1));
            }

          }

        }

      }

    }

  }
  return names;
}

static List _imported_packages(String path){
  String volatile text = NULL;
  {
    ExceptionFrame _x2c_exception_frame_1;
    static MatchCaptureSite _x2c_macro_arms_1[1];
    Var _x2c_macro_patterns_1[1];
    static ErrorCatchSite _x2c_macro_site_1 ={
      _x2c_macro_arms_1, -1, 1, ERROR_CATCH_PENDING, - 1
    }
    ;
    if(x2c_error_catch_site_pending(& _x2c_macro_site_1)){
      _x2c_macro_patterns_1[0] = List_var(cons(List_var(cons(Symbol_var(62436), cons(Symbol_var(31862161386376), cons(Symbol_var(20399393368), NULL)))), cons(Symbol_var(54), NULL)));
    }
    volatile ErrorHandler _x2c_error_handler_1 = x2c_error_catch_site_push(& _x2c_exception_frame_1, & _x2c_macro_site_1, _x2c_macro_patterns_1);
    x2c_exception_push(& _x2c_exception_frame_1);
    if(! sigsetjmp(_x2c_exception_frame_1.env, 0)) text = Path_read_text(path);
    else{
      x2c_exception_landed(& _x2c_exception_frame_1);
      if(x2c_exception_is_error_target(& _x2c_exception_frame_1)){
        int _x2c_macro_selected_1 = x2c_error_catch_selected(_x2c_error_handler_1);
        x2c_error_catch_detach(_x2c_error_handler_1);
        x2c_exception_mark_handled(& _x2c_exception_frame_1);
        if(_x2c_macro_selected_1 == 0){
          {
            List _x2c_return_value_0 = NULL;
            {
              x2c_error_catch_close(_x2c_error_handler_1);
              _x2c_error_handler_1 = NULL;
              x2c_exception_leave(& _x2c_exception_frame_1);
              return _x2c_return_value_0;
            }

          }

        }
        __builtin_unreachable();
      }
      else{
        x2c_error_catch_close(_x2c_error_handler_1);
        _x2c_error_handler_1 = NULL;
        x2c_exception_leave(& _x2c_exception_frame_1);
        __builtin_unreachable();
      }

    }
    x2c_error_catch_close(_x2c_error_handler_1);
    _x2c_error_handler_1 = NULL;
    x2c_exception_leave(& _x2c_exception_frame_1);
  }
  Tokenizer tokens = Tokenizer_new(text, 3945159);
  Tokenizer_scan(tokens);
  Array names = Array_new();
  int depth = 0;
  for(Token token = Tokenizer_next(tokens);  token -> type != 11212;  token = Tokenizer_next(tokens)){
    if(String_equal(token -> text, _29)) depth ++;
    else if(String_equal(token -> text, _30)) depth --;
    else if(! depth && String_equal(token -> text, _31)){
      token = Tokenizer_next(tokens);
      if(token -> type == 27051791223990) Array_push(names, String_var(String_getslice(token -> text, 1, - 1, 1)));
    }

  }
  return Array_list_free(names);
}

static Array _slices(List inputs, int total, int count){
  if(count > total) count = total;
  if(count < 1) count = 1;
  int size =(total + count - 1) / count;
  Array slices = Array_new();
  List at = inputs;
  while(List_truth(at)){
    Array slice = Array_new();
    for(int n = 0;  n < size && List_truth(at);  n ++, at = List_cdr(at)) Array_push(slice, List_car(at));
    Array_push(slices, List_var(Array_list_free(slice)));
  }
  return slices;
}

static int Translation_run_workers(Translation * t, Array slices){
  int jobs =(* t).request -> jobs, count = Array_len(slices);
  if(jobs > count) jobs = count;
  if((* t).request -> verbose) fprintf(stderr, "x2c: translate with %d workers over %d files\n", jobs, (* t).total);
  _workers =(Workers){
    .t = &(* t), .slices = slices, .pids = Scope_calloc(jobs, sizeof(long)), .carried = Scope_calloc(jobs, sizeof(int)), .captures = Scope_calloc(jobs, sizeof(File)), .output = Scope_calloc(count, sizeof(Block))
  }
  ;
  struct sigaction term, interrupt;
  _forward_stop_signal(SIGTERM, & term);
  _forward_stop_signal(SIGINT, & interrupt);
  while(_workers.started < count || _workers.live){
    if(_workers.started < count && _workers.live < jobs) Workers_start(&(_workers));
    else Workers_reap(&(_workers));
    Workers_show(&(_workers));
  }
  sigaction(SIGTERM, & term, NULL);
  sigaction(SIGINT, & interrupt, NULL);
  Scope_free(_workers.output);
  Scope_free(_workers.captures);
  Scope_free(_workers.carried);
  Scope_free(_workers.pids);
  return _workers.failed;
}

static void Workers_start(Workers * w){
  int index =(* w).started ++;
  List slice = Var_list(Array_getindex((* w).slices, index));
  if((* w).t -> build) Build_begin_translation((* w).t -> build, Var_string(List_car(slice)));
  File capture = tmpfile();
  sigset_t unblocked = _block_stop_signals();
  long pid = capture ? worker_fork() : - 1;
  if(! pid){
    (* w).live = 0;
    sigprocmask(SIG_SETMASK, & unblocked, NULL);
    dup2(File_fileno(capture), STDERR_FILENO);
    Translation_work(&((*(* w).t)), slice);
  }
  if(pid > 0){
    (* w).carried[(* w).live] = index;
    (* w).captures[(* w).live] = capture;
    (* w).pids[(* w).live] = pid;
    (* w).live ++;
  }
  sigprocmask(SIG_SETMASK, & unblocked, NULL);
  if(pid > 0) return;
  if(capture) File_close(capture);
  report_line(11703268, _32);
  (* w).failed ++;
}

void Compiler_stop_meta_helper(void);

static void Translation_work(Translation * t, List slice){
  {
    String input;
    List _x2c_macro_object_10 = slice;
    List _x2c_macro_cursor_10 = _x2c_macro_object_10;
    Var _x2c_macro_cursor_output_9;
    while(List_try_next(_x2c_macro_object_10, &(_x2c_macro_cursor_10), &(_x2c_macro_cursor_output_9))){
      input = Var_string(_x2c_macro_cursor_output_9);
      Translation_translate(&((* t)), input);
    }

  }
  Compiler_stop_meta_helper();
  worker_exit(0);
}

static void Workers_reap(Workers * w){
  int status, slot = worker_wait_any((* w).pids, (* w).live, &(status));
  if(status)(* w).failed ++;
  int index =(* w).carried[slot];
  List slice = Var_list(Array_getindex((* w).slices, index));
  File capture =(* w).captures[slot];
  {
    _x2c_defer_env_1 _x2c_macro_environment_1 ={
      0
    }
    ;
    _x2c_macro_environment_1._x2c_defer_capture_1 =(const void *) & capture;
    X2CCleanup _x2c_defer_record_1 ={
      .fn = _x2c_defer_cleanup_1, .env = & _x2c_macro_environment_1
    }
    ;
    x2c_cleanup_push(& _x2c_defer_record_1);
    {
      File_rewind(capture);
      Block output = Block_new(sizeof(char));
      File_read_into(capture, output);
      (* w).output[index] = output;
      if((* w).t -> build && ! status) Build_end_translation((* w).t -> build, Var_string(List_car(slice)), 0);
      (* w).done += List_len(slice);
      sigset_t unblocked = _block_stop_signals();
      (* w).live --;
      (* w).pids[slot] =(* w).pids[(* w).live];
      (* w).carried[slot] =(* w).carried[(* w).live];
      (* w).captures[slot] =(* w).captures[(* w).live];
      sigprocmask(SIG_SETMASK, & unblocked, NULL);
      if(!(* w).t -> build) report_progress(45220543335690, (* w).done, (* w).t -> total, NULL);
    }
    x2c_cleanup_leave(& _x2c_defer_record_1);
  }

}

static void Workers_show(Workers * w){
  while((* w).shown <(* w).started && ! Workers_carries(&((* w)), (* w).shown)){
    Block output =(* w).output[(* w).shown ++];
    if(output == NULL) continue;
    {
      _x2c_defer_env_2 _x2c_macro_environment_2 ={
        0
      }
      ;
      _x2c_macro_environment_2._x2c_defer_capture_2 =(const void *) & output;
      X2CCleanup _x2c_defer_record_2 ={
        .fn = _x2c_defer_cleanup_2, .env = & _x2c_macro_environment_2
      }
      ;
      x2c_cleanup_push(& _x2c_defer_record_2);
      {
        if(! output -> length){
          x2c_cleanup_leave(& _x2c_defer_record_2);
          continue;
        }
        report_suspend();
        File_write_all(stderr, output -> bytes, output -> length);
      }
      x2c_cleanup_leave(& _x2c_defer_record_2);
    }

  }

}

static int Workers_carries(Workers * w, int index){
  for(int slot = 0;  slot <(* w).live;  slot ++) if((* w).carried[slot] == index) return 1;
  return 0;
}

static void _forward_stop(int number){
  for(int slot = 0;  slot < _workers.live;  slot ++) kill((pid_t) _workers.pids[slot], number);
  signal(number, SIG_DFL);
  kill(getpid(), number);
}

static void _forward_stop_signal(int number, struct sigaction * previous){
  struct sigaction forward ={
    .sa_handler = _forward_stop
  }
  ;
  sigaction(number, NULL, previous);
  if(previous -> sa_handler != SIG_IGN) sigaction(number, & forward, NULL);
}

static sigset_t _block_stop_signals(void){
  sigset_t stops, previous;
  sigemptyset(& stops);
  sigaddset(& stops, SIGTERM);
  sigaddset(& stops, SIGINT);
  sigprocmask(SIG_BLOCK, & stops, & previous);
  return previous;
}

static int _run_build(CliRequest request){
  Array commands = String_truth(request -> compile_commands) && ! request -> dry_run ? Array_new() : NULL;
  int status = List_truth(request -> inputs) ? _build_inputs(request, commands) : _build_manifest(request, commands);
  if(status || commands == NULL || request -> command == 38236) return status;
  return ! compile_commands_write(request -> compile_commands, commands);
}

static int _build_inputs(CliRequest request, Array commands){
  if(String_truth(request -> manifest)) driver_error("--manifest-path conflicts with explicit inputs");
  if(String_truth(request -> target)) driver_error("--target conflicts with explicit inputs");
  if(String_truth(request -> profile)) driver_error("--profile conflicts with explicit inputs");
  return _build_target(request, commands);
}

static int _build_manifest(CliRequest request, Array commands){
  if(request -> compile_only) driver_error("--compile-only needs input operands, not a manifest");
  for(ProjectBuild node = project_plan(request);  node;  node = node -> next){
    int status = _build_target(node -> request, commands);
    if(status) return status;
  }
  return 0;
}

static int _build_target(CliRequest request, Array commands){
  Context target = Context_open_isolated_named("build target");
  {
    _x2c_defer_env_3 _x2c_macro_environment_3 ={
      0
    }
    ;
    _x2c_macro_environment_3._x2c_defer_capture_3 =(const void *) & target;
    X2CCleanup _x2c_defer_record_3 ={
      .fn = _x2c_defer_cleanup_4, .env = & _x2c_macro_environment_3
    }
    ;
    x2c_cleanup_push(& _x2c_defer_record_3);
    {
      {
        X2CCleanup _x2c_defer_record_4 ={
          .fn = _x2c_defer_cleanup_3, .env = 0
        }
        ;
        x2c_cleanup_push(& _x2c_defer_record_4);
        {
          Build b = CliRequest_prepare(request);
          request -> cc = Var_string(Context_export(target, String_var(request -> cc)));
          request -> meta_cc = Var_string(Context_export(target, String_var(request -> meta_cc)));
          request -> ar = Var_string(Context_export(target, String_var(request -> ar)));
          int status = _translate_target(request, b);
          if(! status) status = Build_finish(b);
          if(! status) status = _add_commands(request, b, target, commands);
          if(status){
            Build_cleanup(b, 0);
            {
              int _x2c_return_value_1 = status;
              {
                x2c_cleanup_leave(& _x2c_defer_record_4);
                x2c_cleanup_leave(& _x2c_defer_record_3);
                return _x2c_return_value_1;
              }

            }

          }
          Build_report_success(b);
          if(request -> command == 38236) status = Build_run_program(b);
          else if(request -> command == 1282559016 && ! request -> dry_run) Build_publish_script(b, String_join(NULL, cons(String_var(request -> build_dir), cons(String_var(_33), NULL))));
          Build_cleanup(b, 1);
          {
            int _x2c_return_value_2 = status;
            {
              x2c_cleanup_leave(& _x2c_defer_record_4);
              x2c_cleanup_leave(& _x2c_defer_record_3);
              return _x2c_return_value_2;
            }

          }

        }
        x2c_cleanup_leave(& _x2c_defer_record_4);
      }

    }
    x2c_cleanup_leave(& _x2c_defer_record_3);
  }

}

static int _translate_target(CliRequest request, Build b){
  int status = _translate_units(request, b, request -> inputs);
  if(! status && request -> command == 1282559016 && ! request -> dry_run) status = _translate_units(request, b, Build_script_helpers(b));
  if(status || request -> dry_run) return status;
  if(request -> kind != 904178442 && ! List_truth(request -> extensions)) return 0;
  CliRequest entry = request -> kind == 904178442 ? Build_module_entry(b) : Build_extension_entries(b);
  return _translate_units(entry, b, entry -> inputs);
}

static int _add_commands(CliRequest request, Build b, Context target, Array commands){
  if(commands == NULL) return 0;
  {
    String entry;
    Array _x2c_macro_object_11 = b -> compile_commands;
    int _x2c_macro_cursor_11 = 0;
    Var _x2c_macro_cursor_output_10;
    while(Array_try_next(_x2c_macro_object_11, &(_x2c_macro_cursor_11), &(_x2c_macro_cursor_output_10))){
      entry = Var_string(_x2c_macro_cursor_output_10);
      Array_push(commands, Context_export(target, String_var(entry)));
    }

  }
  if(request -> command != 38236) return 0;
  return ! compile_commands_write(request -> compile_commands, commands);
}

static int _translate_units(CliRequest request, Build b, List units){
  Map stale = Map_new();
  List inputs = _stale_inputs(b, units, stale);
  if(! request -> dry_run && List_truth(inputs)){
    CliRequest translation = Scope_memdup(request, sizeof(struct CliRequest));
    translation -> inputs = inputs;
    translation -> out_dir = b -> gen_root;
    if(_run_translation(translation, stale, b)) return 1;
  }
  _register_units(request, b, units, stale);
  return 0;
}

static List _stale_inputs(Build b, List units, Map stale){
  Array inputs = Array_new();
  {
    String input;
    List _x2c_macro_object_12 = units;
    List _x2c_macro_cursor_12 = _x2c_macro_object_12;
    Var _x2c_macro_cursor_output_11;
    while(List_try_next(_x2c_macro_object_12, &(_x2c_macro_cursor_12), &(_x2c_macro_cursor_output_11))){
      input = Var_string(_x2c_macro_cursor_output_11);
      {
        if(! is_source_file(input)) continue;
        String directory = Build_generated_dir(b, input);
        if(Build_translation_current(b, input, directory)){
          Build_begin_translation(b, input);
          Build_end_translation(b, input, 1);
          continue;
        }
        Map_setindex(stale, String_var(input), String_var(directory));
        Array_push(inputs, String_var(input));
      }

    }

  }
  return Array_list_free(inputs);
}

static void _register_units(CliRequest request, Build b, List units, Map stale){
  {
    String input;
    List _x2c_macro_object_13 = units;
    List _x2c_macro_cursor_13 = _x2c_macro_object_13;
    Var _x2c_macro_cursor_output_12;
    while(List_try_next(_x2c_macro_object_13, &(_x2c_macro_cursor_13), &(_x2c_macro_cursor_output_12))){
      input = Var_string(_x2c_macro_cursor_output_12);
      {
        if(! is_source_file(input)) continue;
        String directory = Build_generated_dir(b, input);
        if(Map_contains(stale, String_var(input)) && request -> dry_run){
          Build_begin_translation(b, input);
          fprintf(stderr, "x2c: translate --out-dir %s %s\n", directory, input);
          Build_end_translation(b, input, 0);
        }
        else if(Map_contains(stale, String_var(input))) Build_record_translation(b, input, directory);
        Build_add_generated(b, input, directory);
      }

    }

  }

}

static int _run_env(CliRequest request){
  String wanted = NULL;
  if(List_truth(request -> inputs)) wanted = Var_string(List_car(request -> inputs));
  {
    List row;
    List _x2c_macro_object_14 = _env_rows(request);
    List _x2c_macro_cursor_14 = _x2c_macro_object_14;
    Var _x2c_macro_cursor_output_13;
    while(List_try_next(_x2c_macro_object_14, &(_x2c_macro_cursor_14), &(_x2c_macro_cursor_output_13))){
      row = Var_list(_x2c_macro_cursor_output_13);
      {
        String name, value;
        List _x2c_destructure_0 = row;
        name = Var_string(List_getindex(_x2c_destructure_0, 0));
        value = Var_string(List_getindex(_x2c_destructure_0, 1));
        const char * text = String_truth(value) ? value : "";
        if(! String_truth(wanted)) printf("%s = %s\n", name, text);
        else if(String_equal(name, wanted)){
          printf("%s\n", text);
          return 0;
        }

      }

    }

  }
  if(String_truth(wanted)) driver_error(String_join(NULL, cons(String_var(_34), cons(String_var(wanted), cons(String_var(_35), NULL)))));
  return 0;
}

static List _env_rows(CliRequest request){
  Toolchain toolchain = toolchain_new(request);
  String executable = x2c_get_executable();
  String roots = String_join(_36, CliRequest_package_roots(request));
  interface_configure(request -> out_dir, 0);
  return({
    Var _x2c_literal_part_2 = List_var(cons(_38, cons(String_var(x2c_get_root()), NULL)));  Var _x2c_literal_part_3 = List_var(cons(_40, cons(String_var(executable), NULL)));  Var _x2c_literal_part_4 = List_var(cons(_42, cons(String_var(home_libexec()), NULL)));  Var _x2c_literal_part_5 = List_var(cons(_44, cons(String_var(compiler_identity()), NULL)));  Var _x2c_literal_part_6 = List_var(cons(_46, cons(String_var(toolchain -> include_dir), NULL)));  Var _x2c_literal_part_7 = List_var(cons(_48, cons(String_var(toolchain -> runtime_lib), NULL)));  Var _x2c_literal_part_8 = List_var(cons(_50, cons(String_var(interface_prelude()), NULL)));  Var _x2c_literal_part_9 = List_var(cons(_52, cons(String_var(roots), NULL)));  Var _x2c_literal_part_10 = List_var(cons(_54, cons(String_var(toolchain -> cc), NULL)));  Var _x2c_literal_part_11 = List_var(cons(_56, cons(String_var(toolchain -> ar), NULL)));  Var _x2c_literal_part_12 = List_var(cons(_58, cons(String_var(script_cache_root()), NULL)));  cons(_x2c_literal_part_2, cons(_x2c_literal_part_3, cons(_x2c_literal_part_4, cons(_x2c_literal_part_5, cons(_x2c_literal_part_6, cons(_x2c_literal_part_7, cons(_x2c_literal_part_8, cons(_x2c_literal_part_9, cons(_x2c_literal_part_10, cons(_x2c_literal_part_11, cons(_x2c_literal_part_12, NULL)))))))))));
  }
  );
}

static void _run_external(int argc, char * * argv){
  String path = _external_path(argv[1]);
  if(String_truth(path)) _exec(path, argv + 1);
  if(argc != 3 || strcmp(argv[1], "help")) return;
  char * args[] ={
    NULL, "--help", NULL
  }
  ;
  path = _external_path(argv[2]);
  if(String_truth(path)) _exec(path, args);
}

int Path_is_executable(Path);

static String _external_path(const char * name){
  if(! _external_name(name) || cli_builtin_command(name)) return NULL;
  String libexec = home_libexec();
  if(! String_truth(libexec)) return NULL;
  String path =({
    Var _x2c_literal_part_13 = String_var(libexec);  Var _x2c_literal_part_14 = String_var(String_new(name));  String_join(NULL, cons(_x2c_literal_part_13, cons(String_var(_59), cons(_x2c_literal_part_14, NULL))));
  }
  );
  return Path_is_executable(path) ? path : NULL;
}

static int _external_name(const char * name){
  if(! name || ! isalpha((unsigned char) * name)) return 0;
  for(const char * p = name + 1;  * p;  p ++) if(! isalnum((unsigned char) * p) && * p != '-' && * p != '_') return 0;
  return 1;
}

static void _exec(String path, char * * args){
  String home = home_dir(), executable = x2c_get_executable();
  String identity = compiler_identity();
  if(String_truth(home)) setenv("X2C_HOME", home, 1);
  if(String_truth(executable)) setenv("X2C", executable, 1);
  if(String_truth(identity)) setenv("X2C_IDENTITY", identity, 1);
  args[0] = path;
  execv(path, args);
  driver_error(({
    Var _x2c_literal_part_15 = String_var(path);  Var _x2c_literal_part_16 = String_var(String_new(strerror(errno)));  String_join(NULL, cons(String_var(_60), cons(_x2c_literal_part_15, cons(String_var(_61), cons(_x2c_literal_part_16, NULL)))));
  }
  ));
}

int diagnostics_write_json(String);

int main(int argc, char * * argv){
  x2c_initialize();
  if(! _init_guard_) _file_init_();
  x2c_initialize_environment(argv[0]);
  if(argc > 1 && ! strcmp(argv[1], "editor")){
    argv[1] = argv[0];
    return editor_request(argc - 1, argv + 1);
  }
  if(argc > 1) _run_external(argc, argv);
  CliRequest request = cli_parse(argc, argv);
  String diagnostics = request -> diagnostics_file;
  if(String_truth(diagnostics) && ! diagnostics_write_json(diagnostics)) driver_error(String_join(NULL, cons(String_var(_62), cons(String_var(diagnostics), cons(String_var(_35), NULL)))));
  if(request -> command == 1282559016 && script_prepare(request)) return 0;
  report_configure(request -> quiet, request -> plain, request -> color_mode, request -> verbose || request -> debugging, request -> dry_run, CliRequest_inspects(request));
  switch(request -> command){
    case 11180 : return _run_env(request);
    case 20308036376 : return install_command(request);
    case 1219329418 : return remove_command(request);
    case 806120 : return list_command(request);
    case 29038 : return new_command(request);
  }
  return _run_compiler(request);
}

static int _run_compiler(CliRequest request){
  _configure_logging(request -> debugging);
  Frontend_load_support(request);
  Context command = Context_open_isolated_named("compiler command");
  int status = request -> command == 45220543335690 ? _run_translation(request, NULL, NULL) : _run_build(request);
  Context_close(command);
  if(request -> command == 1282559016 && ! status) status = script_run(request);
  return status;
}

static void _configure_logging(int debugging){
  Logger logger = log_get_global_logger();
  if(! logger) return;
  Logger_clear_sinks(logger);
  if(! debugging) return;
  Logger_set_min_level(logger, 8721742);
  Logger_add_stderr_sink(logger);
}

static void _x2c_defer_cleanup_0(void * _x2c_defer_opaque_0){
  _x2c_defer_env_0 * _x2c_defer_data_0 =(_x2c_defer_env_0 *) _x2c_defer_opaque_0;
  ParsedUnit_close(&((*(ParsedUnit *) _x2c_defer_data_0->_x2c_defer_capture_0)));
}

static void _x2c_defer_cleanup_1(void * _x2c_defer_opaque_1){
  _x2c_defer_env_1 * _x2c_defer_data_1 =(_x2c_defer_env_1 *) _x2c_defer_opaque_1;
  File_close((*(File *) _x2c_defer_data_1->_x2c_defer_capture_1));
}

static void _x2c_defer_cleanup_2(void * _x2c_defer_opaque_2){
  _x2c_defer_env_2 * _x2c_defer_data_2 =(_x2c_defer_env_2 *) _x2c_defer_opaque_2;
  Block_free((*(Block *) _x2c_defer_data_2->_x2c_defer_capture_2));
}

void macro_library_reset(void);

static void _x2c_defer_cleanup_3(void * _x2c_defer_opaque_3){
  macro_library_reset();
}

static void _x2c_defer_cleanup_4(void * _x2c_defer_opaque_4){
  _x2c_defer_env_3 * _x2c_defer_data_3 =(_x2c_defer_env_3 *) _x2c_defer_opaque_4;
  Context_cleanup((*(Context *) _x2c_defer_data_3->_x2c_defer_capture_3));
}

