#define _x2c_initializer_choice_B1CED777_0_expanded(_x2c_static_input_0) static void _x2c_static_initialize_0(void){\
  _x2c_static_input_0;\
}
#define _x2c_initializer_choice_B1CED777_0(_x2c_static_input_0) _x2c_initializer_choice_B1CED777_0_expanded(_x2c_static_input_0)
#define _x2c_initializer_choice_B1CED777_1_expanded(_x2c_static_input_1) static void _x2c_static_initialize_1(void){\
  _x2c_static_input_1;\
}
#define _x2c_initializer_choice_B1CED777_1(_x2c_static_input_1) _x2c_initializer_choice_B1CED777_1_expanded(_x2c_static_input_1)
#define _x2c_initializer_choice_B1CED777_2_expanded(_x2c_static_input_2) static void _x2c_static_initialize_2(void){\
  _x2c_static_input_2;\
}
#define _x2c_initializer_choice_B1CED777_2(_x2c_static_input_2) _x2c_initializer_choice_B1CED777_2_expanded(_x2c_static_input_2)
#define _x2c_initializer_choice_B1CED777_3_expanded(_x2c_static_input_3) static void _x2c_static_initialize_3(void){\
  _x2c_static_input_3;\
}
#define _x2c_initializer_choice_B1CED777_3(_x2c_static_input_3) _x2c_initializer_choice_B1CED777_3_expanded(_x2c_static_input_3)
#define _x2c_initializer_choice_B1CED777_4_expanded(_x2c_static_input_4) static void _x2c_static_initialize_4(void){\
  _x2c_static_input_4;\
}
#define _x2c_initializer_choice_B1CED777_4(_x2c_static_input_4) _x2c_initializer_choice_B1CED777_4_expanded(_x2c_static_input_4)
#define _x2c_initializer_choice_B1CED777_5_expanded(_x2c_static_input_5) static void _x2c_static_initialize_5(void){\
  _x2c_static_input_5;\
}
#define _x2c_initializer_choice_B1CED777_5(_x2c_static_input_5) _x2c_initializer_choice_B1CED777_5_expanded(_x2c_static_input_5)
#define _x2c_initializer_choice_B1CED777_6_expanded(_x2c_static_input_6) static void _x2c_static_initialize_6(void){\
  _x2c_static_input_6;\
}
#define _x2c_initializer_choice_B1CED777_6(_x2c_static_input_6) _x2c_initializer_choice_B1CED777_6_expanded(_x2c_static_input_6)
#define _x2c_initializer_choice_B1CED777_7_expanded(_x2c_static_input_7) static void _x2c_static_initialize_7(void){\
  _x2c_static_input_7;\
}
#define _x2c_initializer_choice_B1CED777_7(_x2c_static_input_7) _x2c_initializer_choice_B1CED777_7_expanded(_x2c_static_input_7)
#define _x2c_initializer_choice_B1CED777_8_expanded(_x2c_static_input_8) static void _x2c_static_initialize_8(void){\
  _x2c_static_input_8;\
}
#define _x2c_initializer_choice_B1CED777_8(_x2c_static_input_8) _x2c_initializer_choice_B1CED777_8_expanded(_x2c_static_input_8)
#define _x2c_initializer_choice_B1CED777_9_expanded(_x2c_static_input_9) static void _x2c_static_initialize_9(void){\
  _x2c_static_input_9;\
}
#define _x2c_initializer_choice_B1CED777_9(_x2c_static_input_9) _x2c_initializer_choice_B1CED777_9_expanded(_x2c_static_input_9)
#define _x2c_initializer_choice_B1CED777_10_expanded(_x2c_static_input_10) static void _x2c_static_initialize_10(void){\
  _x2c_static_input_10;\
}
#define _x2c_initializer_choice_B1CED777_10(_x2c_static_input_10) _x2c_initializer_choice_B1CED777_10_expanded(_x2c_static_input_10)
/* auto-generated by x2c.  Do not edit! */

#include "meta-helper-client.h"

#include "exception.h"

static List _78, _75, _74, _72, _71, _67, _65, _64, _62, _60, _59, _58, _57, _48, _45, _43, _42, _39, _38, _36, _34, _33, _32, _31, _29, _27, _26, _24, _13, _1;

static String _83, _81, _80, _79, _76, _14, _11, _10, _9, _6, _5, _4, _3, _2;

static Var _77, _73, _70, _69, _68, _66, _63, _61, _52, _50, _49, _46, _44, _41, _40, _37, _35, _30, _28, _25, _23, _18, _16, _15, _12, _8, _7, _0;

#include "meta-group.h"
#include "datum.h"
#include <errno.h>
#include <fcntl.h>
#include <poll.h>
#include <signal.h>
#include <stdlib.h>
#include <string.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>
static String helper_path;

_x2c_initializer_choice_B1CED777_0((helper_path = NULL))
static Map helper_failures, helper_units;

_x2c_initializer_choice_B1CED777_1((helper_failures = NULL))
_x2c_initializer_choice_B1CED777_2((helper_units = NULL))
static Scope helper_scope;

_x2c_initializer_choice_B1CED777_3((helper_scope = NULL))
static pid_t helper_pid, helper_owner;

_x2c_initializer_choice_B1CED777_4((helper_pid = 0))
_x2c_initializer_choice_B1CED777_5((helper_owner = 0))
static int helper_to, helper_from, helper_table;

_x2c_initializer_choice_B1CED777_6((helper_to = - 1))
_x2c_initializer_choice_B1CED777_7((helper_from = - 1))
_x2c_initializer_choice_B1CED777_8((helper_table = 0))
static int helper_reset;

_x2c_initializer_choice_B1CED777_9((helper_reset = 0))
static Buffer helper_input;

_x2c_initializer_choice_B1CED777_10((helper_input = NULL))
static int _init_guard_ = 0;

__attribute__((constructor)) static void _file_init_(void);

static void _helper_shutdown(void);

static int _helper_stop(int signal);

static int _helper_start(void);

static int _helper_send(List message);

static double _helper_limit(void);

static double _helper_now(void);

static int _helper_receive(double deadline, Var * reply);

static String _helper_ending(void);

typedef struct _x2c_defer_env_0{
  const void * _x2c_defer_capture_0;
}
_x2c_defer_env_0;

static void _x2c_defer_cleanup_0(void * _x2c_defer_opaque_0);

Var Symbol_var(Symbol);

List cons(Var, List);

Var String_var(String);

Var List_var(List);

__attribute__((constructor)) static void _file_init_(void){
  x2c_initialize_protocols();
  if(_init_guard_) return;
  _init_guard_ = 1;
  _0 = Symbol_var(1157736);
  _1 = cons(_0, NULL);
  _2 = String_new("the body exited with status ");
  _3 = String_new("the body crashed or overflowed the stack (signal ");
  _4 = String_new(": ");
  _5 = String_new(")");
  _6 = String_new("the project meta module was not built");
  _7 = Symbol_var(38115688);
  _8 = Symbol_var(199448);
  _9 = String_new("%s%g s");
  _10 = String_new("function: ");
  _11 = String_new("set X2C_META_TIMEOUT to a larger limit in seconds, or 0 for none");
  _12 = String_var(_11);
  _13 = cons(_12, NULL);
  _14 = String_new("reason: ");
  _15 = Symbol_var(49497918350);
  _16 = Symbol_var(2021158750666);
  _18 = Symbol_var(1976541542);
  _23 = Symbol_var(1318210446);
  _24 = cons(_23, NULL);
  _25 = Symbol_var(1362954);
  _26 = cons(_25, _24);
  _27 = cons(_16, _26);
  _28 = Symbol_var(62054);
  _29 = cons(_28, _27);
  _30 = Symbol_var(806120);
  _31 = cons(_30, NULL);
  _32 = cons(_25, _31);
  _33 = cons(_18, _32);
  _34 = cons(_28, _33);
  _35 = List_var(_34);
  _36 = cons(_35, NULL);
  _37 = List_var(_29);
  _38 = cons(_37, _36);
  _39 = cons(_15, _38);
  _40 = Symbol_var(46228810);
  _41 = Symbol_var(1992385866);
  _42 = cons(_41, NULL);
  _43 = cons(_40, _42);
  _44 = Symbol_var(1473096);
  _45 = cons(_44, NULL);
  _46 = Symbol_var(11703268);
  _48 = cons(_46, _38);
  _49 = Symbol_var(293581290303730);
  _50 = Symbol_var(61869328);
  _52 = Symbol_var(61344976);
  _57 = cons(_50, _26);
  _58 = cons(_28, _57);
  _59 = cons(_52, _26);
  _60 = cons(_28, _59);
  _61 = List_var(_60);
  _62 = cons(_61, NULL);
  _63 = List_var(_58);
  _64 = cons(_63, _62);
  _65 = cons(_49, _64);
  _66 = Symbol_var(28562377614);
  _67 = cons(_66, NULL);
  _68 = Symbol_var(12971715722);
  _69 = Symbol_var(61045002);
  _70 = Symbol_var(58262293080);
  _71 = cons(_70, NULL);
  _72 = cons(_69, _71);
  _73 = List_var(_72);
  _74 = cons(_73, NULL);
  _75 = cons(_68, _74);
  _76 = String_new("reason: the helper sent an unknown reply");
  _77 = String_var(_76);
  _78 = cons(_77, NULL);
  _79 = String_new("X2C_META_TIMEOUT");
  _80 = String_new("a struct");
  _81 = String_new("the compile-time helper did not start");
  _83 = String_new("this meta call stopped the compile-time helper");
  _x2c_static_initialize_0();
  _x2c_static_initialize_1();
  _x2c_static_initialize_2();
  _x2c_static_initialize_3();
  _x2c_static_initialize_4();
  _x2c_static_initialize_5();
  _x2c_static_initialize_6();
  _x2c_static_initialize_7();
  _x2c_static_initialize_8();
  _x2c_static_initialize_9();
  _x2c_static_initialize_10();
}

void Compiler_stop_meta_helper(void){
  if(! _init_guard_) _file_init_();
  _helper_stop(0);
}

void Scope_destroy(Scope);

static void _helper_shutdown(void){
  _helper_stop(0);
  Scope_destroy(helper_scope);
  helper_scope = NULL;
  helper_path = NULL;
  helper_failures = helper_units = NULL;
  helper_input = NULL;
}

int String_truth(String);

int Map_truth(Map);

void Scope_shutdown_hook(void(*)(void));

void Scope_push(Scope *);

String String_new(const char *);

Map Map_copy(Map);

Buffer Buffer_new(size_t);

void Scope_pop(void);

void Compiler_use_meta_helper(String path, Map failures, Map units){
  if(! _init_guard_) _file_init_();
  if(! String_truth(path) && ! Map_truth(failures)) return;
  if(! helper_scope) Scope_shutdown_hook(_helper_shutdown);
  Scope_push(& helper_scope);
  helper_path = String_truth(path) ? String_new(path) : NULL;
  helper_failures = Map_truth(failures) ? Map_copy(failures) : NULL;
  helper_units = Map_truth(units) ? Map_copy(units) : NULL;
  helper_input = Buffer_new(0);
  Scope_pop();
}

int Map_try_get(Map, Var, Var *);

Path Path_absolute(Path);

long Var_integer(Var);

void Compiler_begin_meta_unit(String filename){
  if(! _init_guard_) _file_init_();
  Var table;
  helper_table = Map_truth(helper_units) && String_truth(filename) && Map_try_get(helper_units, String_var(Path_absolute(filename)), &(table)) ? Var_integer(table) : 0;
  helper_reset = 1;
}

int Buffer_truth(Buffer);

Buffer Buffer_clear(Buffer);

static int _helper_stop(int signal){
  int status = 0;
  if(helper_pid > 0 && helper_owner == getpid()){
    if(signal) kill(helper_pid, signal);
    else _helper_send(_1);
    close(helper_to);
    close(helper_from);
    waitpid(helper_pid, & status, 0);
  }
  helper_pid = 0;
  helper_to = helper_from = - 1;
  if(Buffer_truth(helper_input)) Buffer_clear(helper_input);
  return status;
}

static int _helper_start(void){
  if(helper_pid > 0 && helper_owner == getpid()) return 1;
  helper_pid = 0;
  int requests[2], replies[2];
  if(pipe(requests) || pipe(replies)) return 0;
  for(int i = 0;  i < 2;  i ++){
    fcntl(requests[i], F_SETFD, FD_CLOEXEC);
    fcntl(replies[i], F_SETFD, FD_CLOEXEC);
  }
  pid_t pid = fork();
  if(! pid){
    int in = fcntl(requests[0], F_DUPFD_CLOEXEC, 10);
    int out = fcntl(replies[1], F_DUPFD_CLOEXEC, 10);
    dup2(in, 3);
    dup2(out, 4);
    execl(helper_path, helper_path, (char *) NULL);
    _exit(127);
  }
  close(requests[0]);
  close(replies[1]);
  helper_pid = pid;
  helper_owner = getpid();
  helper_to = requests[1];
  helper_from = replies[0];
  if(Buffer_truth(helper_input)) Buffer_clear(helper_input);
  helper_reset = 1;
  return 1;
}

int datum_frame(Buffer, Var);

String Buffer_str(Buffer);

int String_len(String);

static int _helper_send(List message){
  Buffer out = Buffer_new(0);
  {
    _x2c_defer_env_0 _x2c_defer_env_1 ={
      ._x2c_defer_capture_0 =(const void *) & out
    }
    ;
    X2CCleanup _x2c_defer_record_0 ={
      .fn = _x2c_defer_cleanup_0, .env = & _x2c_defer_env_1
    }
    ;
    x2c_cleanup_push(& _x2c_defer_record_0);
    {
      if(! datum_frame(out, List_var(message))){
        int _x2c_return_value_0 = 0;
        {
          x2c_cleanup_leave(& _x2c_defer_record_0);
          return _x2c_return_value_0;
        }

      }
      String frame = String_join(NULL, cons(String_var(Buffer_str(out)), NULL));
      void(* previous)(int) = signal(SIGPIPE, SIG_IGN);
      size_t done = 0, size = String_len(frame);
      while(done < size){
        ssize_t n = write(helper_to, (char *) frame + done, size - done);
        if(n < 0 && errno == EINTR) continue;
        if(n <= 0) break;
        done += n;
      }
      signal(SIGPIPE, previous);
      {
        int _x2c_return_value_1 = done == size;
        {
          x2c_cleanup_leave(& _x2c_defer_record_0);
          return _x2c_return_value_1;
        }

      }

    }
    x2c_cleanup_leave(& _x2c_defer_record_0);
  }

}

String Env_get(String);

double atof(const char *);

static double _helper_limit(void){
  String text = Env_get(_79);
  return String_truth(text) ? atof(text) : 60.0;
}

static double _helper_now(void){
  struct timespec now;
  clock_gettime(CLOCK_MONOTONIC, & now);
  return now.tv_sec + now.tv_nsec / 1e9;
}

void x2c_exception_push(ExceptionFrame *);

int datum_unframe(String, size_t *, Var *);

void x2c_exception_landed(ExceptionFrame *);

Buffer Buffer_write(Buffer, const char *);

String String_new_len(const char *, int);

static int _helper_receive(double deadline, Var * reply){
  for(; ; ){
    String input = Buffer_str(helper_input);
    size_t used = 0;
    int volatile framed = 0;
    {
      ExceptionFrame _x2c_exception_frame_0;
      MatchCaptureSite static _x2c_catch_arms_0[1];
      Var _x2c_catch_patterns_0[1];
      ErrorCatchSite static _x2c_catch_site_0 ={
        _x2c_catch_arms_0, -1, 1, ERROR_CATCH_PENDING, -1
      }
      ;
      if(x2c_error_catch_site_pending(& _x2c_catch_site_0)){
        _x2c_catch_patterns_0[0] = List_var(cons(List_var(cons(Symbol_var(62436), cons(Symbol_var(664344300629258), cons(Symbol_var(28682226919752), NULL)))), cons(Symbol_var(54), NULL)));
      }
      volatile ErrorHandler _x2c_error_handler_0 = x2c_error_catch_site_push(& _x2c_exception_frame_0, & _x2c_catch_site_0, _x2c_catch_patterns_0);
      x2c_exception_push(& _x2c_exception_frame_0);
      if(! sigsetjmp(_x2c_exception_frame_0.env, 0)) framed = datum_unframe(input, &(used), &((* reply)));
      else{
        x2c_exception_landed(& _x2c_exception_frame_0);
        if(x2c_exception_is_error_target(& _x2c_exception_frame_0)){
          x2c_error_catch_detach(_x2c_error_handler_0);
          x2c_exception_mark_handled(& _x2c_exception_frame_0);
          {
            {
              int _x2c_return_value_2 = 0;
              {
                x2c_error_catch_close(_x2c_error_handler_0);
                _x2c_error_handler_0 = NULL;
                x2c_exception_leave(& _x2c_exception_frame_0);
                return _x2c_return_value_2;
              }

            }

          }

        }
        else{
          x2c_error_catch_close(_x2c_error_handler_0);
          _x2c_error_handler_0 = NULL;
          x2c_exception_leave(& _x2c_exception_frame_0);
          __builtin_unreachable();
        }

      }
      x2c_error_catch_close(_x2c_error_handler_0);
      _x2c_error_handler_0 = NULL;
      x2c_exception_leave(& _x2c_exception_frame_0);
    }
    if(framed){
      String rest = String_getslice(input, used, -2147483648, 1);
      Buffer_clear(helper_input);
      if(String_truth(rest)) Buffer_write(helper_input, rest);
      return 1;
    }
    int wait = - 1;
    if(deadline > 0){
      double left = deadline - _helper_now();
      if(left <= 0) return - 1;
      wait =(int)(left * 1000) + 1;
    }
    struct pollfd ready ={
      .fd = helper_from, .events = POLLIN
    }
    ;
    int polled = poll(& ready, 1, wait);
    if(polled < 0 && errno == EINTR) continue;
    if(polled == 0) return - 1;
    char bytes[65536];
    ssize_t n = read(helper_from, bytes, sizeof bytes);
    if(n < 0 && errno == EINTR) continue;
    if(n <= 0) return 0;
    Buffer_write(helper_input, String_new_len(bytes, n));
  }

}

String int_str(int);

static String _helper_ending(void){
  int status = _helper_stop(0);
  int code = WEXITSTATUS(status);
  if(! WIFSIGNALED(status)) return String_join(NULL, cons(String_var(_2), cons(String_var(int_str(code)), NULL)));
  int signal = WTERMSIG(status);
  String name = String_new(strsignal(signal));
  return String_join(NULL, cons(String_var(_3), cons(String_var(int_str(signal)), cons(String_var(_4), cons(String_var(name), cons(String_var(_5), NULL))))));
}

void Compiler_refuse_meta_call(Compiler, String, Token, String);

String Var_string(Var);

Var int_var(int);

String Compiler_meta_call_missing(Compiler, String);

int String_startswith(String, String);

Var Macro_subject(void);

void Compiler_report_error(Compiler, Symbol, String, Token, List);

String String_printf(String, ...);

List Var_list(Var);

void Compiler_report_warning(Compiler, Symbol, String, Token, List);

void Map_merge_translation_dependency(Map, String, Var);

Symbol Error_raise(Symbol, List);

Var Compiler_meta_helper_call(Compiler c, String name, Token site, List arguments){
  if(! _init_guard_) _file_init_();
  Var failure;
  if(! String_truth(helper_path)) Compiler_refuse_meta_call(c, name, site, Var_string(Map_truth(helper_failures) && Map_try_get(helper_failures, int_var(- 1), &(failure)) ? failure : String_var(_6)));
  if(Map_truth(helper_failures) && Map_try_get(helper_failures, int_var(helper_table), &(failure))) Compiler_refuse_meta_call(c, name, site, Var_string(failure));
  String missing = Compiler_meta_call_missing(c, name);
  if(String_startswith(missing, _80)) Compiler_refuse_meta_call(c, name, site, missing);
  if(! _helper_start()) Compiler_refuse_meta_call(c, name, site, _81);
  if(helper_reset){
    _helper_send(cons(_7, cons(int_var(helper_table), NULL)));
    helper_reset = 0;
  }
  _helper_send(cons(_8, cons(String_var(name), cons(List_var(arguments), cons(Macro_subject(), NULL)))));
  double limit = _helper_limit();
  double deadline = limit > 0 ? _helper_now() + limit : 0;
  for(; ; ){
    Var reply;
    int status = _helper_receive(deadline, &(reply));
    if(status < 0){
      _helper_stop(SIGKILL);
      Compiler_report_error(c, 27335838, String_printf(_9, "this meta call ran longer than ", limit), site, cons(String_var(String_join(NULL, cons(String_var(_10), cons(String_var(name), NULL)))), _13));
    }
    if(! status) Compiler_report_error(c, 27335838, _83, site, cons(String_var(String_join(NULL, cons(String_var(_10), cons(String_var(name), NULL)))), cons(String_var(String_join(NULL, cons(String_var(_14), cons(String_var(_helper_ending()), NULL)))), NULL)));

  {
    List _x2c_match_expr = Var_list(reply);
    Var _x2c_match_values[2];
    MatchCaptureBuffer _x2c_match_capture = { .values = _x2c_match_values, .capacity = 2 };

    switch (Var_symbol(car(_x2c_match_expr))) {
      case 49497918350: ;
    { List _x2c_match_cursor;
    if (_x2c_match_expr && _x2c_match_expr->car.u64 == 9224497986259536782ULL && (_x2c_match_cursor = _x2c_match_expr->cdr, 1) && _x2c_match_cursor && Var_is(_x2c_match_cursor->car, 1318210446) && (_x2c_match_values[0] = _x2c_match_cursor->car, _x2c_match_cursor = _x2c_match_cursor->cdr, 1) && _x2c_match_cursor && Var_is(_x2c_match_cursor->car, 806120) && (_x2c_match_values[1] = _x2c_match_cursor->car, _x2c_match_cursor = _x2c_match_cursor->cdr, 1) && !_x2c_match_cursor) {Var message = _x2c_match_values[0];
    Var notes = _x2c_match_values[1];
    {
      Var _x2c_match_value_0 = message;
      Var _x2c_match_value_1 = notes;
      {
        String message = Var_string(_x2c_match_value_0);
        List notes = Var_list(_x2c_match_value_1);
        Compiler_report_warning(c, 27335838, message, site, notes);
      }

    }
    break; } } case 46228810: ;
    { List _x2c_match_cursor;
    if (_x2c_match_expr && _x2c_match_expr->car.u64 == 9224497936807847242ULL && (_x2c_match_cursor = _x2c_match_expr->cdr, 1) && _x2c_match_cursor && (_x2c_match_values[0] = _x2c_match_cursor->car, _x2c_match_cursor = _x2c_match_cursor->cdr, 1) && !_x2c_match_cursor) {Var value = _x2c_match_values[0];
    return value;
    break; } } case 1473096: ;
    { List _x2c_match_cursor;
    if (_x2c_match_expr && _x2c_match_expr->car.u64 == 9224497936763091528ULL && (_x2c_match_cursor = _x2c_match_expr->cdr, 1) && !_x2c_match_cursor) {return((void) 0, Void);
    break; } } case 11703268: ;
    { List _x2c_match_cursor;
    if (_x2c_match_expr && _x2c_match_expr->car.u64 == 9224497936773321700ULL && (_x2c_match_cursor = _x2c_match_expr->cdr, 1) && _x2c_match_cursor && Var_is(_x2c_match_cursor->car, 1318210446) && (_x2c_match_values[0] = _x2c_match_cursor->car, _x2c_match_cursor = _x2c_match_cursor->cdr, 1) && _x2c_match_cursor && Var_is(_x2c_match_cursor->car, 806120) && (_x2c_match_values[1] = _x2c_match_cursor->car, _x2c_match_cursor = _x2c_match_cursor->cdr, 1) && !_x2c_match_cursor) {Var message = _x2c_match_values[0];
    Var notes = _x2c_match_values[1];
    {
      Var _x2c_match_value_2 = message;
      Var _x2c_match_value_3 = notes;
      {
        String message = Var_string(_x2c_match_value_2);
        List notes = Var_list(_x2c_match_value_3);
        Compiler_report_error(c, 27335838, message, site, notes);
      }

    }
    break; } } case 293581290303730: ;
    { List _x2c_match_cursor;
    if (_x2c_match_expr && _x2c_match_expr->car.u64 == 9224791518051922162ULL && (_x2c_match_cursor = _x2c_match_expr->cdr, 1) && _x2c_match_cursor && Var_is(_x2c_match_cursor->car, 1318210446) && (_x2c_match_values[0] = _x2c_match_cursor->car, _x2c_match_cursor = _x2c_match_cursor->cdr, 1) && _x2c_match_cursor && Var_is(_x2c_match_cursor->car, 1318210446) && (_x2c_match_values[1] = _x2c_match_cursor->car, _x2c_match_cursor = _x2c_match_cursor->cdr, 1) && !_x2c_match_cursor) {Var path = _x2c_match_values[0];
    Var hash = _x2c_match_values[1];
    {
      Var _x2c_match_value_4 = path;
      Var _x2c_match_value_5 = hash;
      {
        String path = Var_string(_x2c_match_value_4);
        String hash = Var_string(_x2c_match_value_5);
        Map_merge_translation_dependency(c -> deps, path, String_var(hash));
      }

    }
    break; } } case 28562377614: ;
    { List _x2c_match_cursor;
    if (_x2c_match_expr && _x2c_match_expr->car.u64 == 9224497965323996046ULL && (_x2c_match_cursor = _x2c_match_expr->cdr, 1) && !_x2c_match_cursor) {Compiler_refuse_meta_call(c, name, site, Compiler_meta_call_missing(c, name));
    break; } } case 12971715722: ;
    static MatchCaptureSite _x2c_match_site_0;
    if (x2c_match_site_try_capture(& _x2c_match_site_0, _x2c_match_expr, List_var(_75), &_x2c_match_capture)) {Var code = _x2c_match_values[0];  List detail = Var_list(_x2c_match_values[1]);  Error_raise(Var_symbol(code), detail);  break;
  }
  default: ;  Compiler_report_error(c, 27335838, _83, site, cons(String_var(String_join(NULL, cons(String_var(_10), cons(String_var(name), NULL)))), _78));  break;
    }
  }
}
}

void Buffer_cleanup(Buffer);
static void _x2c_defer_cleanup_0(void * _x2c_defer_opaque_0){
  _x2c_defer_env_0 * _x2c_defer_data_0 =(_x2c_defer_env_0 *) _x2c_defer_opaque_0;  Buffer_cleanup((*(Buffer *) _x2c_defer_data_0->_x2c_defer_capture_0));
}

#undef _x2c_initializer_choice_B1CED777_0_expanded
#undef _x2c_initializer_choice_B1CED777_0
#undef _x2c_initializer_choice_B1CED777_1_expanded
#undef _x2c_initializer_choice_B1CED777_1
#undef _x2c_initializer_choice_B1CED777_2_expanded
#undef _x2c_initializer_choice_B1CED777_2
#undef _x2c_initializer_choice_B1CED777_3_expanded
#undef _x2c_initializer_choice_B1CED777_3
#undef _x2c_initializer_choice_B1CED777_4_expanded
#undef _x2c_initializer_choice_B1CED777_4
#undef _x2c_initializer_choice_B1CED777_5_expanded
#undef _x2c_initializer_choice_B1CED777_5
#undef _x2c_initializer_choice_B1CED777_6_expanded
#undef _x2c_initializer_choice_B1CED777_6
#undef _x2c_initializer_choice_B1CED777_7_expanded
#undef _x2c_initializer_choice_B1CED777_7
#undef _x2c_initializer_choice_B1CED777_8_expanded
#undef _x2c_initializer_choice_B1CED777_8
#undef _x2c_initializer_choice_B1CED777_9_expanded
#undef _x2c_initializer_choice_B1CED777_9
#undef _x2c_initializer_choice_B1CED777_10_expanded
#undef _x2c_initializer_choice_B1CED777_10
