/* auto-generated by x2c.  Do not edit! */

#pragma once

#ifndef __GUARD_0x46021D32__
#define __GUARD_0x46021D32__

#include "x2c.h"
#include "compiler.h"
#include "type.h"
String Compiler_package_alias_spelling(Compiler c);

List Compiler_parse_complex_identifier(Compiler compiler);

List Compiler_parse_basic_identifier(Compiler compiler);

List Compiler_parse_optional_identifier(Compiler compiler);

List Compiler_parse_field(Compiler compiler,  List context);

List Compiler_parse_fields(Compiler c,  List context);

List Compiler_parse_enumerator(Compiler c,  Type context);

List Compiler_parse_enumerators(Compiler c,  List context);

Type Compiler_parse_type_name(Compiler compiler);

List Compiler_parse_parameter(Compiler compiler);

List Compiler_parse_parameter_list(Compiler c);

int Compiler_test_declaration(Compiler compiler);

List Compiler_parse_simple_declaration(Compiler compiler);

List Compiler_parse_declaration_row(Compiler compiler);

List Compiler_parse_declaration_argument(Compiler c);

List Compiler_parse_function_definition(Compiler compiler);

List Compiler_parse_function_target(Compiler compiler);

List Compiler_parse_import_declaration(Compiler c);

List Compiler_parse_top_level(Compiler c);

List Compiler_finish_foreign_alias(Compiler c,  List declaration,  List native_syntax);

List Compiler_bind_syntax(Compiler compiler,  Var syntax,  AstPos context,  Type return_type);


#endif /* __GUARD_0x46021D32__ */
