/* auto-generated by x2c.  Do not edit! */

#include "symbols.h"

#include "exception.h"

static List _30353, _30350, _30347, _30346, _30344, _30342, _30341, _30340, _30339, _30337, _30336, _30335, _30333, _30331, _30329, _30328, _30326, _30325, _30323, _30322, _30321, _30320, _30317, _30316, _30315, _30314, _30313, _30312, _30310, _30308, _30307, _30306, _30304, _30303, _30302, _30300, _30299, _30298, _30296, _30295, _30292, _30291, _30283, _30278, _30276, _30275, _30272, _30270, _30269, _30267, _30265, _30263, _30262, _30250, _30249, _30248, _30246, _30245, _30244, _30242, _30239, _30238, _30235, _30234, _30233, _30225, _30224, _30221, _30219, _30217, _30216, _30215, _2533, _1554, _379, _182, _94, _77;

static String _30362, _30361, _30360, _30359, _30358, _30357, _30356, _30355, _30354, _30348, _30286, _30285, _30284, _30251, _30222, _22574, _377;

static Var _30352, _30351, _30349, _30345, _30343, _30338, _30334, _30332, _30330, _30327, _30324, _30319, _30318, _30311, _30309, _30305, _30301, _30297, _30294, _30293, _30290, _30289, _30288, _30287, _30282, _30281, _30280, _30279, _30277, _30271, _30268, _30266, _30264, _30252, _30247, _30243, _30241, _30240, _30237, _30236, _30232, _30231, _30230, _30229, _30228, _30227, _30226, _30223, _30220, _30218, _30214, _20887, _4078, _3073, _2532, _2491, _2490, _2489, _2488, _1553, _1249, _381, _378, _181, _146, _140, _93, _76;

static int _init_guard_ = 0;

__attribute__((constructor, noinline, cold)) static void _file_init_(void);

static SymScope * Sym__scope_at(Sym s, int index);

static void Sym__clear_symbols(Sym s, Map globals, int base_scopes);

static void Sym__push_symbols(Sym s, Map symbols);

static int _unseen(Map seen, Var name);

static Symbol _macro_kind(Var definition);

static int _retained_member(List key);

static void _seed_var_tag(List key, List type);

static String _var_converter_owner(List key, List type);

static List Sym__scope_binding(Sym s, SymScope * scope, List key);

static void Sym__note_source_key(Sym s, SymScope * scope, List key, List binding);

static List Sym__new_binding(Sym s, List key);

static List Sym__package_retry_key(Sym s, List key);

static List Sym__lookup_from(Sym s, List key, Type * type, int first, int forward);

static List Sym__package_declared_key(Sym s, List context, List key, List ast);

static String _declared_spelling(List key);

static void Compiler__check_spelling(Compiler c, String spelling);

static int _is_reserved_spelling(String s);

static String Compiler__package_reserved_owner(Compiler c, String spelling);

static void Sym__track_static(Sym s, List key, List ast);

static Type _stored_type(Type type, Type key, List ast);

static void Sym__local_typedef(Sym s, Type type, List binding);

static void Sym__local_object(Sym s, List key, List binding, Type type);

static void Sym__mark_automatic(Sym s, List binding, Type type);

static void Compiler__record_rows_visibility(Compiler c, List declaration, Symbol kind, int private, int mark, List rows);

static void _record_declaration_binding_visibility(Compiler c, List declaration, Symbol kind, int private, int mark, List identity);

static void Compiler__check_package_binding(Compiler c, String kind, String local, Token token);

#define RESOLVE_KEY_MAX_TYPEDEFS 64
#define RESOLVE_KEY_MAX_HOPS (2 * RESOLVE_KEY_MAX_TYPEDEFS)
static Type Sym__resolve_chain(Sym s, Type key, Type stop, Type origin, int hops);

static void Sym__typedef_budget_error(Sym s, Type origin);

static Type Sym__typedef_target(Sym s, Type key);

static Type Sym__normalize_chain(Sym s, Type type, Type origin, int hops);

static Type Sym__typedef_base_step(Sym s, Type type);

static Type _replace_type_base(Type type, Type base, Type replacement);

static Type Sym__local_tag(Sym s, Type type, Type base);

static Type Sym__local_alias(Sym s, Type type, Type base);

static Type _builtin_typedef_scalar(Type key);

static Symbol Sym__var_tag_chain(Sym s, Type type, Type origin, Type * resolved, int hops);

static List Sym__field_row(Sym s, Type type, List declaration, List declarator);

static void SymTxn__save(SymTxn s, SymScope scope);

static void SymTxn__save_effects(SymTxn s);

static void SymTxn__save_sources(SymTxn s);

static void SymTxn__stage(SymTxn s, SymScope * scope);

static void Compiler__merge_scope(Compiler c, SymScope * scope, SymScope staged);

static void SymTxn__commit_effects(SymTxn s);

static void _replace_map(Map original, Map staged);

static void SymTxn__restore(SymTxn s);

static void SymTxn__restore_effects(SymTxn s);

static void SymTxn__restore_sources(SymTxn s);

typedef struct _x2c_defer_env_0{
  const void * _x2c_defer_capture_0;
}
_x2c_defer_env_0;

static void _x2c_defer_cleanup_0(void * _x2c_defer_opaque_0);

Var Symbol_var(Symbol);

List cons(Var, List);

Var String_var(String);

Var List_var(List);

__attribute__((constructor, noinline, cold)) static void _file_init_(void){
  x2c_initialize_protocols();
  if(_init_guard_) return;
  _init_guard_ = 1;
  _76 = Symbol_var(58);
  _77 = cons(_76, NULL);
  _93 = Symbol_var(54);
  _94 = cons(_93, NULL);
  _140 = Symbol_var(39266);
  _146 = Symbol_var(992);
  _181 = Symbol_var(213092);
  _182 = cons(_181, NULL);
  _377 = String_new("Var");
  _378 = String_var(_377);
  _379 = cons(_378, NULL);
  _381 = Symbol_var(437126);
  _1249 = Symbol_var(61737802);
  _1553 = Symbol_var(65112065723278);
  _1554 = cons(_1553, NULL);
  _2488 = Symbol_var(8932560010);
  _2489 = Symbol_var(157714837990);
  _2490 = Symbol_var(123);
  _2491 = Symbol_var(150408);
  _2532 = Symbol_var(19368);
  _2533 = cons(_2532, NULL);
  _3073 = Symbol_var(62180362);
  _4078 = Symbol_var(61557640);
  _20887 = Symbol_var(1362954);
  _22574 = String_new(".");
  _30214 = Symbol_var(1318210446);
  _30215 = cons(_30214, NULL);
  _30216 = cons(_20887, _30215);
  _30217 = cons(_1249, _30216);
  _30218 = Symbol_var(62054);
  _30219 = cons(_30218, _30217);
  _30220 = List_var(_30219);
  _30221 = cons(_30220, NULL);
  _30222 = String_new("Sym.set");
  _30223 = String_var(_30222);
  _30224 = cons(_30223, NULL);
  _30225 = cons(_381, _30224);
  _30226 = List_var(_30225);
  _30227 = Symbol_var(22898);
  _30228 = Symbol_var(45144);
  _30229 = Symbol_var(2632321256);
  _30230 = Symbol_var(62436);
  _30231 = Symbol_var(1318234344);
  _30232 = Symbol_var(44977116);
  _30233 = cons(_30232, NULL);
  _30234 = cons(_30231, _30233);
  _30235 = cons(_30230, _30234);
  _30236 = List_var(_30235);
  _30237 = Symbol_var(4928588686);
  _30238 = cons(_76, _77);
  _30239 = cons(_30237, _30238);
  _30240 = List_var(_30239);
  _30241 = Symbol_var(481205850);
  _30242 = cons(_30241, _30238);
  _30243 = List_var(_30242);
  _30244 = cons(_30243, NULL);
  _30245 = cons(_30240, _30244);
  _30246 = cons(_30230, _30245);
  _30247 = List_var(_30246);
  _30248 = cons(_76, _94);
  _30249 = cons(_30247, _30248);
  _30250 = cons(_30236, _30249);
  _30251 = String_new("_var");
  _30252 = Symbol_var(1975609672);
  _30262 = cons(_30252, _30216);
  _30263 = cons(_30218, _30262);
  _30264 = List_var(_30263);
  _30265 = cons(_30264, NULL);
  _30266 = List_var(_30265);
  _30267 = cons(_30266, NULL);
  _30268 = List_var(_30267);
  _30269 = cons(_30268, NULL);
  _30270 = cons(_381, _30269);
  _30271 = List_var(_30270);
  _30272 = cons(_30271, _379);
  _30275 = cons(_1553, _30216);
  _30276 = cons(_30218, _30275);
  _30277 = List_var(_30276);
  _30278 = cons(_30277, NULL);
  _30279 = Symbol_var(24018396);
  _30280 = Symbol_var(1256204);
  _30281 = Symbol_var(42018494834);
  _30282 = Symbol_var(44661285196);
  _30283 = cons(_30282, NULL);
  _30284 = String_new("_init_guard_");
  _30285 = String_new("_file_init_");
  _30286 = String_new("__");
  _30287 = Symbol_var(30723082);
  _30288 = Symbol_var(11630059848);
  _30289 = Symbol_var(3686115942982);
  _30290 = Symbol_var(57834982);
  _30291 = cons(_30290, NULL);
  _30292 = cons(_140, _30291);
  _30293 = Symbol_var(458361162716);
  _30294 = Symbol_var(64399105871154);
  _30295 = cons(_30294, _94);
  _30296 = cons(_2491, _30295);
  _30297 = List_var(_30296);
  _30298 = cons(_30297, _94);
  _30299 = cons(_3073, _30298);
  _30300 = cons(_30293, _30299);
  _30301 = Symbol_var(2005352);
  _30302 = cons(_2488, NULL);
  _30303 = cons(_30282, _30302);
  _30304 = cons(_30230, _30303);
  _30305 = List_var(_30304);
  _30306 = cons(_30305, NULL);
  _30307 = cons(_4078, _30306);
  _30308 = cons(_30301, _30307);
  _30309 = List_var(_30308);
  _30310 = cons(_2489, _30291);
  _30311 = List_var(_30310);
  _30312 = cons(_30311, NULL);
  _30313 = cons(_3073, _30312);
  _30314 = cons(_30309, _30313);
  _30315 = cons(_30297, _77);
  _30316 = cons(_2490, _30315);
  _30317 = cons(_146, _30316);
  _30318 = Atom_intern(String_new("local-macro-capture"));
  _30319 = Symbol_var(836963110);
  _30320 = cons(_30319, NULL);
  _30321 = cons(_30236, NULL);
  _30322 = cons(_4078, _30321);
  _30323 = cons(_30301, _30322);
  _30324 = List_var(_30323);
  _30325 = cons(_76, _1554);
  _30326 = cons(_30237, _30325);
  _30327 = List_var(_30326);
  _30328 = cons(_30327, NULL);
  _30329 = cons(_30324, _30328);
  _30330 = Symbol_var(1474468213064);
  _30331 = cons(_30330, _182);
  _30332 = Symbol_var(1294430536);
  _30333 = cons(_30332, _182);
  _30334 = Symbol_var(40402088);
  _30335 = cons(_30334, NULL);
  _30336 = cons(_30330, _30335);
  _30337 = cons(_30330, NULL);
  _30338 = Symbol_var(818062);
  _30339 = cons(_30338, NULL);
  _30340 = cons(_30330, _30339);
  _30341 = cons(_30338, _30339);
  _30342 = cons(_30330, _30341);
  _30343 = Symbol_var(13400168);
  _30344 = cons(_30343, NULL);
  _30345 = Symbol_var(301273866);
  _30346 = cons(_30345, NULL);
  _30347 = cons(_30338, _30346);
  _30348 = String_new("field-order");
  _30349 = String_var(_30348);
  _30350 = cons(_30349, NULL);
  _30351 = Symbol_var(421880102);
  _30352 = Symbol_var(286431579402);
  _30353 = cons(_30352, NULL);
  _30354 = String_new("_x2c_");
  _30355 = String_new("local_typedef");
  _30356 = String_new("var_converter_shadow");
  _30357 = String_new("alias");
  _30358 = String_new("name");
  _30359 = String_new("Var");
  _30360 = String_new("String");
  _30361 = String_new("Array");
  _30362 = String_new("Map");
}

void * Scope_calloc(size_t, size_t);

Map Map_new(void);

Block Block_new(size_t);

Sym Sym_new(Compiler c){
  Sym s = Scope_calloc(1, sizeof(struct Sym));
  s -> c = c;
  s -> binding_facts = Map_new();
  s -> scopes = Block_new(sizeof(SymScope));
  s -> statics = Map_new();
  return s;
}

size_t Block_len(Block);

static SymScope * Sym__scope_at(Sym s, int index){
  int count = Block_len(s -> scopes);
  if(index < 0) index += count;
  if(index < 0 || index >= count) return NULL;
  SymScope * scopes = s -> scopes -> bytes;
  return scopes + index;
}

void Sym_reset(Sym s, Map globals){
  Sym__clear_symbols(s, globals, 1);
  Sym__push_symbols(s, s -> globals);
}

void Sym_reset_overlay(Sym s, Map base, Map overlay){
  Sym__clear_symbols(s, overlay, 2);
  Sym__push_symbols(s, base != NULL ? base : Map_new());
  Sym__push_symbols(s, s -> globals);
}

void Block_clear(Block);

static void Sym__clear_symbols(Sym s, Map globals, int base_scopes){
  Block_clear(s -> scopes);
  s -> globals = globals != NULL ? globals : Map_new();
  s -> statics = Map_new();
  s -> base_scopes = base_scopes;
  s -> local_macro_names = 0;
  s -> binding_facts = Map_new();
}

void Block_push(Block, const void *);

static void Sym__push_symbols(Sym s, Map symbols){
  struct SymScope scope ={
    .symbols = symbols, .bindings = Map_new(), .enumerators = Map_new()
  }
  ;
  Block_push(s -> scopes, & scope);
}

void Sym_push_new_scope(Sym s){
  Sym__push_symbols(s, Map_new());
}

void Sym_push_scope(Sym s, SymScope scope){
  Block_push(s -> scopes, & scope);
}

int Block_try_pop(Block, void *);

unsigned Map_len(Map);

SymScope Sym_pop_scope(Sym s){
  struct SymScope scope ={
    0
  }
  ;
  Block_try_pop(s -> scopes, & scope);
  if(scope.macros != NULL) s -> local_macro_names -= Map_len(scope.macros);
  return scope;
}

int Sym_scope_count(Sym s){
  return Block_len(s -> scopes);
}

int Sym_at_file_scope(Sym s){
  return(int) Block_len(s -> scopes) <= s -> base_scopes;
}

Map Sym_global_symbols(Sym s){
  return s -> globals;
}

Map Map_merge(Map, Map);

Map Sym_base_symbols(Sym s){
  Map seed = Map_new();
  for(int i = 0;  i < s -> base_scopes;  i ++) Map_merge(seed, Sym__scope_at(s, i) -> symbols);
  return seed;
}

Map Sym_current_symbols(Sym s){
  SymScope * scope = Sym__scope_at(s, - 1);
  return scope ? scope -> symbols : NULL;
}

int Map_truth(Map);

Map Sym_unit_symbols(Sym s){
  Map symbols = Sym_base_symbols(s);
  Map current = Sym_current_symbols(s);
  if(Map_truth(current)) Map_merge(symbols, current);
  return symbols;
}

Map Sym_file_statics(Sym s){
  return s -> statics;
}

Var Map_setindex(Map, Var, Var);

Var int_var(int);

void Sym_mark_static(Sym s, List key){
  Map_setindex(s -> statics, List_var(key), int_var(1));
}

Array Array_new(void);

int Map_try_next(Map, unsigned *, Var *, Var *);

List Var_list(Var);

String Var_string(Var);

Var Array_push(Array, Var);

int Var_is_row(Var, unsigned, unsigned long, unsigned long);

List Array_list_free(Array);

List Sym_visible_symbols(Sym s){
  if(! _init_guard_) _file_init_();
  Map seen = Map_new();
  Array rows = Array_new();
  for(int i =(int) Block_len(s -> scopes) - 1;  i >= 0;  i --){
    SymScope * scope = Sym__scope_at(s, i);
    {
      Var key, value;
      Map _x2c_macro_object_0 = scope -> symbols;
      unsigned _x2c_macro_cursor_0 = 0;
      Var _x2c_macro_cursor_output_0;
      Var _x2c_macro_cursor_output_1;
      while(Map_try_next(_x2c_macro_object_0, &(_x2c_macro_cursor_0), &(_x2c_macro_cursor_output_0), &(_x2c_macro_cursor_output_1))){
        key = _x2c_macro_cursor_output_0;
        value = _x2c_macro_cursor_output_1;

  {
    List _x2c_match_expr = Var_list(key);
    Var _x2c_match_values[1];
        MatchCaptureBuffer _x2c_match_capture = { .values = _x2c_match_values, .capacity = 1 };

    switch (0) {
      default: ;  static MatchCaptureSite _x2c_match_site_0;  if (x2c_match_site_try_capture(& _x2c_match_site_0, _x2c_match_expr, List_var(_30221), &_x2c_match_capture)) {Var name = _x2c_match_values[0]; {
          Var _x2c_match_value_0 = name; {
            String name = Var_string(_x2c_match_value_0);  if(_unseen(seen, String_var(name))) Array_push(rows, List_var(cons(String_var(name), cons(value, NULL))));
          }

        }
        break;
      }

    }
  }
    }

  }
  if(scope -> macros != NULL){
    Var name, definition;  Map _x2c_macro_object_1 = scope -> macros;  unsigned _x2c_macro_cursor_1 = 0;  Var _x2c_macro_cursor_output_2;  Var _x2c_macro_cursor_output_3;  while(Map_try_next(_x2c_macro_object_1, &(_x2c_macro_cursor_1), &(_x2c_macro_cursor_output_2), &(_x2c_macro_cursor_output_3))){
      name = _x2c_macro_cursor_output_2;  definition = _x2c_macro_cursor_output_3;  if(Var_is_row(name, 11, 7, 1) && _unseen(seen, name)) Array_push(rows, List_var(cons(name, cons(Symbol_var(_macro_kind(definition)), NULL))));
    }

  }

}
return Array_list_free(rows);
}

int Map_contains(Map, Var);
static int _unseen(Map seen, Var name){
  if(Map_contains(seen, name)) return 0;  Map_setindex(seen, name, int_var(1));  return 1;
}

Var List_assoc(List, Var);
static Symbol _macro_kind(Var definition){
  Symbol kind = Var_symbol(Var_is_row(definition, 9, 7, 4) ? List_assoc(Var_list(definition), Symbol_var(740232)) : int_var(0));  return kind == 1362954 ? 45733174647966 : 27335838;
}

int log_should_log(Symbol, Symbol);
void log_debug(Symbol, List);
void Sym_set(Sym s, List key, List type){
  if(! _init_guard_) _file_init_();  Map scope = Sym__scope_at(s, - 1) -> symbols;  if(log_should_log(8721742, 1328390212)) log_debug(1328390212, cons(_30226, cons(List_var(cons(_30227, cons(List_var(key), NULL))), cons(List_var(cons(_30228, cons(List_var(type), NULL))), NULL))));  Map_setindex(scope, List_var(key), List_var(type));  if(_retained_member(key)) Map_setindex(s -> binding_facts, List_var(cons(_30229, cons(List_var(key), NULL))), List_var(type));
}

int List_truth(List);
List List_match(List, Var);
static int _retained_member(List key){
  return ! ! List_truth(({ static MatchCaptureSite _x2c_match_site_1;  x2c_match_site_match(& _x2c_match_site_1, key, List_var(_30250)); }));
}

List Sym_define(Sym s, List key, List type){
  if(! _init_guard_) _file_init_();  SymScope * scope = Sym__scope_at(s, - 1);  Sym_set(s, key, type);  _seed_var_tag(key, type);  return Sym__scope_binding(s, scope, key);
}

int String_truth(String);
Type List_type(List);
void Type_register_var_tag(Type, String, String);
static void _seed_var_tag(List key, List type){
  String owner = _var_converter_owner(key, type);  if(! String_truth(owner)) return;  String converter = String_join(NULL, cons(String_var(owner), cons(String_var(_30251), NULL)));  Type declared = List_type(cons(String_var(owner), NULL));  Type_register_var_tag(declared, owner, converter);
}

int String_equal(String, String);
static String _var_converter_owner(List key, List type){

  {
    List _x2c_match_expr = type;
    Var _x2c_match_values[1];  MatchCaptureBuffer _x2c_match_capture = { .values = _x2c_match_values, .capacity = 1 };
    switch (0) {
      default: ;  static MatchCaptureSite _x2c_match_site_3;  if (x2c_match_site_try_capture(& _x2c_match_site_3, _x2c_match_expr, List_var(_30272), &_x2c_match_capture)) {Var named = _x2c_match_values[0]; {
    Var _x2c_match_value_1 = named; {
      String named = Var_string(_x2c_match_value_1);
  {
    List _x2c_match_expr = key;
    Var _x2c_match_values[1];  MatchCaptureBuffer _x2c_match_capture = { .values = _x2c_match_values, .capacity = 1 };
    switch (0) {
      default: ;  static MatchCaptureSite _x2c_match_site_2;  if (x2c_match_site_try_capture(& _x2c_match_site_2, _x2c_match_expr, List_var(_30278), &_x2c_match_capture)) {Var spelling = _x2c_match_values[0]; {
        Var _x2c_match_value_2 = spelling; {
          String spelling = Var_string(_x2c_match_value_2);  return String_equal(spelling, String_join(NULL, cons(String_var(named), cons(String_var(_30251), NULL)))) ? named : NULL;
        }

      }
      break;
    }

    }
  }
  }

}
break;
}

    }
  }
return NULL;
}

void Sym_seed_var_tags(Sym s, Map symbols){
  if(! _init_guard_) _file_init_();  if(! Map_truth(symbols)) return; {
    Var key, type;  Map _x2c_macro_object_2 = symbols;  unsigned _x2c_macro_cursor_2 = 0;  Var _x2c_macro_cursor_output_4;  Var _x2c_macro_cursor_output_5;  while(Map_try_next(_x2c_macro_object_2, &(_x2c_macro_cursor_2), &(_x2c_macro_cursor_output_4), &(_x2c_macro_cursor_output_5))){
      key = _x2c_macro_cursor_output_4;  type = _x2c_macro_cursor_output_5;  if(Var_is_row(key, 9, 7, 4) && Var_is_row(type, 9, 7, 4)) _seed_var_tag(Var_list(key), Var_list(type));
    }

  }

}

void Sym_define_global(Sym s, List key, List type){
  if(! _init_guard_) _file_init_();  SymScope * scope = Sym__scope_at(s, s -> base_scopes - 1);  Map_setindex(scope -> symbols, List_var(key), List_var(type));  _seed_var_tag(key, type);
}

void Sym_declare_enumerator(Sym s, List key, Symbol owner){
  SymScope * scope = Sym__scope_at(s, - 1);  if(scope) Map_setindex(scope -> enumerators, List_var(key), Symbol_var(owner));
}

int Map_try_get(Map, Var, Var *);
Var List_getindex(List, int);
static List Sym__scope_binding(Sym s, SymScope * scope, List key){
  Var found;  List binding;  if(Map_try_get(scope -> bindings, List_var(key), &(found))) binding = Var_list(found);  else{
    binding = Sym__new_binding(s, key);  Map_setindex(scope -> bindings, List_var(key), List_var(binding));
  }
  List _x2c_destructure_0 = binding;  Var binding_tag = List_getindex(_x2c_destructure_0, 0);  int identity = Var_int(Var_convert(List_getindex(_x2c_destructure_0, 1), 3453797));  String spelling = Var_string(List_getindex(_x2c_destructure_0, 2)); (void) binding_tag;  if(! Map_contains(s -> binding_facts, List_var(cons(_30279, cons(int_var(identity), NULL))))) Map_setindex(s -> binding_facts, List_var(cons(_30279, cons(int_var(identity), NULL))), String_var(spelling));  List self_key = cons(_30280, cons(List_var(binding), NULL));  if(! Map_contains(s -> binding_facts, List_var(self_key))){
    Var relative;  if(Map_try_get(scope -> symbols, List_var(cons(_30280, cons(String_var(spelling), NULL))), &(relative))) Map_setindex(s -> binding_facts, List_var(self_key), relative);
  }
  if(s -> c -> source_facts) Sym__note_source_key(s, scope, key, binding);  return binding;
}

Var Map_var(Map);
static void Sym__note_source_key(Sym s, SymScope * scope, List key, List binding){
  Compiler c = s -> c;  List source_key = cons(Map_var(scope -> symbols), cons(List_var(key), NULL));  Map_setindex(s -> binding_facts, List_var(cons(_30281, cons(List_var(binding), NULL))), List_var(source_key));  Var declaration;  if(c -> source_primary && ! c -> shallow && Map_try_get(c -> source_declarations, List_var(source_key), &(declaration))) Map_setindex(c -> source_definitions, List_var(binding), declaration);
}

Var List_last(List);
List binding_identity_new(int, String);
static List Sym__new_binding(Sym s, List key){
  int identity = ++ s -> c -> names -> next_binding;  Var name = List_last(key);  List binding = binding_identity_new(identity, Var_string(name));  Map_setindex(s -> binding_facts, List_var(cons(_30279, cons(int_var(identity), NULL))), name);  return binding;
}

List Sym_introduce(Sym s, String spelling){
  if(! _init_guard_) _file_init_();  return Sym__new_binding(s, cons(String_var(spelling), NULL));
}

List Sym_current_binding(Sym s, List key){
  SymScope * scope = Sym__scope_at(s, - 1);  Var binding;  return scope && Map_try_get(scope -> bindings, List_var(key), &(binding)) ? Var_list(binding) : NULL;
}

Symbol Sym_enumerator_owner(Sym s, List key){
  SymScope * scope = Sym__scope_at(s, - 1);  Var owner;  return Var_symbol(scope && Map_try_get(scope -> enumerators, List_var(key), &(owner)) ? owner : int_var(0));
}

int Sym_binding_is_local(Sym s, List binding){
  return Sym_binding_is_local_before(s, binding, Block_len(s -> scopes));
}

int List_equal(List, List);
int Sym_binding_is_local_before(Sym s, List binding, int scope_count){
  if(scope_count >(int) Block_len(s -> scopes)) scope_count = Block_len(s -> scopes);  for(int i = scope_count - 1;  i >= s -> base_scopes;  i --){
    Var _, candidate;  Map _x2c_macro_object_3 = Sym__scope_at(s, i) -> bindings;  unsigned _x2c_macro_cursor_3 = 0;  Var _x2c_macro_cursor_output_6;  Var _x2c_macro_cursor_output_7;  while(Map_try_next(_x2c_macro_object_3, &(_x2c_macro_cursor_3), &(_x2c_macro_cursor_output_6), &(_x2c_macro_cursor_output_7))){
      _ = _x2c_macro_cursor_output_6;  candidate = _x2c_macro_cursor_output_7;  if(List_equal(Var_list(candidate), binding)) return 1;
    }

  }
  return 0;
}

Map Compiler_semantic_binding_facts(Compiler c){
  return c -> sym -> binding_facts;
}

List Sym_get(Sym s, List key){
  if(! _init_guard_) _file_init_();  List found = Sym_get_exact(s, key);  if(List_truth(found)) return found;  List retry = Sym__package_retry_key(s, key);  return List_truth(retry) ? Sym_get_exact(s, retry) : NULL;
}

List Sym_get_exact(Sym s, List key){
  if(! _init_guard_) _file_init_();  Var val;  for(int i =(int) Block_len(s -> scopes) - 1;  i >= 0;  i --){
    Map scope = Sym__scope_at(s, i) -> symbols;  if(Map_try_get(scope, List_var(key), &(val))) return Var_list(val);
  }
  if(_retained_member(key) && Map_try_get(s -> binding_facts, List_var(cons(_30229, cons(List_var(key), NULL))), &(val))) return Var_list(val);  return NULL;
}

List List_cdr(List);
Var List_car(List);
static List Sym__package_retry_key(Sym s, List key){
  String package = s -> c -> package;  if(! String_truth(package) || ! List_truth(key) || List_truth(List_cdr(key)) || ! Var_is_row(List_car(key), 11, 7, 1)) return NULL;  String spelling = Var_string(List_car(key));  String prefixed = Compiler_package_spelling(s -> c, spelling);  return String_equal(prefixed, spelling) ? NULL : cons(String_var(prefixed), NULL);
}

List Sym_lookup(Sym s, List key, Type * type){
  if(! _init_guard_) _file_init_();  return Sym__lookup_from(s, key, type, (int) Block_len(s -> scopes) - 1, 0);
}

List Sym_reference(Sym s, List key, Type * type){
  if(! _init_guard_) _file_init_();  return Sym__lookup_from(s, key, type, (int) Block_len(s -> scopes) - 1, 1);
}

List Sym_resolve_global(Sym s, List key, Type * type){
  if(! _init_guard_) _file_init_();  return Sym__lookup_from(s, key, type, s -> base_scopes - 1, 0);
}

List Sym_reference_global(Sym s, List key){
  if(! _init_guard_) _file_init_();  List binding = Sym_resolve_global(s, key, NULL);  if(List_truth(binding)) return binding;  return Sym__scope_binding(s, Sym__scope_at(s, s -> base_scopes - 1), key);
}

Type Var_type(Var);
static List Sym__lookup_from(Sym s, List key, Type * type, int first, int forward){
  Var found;  for(int i = first;  i >= 0;  i --){
    SymScope * scope = Sym__scope_at(s, i);  if(Map_try_get(scope -> symbols, List_var(key), &(found))){
      if(type)(* type) = Var_type(found);  return Sym__scope_binding(s, scope, key);
    }
    if(Map_try_get(scope -> bindings, List_var(key), &(found))){
      if(type)(* type) = NULL;  return Var_list(found);
    }

  }
  List retry = Sym__package_retry_key(s, key);  if(List_truth(retry) &&(! forward || List_truth(Sym_get_exact(s, retry)))) return Sym__lookup_from(s, retry, type, first, forward);  if(type)(* type) = NULL;  return forward ? Sym__scope_binding(s, Sym__scope_at(s, - 1), key) : NULL;
}

Type List_type_from_ast(List);
List Type_list(Type);
List Sym_declare(Sym s, List context, List key, List ast){
  if(! _init_guard_) _file_init_();  if(String_truth(s -> c -> package)) key = Sym__package_declared_key(s, context, key, ast);  Compiler__check_spelling(s -> c, _declared_spelling(key));  Type ctxkey = List_type(List_append(context, List_append(key, NULL))), type = List_type_from_ast(ast);  Type declared_type = type;  if((int) Block_len(s -> scopes) == s -> base_scopes && ! List_truth(context)) Sym__track_static(s, (List) ctxkey, ast);  List binding = NULL;  if(context == _30283) binding = Sym_define(s, key, (List) ctxkey);  type = _stored_type(type, ctxkey, ast);  if(! List_truth(binding)) binding = Sym_define(s, Type_list(ctxkey), (List) type);  else{
    Sym_set(s, Type_list(ctxkey), (List) type);  Sym__local_typedef(s, type, binding);
  }
  if(! List_truth(context) && ! Sym_at_file_scope(s)) Sym__local_object(s, key, binding, declared_type);  return binding;
}

int Type_is_static(Type);
List List_cddr(List);
static List Sym__package_declared_key(Sym s, List context, List key, List ast){
  Compiler c = s -> c;  if((int) Block_len(s -> scopes) != s -> base_scopes) return key;  if(List_truth(context) && !(context == _30283)) return key;  if(Type_is_static(List_type(ast))) return key;  Var head, tag;  List _x2c_destructure_1 = key;  head = List_getindex(_x2c_destructure_1, 0);  tag = List_getindex(_x2c_destructure_1, 1);  if(Var_is_row(head, 11, 7, 1) && ! List_truth(List_cdr(key))) return cons(String_var(Compiler_package_spelling(c, Var_string(head))), NULL);  if((Var_equal(head, Symbol_var(1318234344)) || Var_equal(head, Symbol_var(44977116)) || Var_equal(head, Symbol_var(357722))) && List_truth(List_cdr(key)) && ! List_truth(List_cddr(key)) && Var_is_row(tag, 11, 7, 1)) return cons(head, cons(String_var(Compiler_package_spelling(c, Var_string(tag))), NULL));  return key;
}

static String _declared_spelling(List key){
  Var head, tag;  List _x2c_destructure_2 = key;  head = List_getindex(_x2c_destructure_2, 0);  tag = List_getindex(_x2c_destructure_2, 1);  if(Var_is_row(head, 11, 7, 1)) return Var_string(head);  if(Var_equal(head, Symbol_var(1318234344)) || Var_equal(head, Symbol_var(44977116)) || Var_equal(head, Symbol_var(357722))) if(Var_is_row(tag, 11, 7, 1)) return Var_string(tag);  return NULL;
}

void Compiler_report_error(Compiler, Symbol, String, Token, List);
static void Compiler__check_spelling(Compiler c, String spelling){
  if(! c -> shallow && _is_reserved_spelling(spelling)){
    Compiler_report_error(c, 33658058, String_join(NULL, cons(String_var(String_new("\'")), cons(String_var(spelling), cons(String_var(String_new("\' is reserved for compiler-generated names")), NULL)))), c -> token, NULL);
  }
  String owner = Compiler__package_reserved_owner(c, spelling);  if(String_truth(owner)) Compiler_report_error(c, 33658058, String_join(NULL, cons(String_var(String_new("\'")), cons(String_var(spelling), cons(String_var(String_new("\' is reserved for imported package \'")), cons(String_var(owner), cons(String_var(String_new("\'")), NULL)))))), c -> token, NULL);
}

int String_startswith(String, String);
int String_len(String);
int String_getindex(String, int);
static int _is_reserved_spelling(String s){
  if(! String_truth(s)) return 0;  if(String_startswith(s, _30354) || String_equal(s, _30284) || String_equal(s, _30285)) return 1;  if(String_len(s) < 2 || String_getindex(s, 0) != '_') return 0;  for(int i = 1;  i < String_len(s);  i ++) if(String_getindex(s, i) < '0' || String_getindex(s, i) > '9') return 0;  return 1;
}

static String Compiler__package_reserved_owner(Compiler c, String spelling){
  if(! String_truth(spelling) || ! Map_len(c -> package_aliases)) return NULL; {
    Var alias, value;  Map _x2c_macro_object_4 = c -> package_aliases;  unsigned _x2c_macro_cursor_4 = 0;  Var _x2c_macro_cursor_output_8;  Var _x2c_macro_cursor_output_9;  while(Map_try_next(_x2c_macro_object_4, &(_x2c_macro_cursor_4), &(_x2c_macro_cursor_output_8), &(_x2c_macro_cursor_output_9))){
      alias = _x2c_macro_cursor_output_8;  value = _x2c_macro_cursor_output_9; {
        String name = Var_string(value);  if(String_equal(name, c -> package)) continue;  if(String_startswith(spelling, String_join(NULL, cons(String_var(name), cons(String_var(_30286), NULL))))) return name;
      }

    }

  }
  return NULL;
}

Var Map_del(Map, Var);
static void Sym__track_static(Sym s, List key, List ast){
  if(Type_is_static(List_type(ast))) Map_setindex(s -> statics, List_var(key), int_var(1));  else Map_del(s -> statics, List_var(key));
}

int Type_is_aggregate_tag_body(Type);
int Type_is_aggregate_tag(Type);
Type Type_declared(Type);
static Type _stored_type(Type type, Type key, List ast){
  if(Type_is_aggregate_tag_body(type) && ! Type_is_aggregate_tag(key)){
    Var aggregate, tag;  List _x2c_destructure_3 = ast;  aggregate = List_getindex(_x2c_destructure_3, 0);  tag = List_getindex(_x2c_destructure_3, 1);  type = List_type(cons(aggregate, cons(tag, NULL)));
  }
  return Type_declared(type);
}

String Compiler_fresh_name(Compiler, String);
static void Sym__local_typedef(Sym s, Type type, List binding){
  if(Sym_at_file_scope(s)) return;  if(Type_is_aggregate_tag(type)) Map_setindex(s -> binding_facts, List_var(cons(_30287, cons(List_var(binding), NULL))), List_var(type));  Map_setindex(s -> binding_facts, List_var(cons(_30288, cons(List_var(binding), NULL))), String_var(Compiler_fresh_name(s -> c, _30355)));
}

static void Sym__local_object(Sym s, List key, List binding, Type type){
  Sym__mark_automatic(s, binding, type);  Type global_type = NULL;  Sym_resolve_global(s, key, &(global_type));  if(String_truth(_var_converter_owner(key, Type_list(global_type))) && ! Map_contains(s -> binding_facts, List_var(cons(_30288, cons(List_var(binding), NULL))))) Map_setindex(s -> binding_facts, List_var(cons(_30288, cons(List_var(binding), NULL))), String_var(Compiler_fresh_name(s -> c, _30356)));
}

static void Sym__mark_automatic(Sym s, List binding, Type type){
  Map_setindex(s -> binding_facts, List_var(cons(_30289, cons(List_var(binding), NULL))), int_var(1));  Map_setindex(s -> binding_facts, List_var(cons(_20887, cons(List_var(binding), NULL))), List_var(type));
}

String binding_identity_spelling(List);
List Sym_bind_identity(Sym s, List context, List binding, List ast){
  if(! _init_guard_) _file_init_();  String spelling = binding_identity_spelling(binding);  List key = List_truth(context) ? List_append(context, cons(String_var(spelling), NULL)) : cons(String_var(spelling), NULL);  SymScope * scope = Sym__scope_at(s, - 1);  Type annotation = List_type_from_ast(ast);  Map_setindex(scope -> symbols, List_var(key), List_var(Type_declared(annotation)));  if(context == _30283){
    key = cons(String_var(spelling), NULL);  Map_setindex(scope -> symbols, List_var(key), List_var(cons(_30282, cons(String_var(spelling), NULL))));  Sym__local_typedef(s, annotation, binding);
  }
  Map_setindex(scope -> bindings, List_var(key), List_var(binding));  if(! List_truth(context) && ! Sym_at_file_scope(s)) Sym__mark_automatic(s, binding, annotation);  return binding;
}

List Compiler_macro_tag_name(Compiler, Symbol, String, int);
Var List_cadr(List);
Var Compiler_aggregate_name(Compiler c, Symbol kind, Var name, int definition){
  if(! _init_guard_) _file_init_();  Sym s = c -> sym;  if(! Var_is_row(name, 11, 7, 1)) return name;  if(Map_truth(c -> macro_holes)){
    List local = Compiler_macro_tag_name(c, kind, Var_string(name), definition);  return List_truth(local) ? List_var(local) : name;
  }
  Type type = List_type(cons(Symbol_var(kind), cons(name, NULL)));  if(Sym_at_file_scope(s)){
    if(definition && ! List_truth(Sym_get_exact(s, Type_list(type)))) Sym_declare(s, NULL, Type_list(type), Type_list(type));  return name;
  }
  if(! definition && List_truth(Sym_get_exact(s, Type_list(type)))) return List_cadr(Type_list(Sym_local_type(s, type)));  if(! definition && c -> shallow) return name;  List binding = Sym_current_binding(s, Type_list(type));  return List_var(List_truth(binding) ? binding : Sym_declare(s, NULL, Type_list(type), Type_list(type)));
}

int List_try_next(List, List *, Var *);
void Compiler_record_declaration_visibility(Compiler c, List declaration){
  if(! _init_guard_) _file_init_();  int private = c -> source_private > 0;
  {
    List _x2c_match_expr = declaration;
    Var _x2c_match_values[3];  MatchCaptureBuffer _x2c_match_capture = { .values = _x2c_match_values, .capacity = 3 };
    switch (Var_symbol(car(_x2c_match_expr))) {
      case 39266: ;  static MatchCaptureSite _x2c_match_site_4;  if (x2c_match_site_try_capture(& _x2c_match_site_4, _x2c_match_expr, List_var(_30292), &_x2c_match_capture)) {List rows = Var_list(_x2c_match_values[0]); {
    List row;  List _x2c_macro_object_5 = rows;  List _x2c_macro_cursor_5 = _x2c_macro_object_5;  Var _x2c_macro_cursor_output_10;  while(List_try_next(_x2c_macro_object_5, &(_x2c_macro_cursor_5), &(_x2c_macro_cursor_output_10))){
      row = Var_list(_x2c_macro_cursor_output_10);  Compiler_record_declaration_visibility(c, row);
    }

  }
  break;
}
case 458361162716: ;  static MatchCaptureSite _x2c_match_site_5;  if (x2c_match_site_try_capture(& _x2c_match_site_5, _x2c_match_expr, List_var(_30300), &_x2c_match_capture)) {Var type = _x2c_match_values[0];  Var identity = _x2c_match_values[1]; {
  if(! private && ! Type_is_static(Var_type(type))) return;  String name = binding_identity_spelling(Var_list(identity));  if(String_truth(name)) Sym_mark_static(c -> sym, cons(String_var(name), NULL));
}
break;
}
default: ;  static MatchCaptureSite _x2c_match_site_6;  if (x2c_match_site_try_capture(& _x2c_match_site_6, _x2c_match_expr, List_var(_30314), &_x2c_match_capture)) {Var kind = _x2c_match_values[0];  Var type = _x2c_match_values[1];  List rows = Var_list(_x2c_match_values[2]); {
  int mark = private || Type_is_static(Var_type(type));  Compiler__record_rows_visibility(c, declaration, Var_symbol(kind), private, mark, rows);
}
break;
}

    }
  }
}

static void Compiler__record_rows_visibility(Compiler c, List declaration, Symbol kind, int private, int mark, List rows){
  {
    List row;  List _x2c_macro_object_6 = rows;  List _x2c_macro_cursor_6 = _x2c_macro_object_6;  Var _x2c_macro_cursor_output_11;  while(List_try_next(_x2c_macro_object_6, &(_x2c_macro_cursor_6), &(_x2c_macro_cursor_output_11))){
      row = Var_list(_x2c_macro_cursor_output_11);
  {
    List _x2c_match_expr = row;
    Var _x2c_match_values[1];  MatchCaptureBuffer _x2c_match_capture = { .values = _x2c_match_values, .capacity = 1 };
    switch (Var_symbol(car(_x2c_match_expr))) {
      case 150408: ;  static MatchCaptureSite _x2c_match_site_7;  if (x2c_match_site_try_capture(& _x2c_match_site_7, _x2c_match_expr, List_var(_30296), &_x2c_match_capture)) {Var identity = _x2c_match_values[0];  _record_declaration_binding_visibility(c, declaration, kind, private, mark, Var_list(identity));  break;
    }
    case 992: ;  static MatchCaptureSite _x2c_match_site_8;  if (x2c_match_site_try_capture(& _x2c_match_site_8, _x2c_match_expr, List_var(_30317), &_x2c_match_capture)) {Var identity = _x2c_match_values[0];  _record_declaration_binding_visibility(c, declaration, kind, private, mark, Var_list(identity));  break;
  }
  default: break;
    }
  }
}
}
}

void Compiler_record_source_typedef(Compiler, String, List, int);
static void _record_declaration_binding_visibility(Compiler c, List declaration, Symbol kind, int private, int mark, List identity){
  String name = binding_identity_spelling(identity);  if(kind == 44661285196 && String_truth(name)) Compiler_record_source_typedef(c, name, declaration, private);  if(mark && String_truth(name)) Sym_mark_static(c -> sym, cons(String_var(name), NULL));
}

String Compiler_package_spelling(Compiler c, String name){
  if(! _init_guard_) _file_init_();  if(! String_truth(c -> package) || ! String_truth(name)) return name;  String prefix = String_join(NULL, cons(String_var(c -> package), cons(String_var(_30286), NULL)));  return String_startswith(name, prefix) ? name : String_join(NULL, cons(String_var(prefix), cons(String_var(name), NULL)));
}

Var Map_getindex(Map, Var);
int Var_is_void(Var);
void Compiler_register_package_alias(Compiler c, String name, String alias, Token token){
  if(! _init_guard_) _file_init_();  Var bound = Map_getindex(c -> package_aliases, String_var(alias));  if(! Var_is_void(bound) && Var_equal(bound, String_var(name))) return;  Compiler__check_package_binding(c, _30357, alias, token);  Map_setindex(c -> package_aliases, String_var(alias), String_var(name));
}

void Compiler_register_package_member(Compiler c, String name, String member, String local, Token member_token, Token local_token){
  if(! _init_guard_) _file_init_();  List binding = cons(String_var(name), cons(String_var(member), NULL));  Var bound = Map_getindex(c -> package_members, String_var(local));  if(! Var_is_void(bound) && Var_list(bound) == binding) return;  String spelling = String_join(NULL, cons(String_var(name), cons(String_var(_30286), cons(String_var(member), NULL))));  if(! List_truth(Sym_get_exact(c -> sym, cons(String_var(spelling), NULL)))) Compiler_report_error(c, 33658058, String_join(NULL, cons(String_var(String_new("package \'")), cons(String_var(name), cons(String_var(String_new("\' has no public name \'")), cons(String_var(member), cons(String_var(String_new("\'")), NULL)))))), member_token, NULL);  Compiler__check_package_binding(c, _30358, local, local_token);  Map_setindex(c -> package_members, String_var(local), List_var(binding));
}

static void Compiler__check_package_binding(Compiler c, String kind, String local, Token token){
  Var alias = Map_getindex(c -> package_aliases, String_var(local));  Var member = Map_getindex(c -> package_members, String_var(local));  String bound = Var_is_void(alias) ? NULL : Var_string(alias);  if(! String_truth(bound) && ! Var_is_void(member)){
    List pair = Var_list(member);  List _x2c_destructure_4 = pair;  String package = Var_string(List_getindex(_x2c_destructure_4, 0));  String member_name = Var_string(List_getindex(_x2c_destructure_4, 1));  bound = String_join(NULL, cons(String_var(package), cons(String_var(_22574), cons(String_var(member_name), NULL))));
  }
  if(String_truth(bound)) Compiler_report_error(c, 33658058, String_join(NULL, cons(String_var(String_new("package ")), cons(String_var(kind), cons(String_var(String_new(" \'")), cons(String_var(local), cons(String_var(String_new("\' is already bound")), NULL)))))), token, cons(String_var(String_join(NULL, cons(String_var(String_new("bound to: ")), cons(String_var(bound), NULL)))), NULL));  if(List_truth(Sym_get_exact(c -> sym, cons(String_var(local), NULL)))) Compiler_report_error(c, 33658058, String_join(NULL, cons(String_var(String_new("package ")), cons(String_var(kind), cons(String_var(String_new(" \'")), cons(String_var(local), cons(String_var(String_new("\' collides with a declared name")), NULL)))))), token, NULL);
}

String Compiler_package_member_spelling(Compiler c, String name){
  if(! _init_guard_) _file_init_();  if(! Map_len(c -> package_members)) return NULL;  Var bound = Map_getindex(c -> package_members, String_var(name));  if(Var_is_void(bound) || List_truth(Sym_get_exact(c -> sym, cons(String_var(name), NULL)))) return NULL;  List pair = Var_list(bound);  List _x2c_destructure_5 = pair;  String package = Var_string(List_getindex(_x2c_destructure_5, 0));  String member_name = Var_string(List_getindex(_x2c_destructure_5, 1));  return String_join(NULL, cons(String_var(package), cons(String_var(_30286), cons(String_var(member_name), NULL))));
}

List List_sort(List);
List Compiler_imported_providers(Compiler c, String name){
  if(! _init_guard_) _file_init_();  if(! String_truth(name) || ! Map_len(c -> package_roots)) return NULL;  List packages = NULL; {
    Var key, root;  Map _x2c_macro_object_7 = c -> package_roots;  unsigned _x2c_macro_cursor_7 = 0;  Var _x2c_macro_cursor_output_12;  Var _x2c_macro_cursor_output_13;  while(Map_try_next(_x2c_macro_object_7, &(_x2c_macro_cursor_7), &(_x2c_macro_cursor_output_12), &(_x2c_macro_cursor_output_13))){
      key = _x2c_macro_cursor_output_12;  root = _x2c_macro_cursor_output_13; {
        String package = Var_string(key);  if(List_truth(Sym_get_exact(c -> sym, cons(String_var(String_join(NULL, cons(String_var(package), cons(String_var(_30286), cons(String_var(name), NULL))))), NULL)))) packages = cons(String_var(package), packages);
      }

    }

  }
  return List_sort(packages);
}

String Compiler_imported_spelling(Compiler c, String name){
  if(! _init_guard_) _file_init_();  List packages = Compiler_imported_providers(c, name);  if(! List_truth(packages) || List_truth(List_cdr(packages))) return NULL;  return String_join(NULL, cons(String_var(Var_str(List_car(packages))), cons(String_var(_30286), cons(String_var(name), NULL))));
}

void Sym_define_macro(Sym s, Atom name, List definition){
  if(! _init_guard_) _file_init_();  SymScope * scope = Sym__scope_at(s, - 1);  if(scope -> macros == NULL) scope -> macros = Map_new();  if(! Map_contains(scope -> macros, name)) s -> local_macro_names ++;  Map_setindex(scope -> macros, name, List_var(definition));  Var captures = List_assoc(definition, Symbol_var(209423012198));  if(Var_is_row(captures, 9, 7, 4)){
    Var capture;  List _x2c_macro_object_8 = Var_list(captures);  List _x2c_macro_cursor_8 = _x2c_macro_object_8;  Var _x2c_macro_cursor_output_14;  while(List_try_next(_x2c_macro_object_8, &(_x2c_macro_cursor_8), &(_x2c_macro_cursor_output_14))){
      capture = _x2c_macro_cursor_output_14;  if(Var_is_row(capture, 9, 7, 4)) Map_setindex(s -> binding_facts, List_var(cons(_30318, cons(List_var(Var_list(capture)), NULL))), int_var(1));
    }

  }

}

int Sym_has_local_macros(Sym s){
  return s -> local_macro_names != 0;
}

List Sym_lookup_macro(Sym s, Atom name){
  Var definition;  for(int i =(int) Block_len(s -> scopes) - 1;  i >= s -> base_scopes;  i --){
    SymScope * scope = Sym__scope_at(s, i);  if(scope -> macros != NULL && Map_try_get(scope -> macros, name, &(definition))) return Var_list(definition);
  }
  return NULL;
}

int Var_is(Var, Symbol);
Map Var_map(Var);
Map Compiler_macro_definition_locals(Compiler c){
  if(! _init_guard_) _file_init_();  Var stored = Map_getindex(c -> macro_holes, List_var(_30320));  return Var_is(stored, 26720) ? Var_map(stored) : NULL;
}

Type Type_canonicalize(Type);
Type Sym_resolve_key(Sym s, Type key){
  if(! _init_guard_) _file_init_();  if(! List_truth(Type_list(key))) return key;  key = Type_canonicalize(key);  return Sym__resolve_chain(s, key, NULL, key, 0);
}

int Type_is_typedef_name(Type);
int Type_is_typedef(Type);
static Type Sym__resolve_chain(Sym s, Type key, Type stop, Type origin, int hops){
  if(hops > RESOLVE_KEY_MAX_HOPS) Sym__typedef_budget_error(s, origin);  if(List_truth(Type_list(stop)) && List_equal(Type_list(key), Type_list(stop))) return key;  if(Type_is_typedef_name(key) || Type_is_typedef(key)){
    Type type = Sym__typedef_target(s, key);  if(List_truth(Type_list(type))) return Sym__resolve_chain(s, type, stop, origin, hops + 1);
  }

  {
    List _x2c_match_expr = Type_list(key);
    Var _x2c_match_values[2];  MatchCaptureBuffer _x2c_match_capture = { .values = _x2c_match_values, .capacity = 2 };
    switch (0) {
      default: ;  static MatchCaptureSite _x2c_match_site_9;  if (x2c_match_site_try_capture(& _x2c_match_site_9, _x2c_match_expr, List_var(_30329), &_x2c_match_capture)) {Var kind = _x2c_match_values[0];  Var spelling = _x2c_match_values[1];  if(! List_truth(Sym_field_order(s, key))) return List_type(cons(kind, cons(spelling, NULL)));  break;
}

    }
  }
return key;
}

String List_repr(List);
static void Sym__typedef_budget_error(Sym s, Type origin){
  Compiler_report_error(s -> c, 1362954, String_join(NULL, cons(String_var(String_new("typedef chain too deep (possible cycle) resolving ")), cons(String_var(List_repr(Type_list(origin))), NULL))), NULL, NULL);
}

static Type Sym__typedef_target(Sym s, Type key){
  for(int i = s -> base_scopes - 1;  i >= 0;  i --){
    Var target;  if(Map_try_get(Sym__scope_at(s, i) -> symbols, List_var(key), &(target))) return Var_type(target);
  }
  return NULL;
}

Type Sym_next_typedef(Sym s, Type type, int * hops){
  if(! _init_guard_) _file_init_();  if(++(* hops) > RESOLVE_KEY_MAX_HOPS) Sym__typedef_budget_error(s, type);  return Type_is_typedef_name(type) || Type_is_typedef(type) ? Sym__typedef_target(s, type) : List_type(Sym_get(s, Type_list(type)));
}

Type Sym_resolve_base_type(Sym s, Type key){
  Type type = Sym__typedef_target(s, key);  for(int hops = 0;  List_truth(Type_list(type)) && hops < RESOLVE_KEY_MAX_HOPS;  hops ++){
    Type next = Sym__typedef_target(s, type);  if(! List_truth(Type_list(next))) break;  type = next;
  }
  return type;
}

Type Sym_normalize_declared_type(Sym s, Type type){
  if(! _init_guard_) _file_init_();  return List_truth(Type_list(type)) ? Sym__normalize_chain(s, type, type, 0) : NULL;
}

static Type Sym__normalize_chain(Sym s, Type type, Type origin, int hops){
  type = Type_declared(type);  if(hops > RESOLVE_KEY_MAX_HOPS) Sym__typedef_budget_error(s, origin);  Type next = Sym__typedef_base_step(s, type);  return List_truth(Type_list(next)) ? Sym__normalize_chain(s, next, origin, hops + 1) : type;
}

Type Type_base_type(Type);
static Type Sym__typedef_base_step(Sym s, Type type){
  Type base = Type_base_type(type);  if(! List_truth(Type_list(base)) ||(! Type_is_typedef_name(base) && ! Type_is_typedef(base))) return NULL;  Type next = Sym__typedef_target(s, base);  if(! List_truth(Type_list(next))) next = _builtin_typedef_scalar(base);  return List_truth(Type_list(next)) ? _replace_type_base(type, base, next) : NULL;
}

static Type _replace_type_base(Type type, Type base, Type replacement){
  if(type == base) return replacement;  if(! List_truth(Type_list(type))) return type;  return List_type(cons(List_car(Type_list(type)), Type_list(_replace_type_base(List_cdr(type), base, replacement))));
}

int Type_is_bare_typedef_name(Type);
Type Sym_local_type(Sym s, Type type){
  Type base = Type_base_type(type);  if(Type_is_aggregate_tag(base) && Var_is_row(List_cadr(Type_list(base)), 11, 7, 1)) return Sym__local_tag(s, type, base);  return Type_is_bare_typedef_name(base) ? Sym__local_alias(s, type, base) : type;
}

static Type Sym__local_tag(Sym s, Type type, Type base){
  for(int i = Block_len(s -> scopes) - 1;  i >= s -> base_scopes;  i --){
    SymScope * scope = Sym__scope_at(s, i);  Var binding;  if(Map_try_get(scope -> bindings, List_var(base), &(binding))) return _replace_type_base(type, base, List_type(cons(List_car(Type_list(base)), cons(binding, NULL))));
  }
  return type;
}

static Type Sym__local_alias(Sym s, Type type, Type base){
  for(int i = Block_len(s -> scopes) - 1;  i >= s -> base_scopes;  i --){
    Map symbols = Sym__scope_at(s, i) -> symbols;  Var marker;  if(! Map_try_get(symbols, List_var(base), &(marker))) continue;  Type declared = Var_type(marker);  if(! Type_is_typedef(declared)) return type;  Var target;  if(! Map_try_get(symbols, List_var(declared), &(target))) return type;  return _replace_type_base(type, base, Var_type(target));
  }
  return type;
}

Type Type_scalar(Type);
int Type_is_number(Type);
Type Sym_resolve_numeric_type(Sym s, Type type){
  if(! _init_guard_) _file_init_();  Type scalar = Type_scalar(type);  if(List_truth(Type_list(scalar))) return scalar;  Type resolved = Sym_resolve_key(s, type);  if(Type_is_number(resolved)) return resolved;  return _builtin_typedef_scalar(resolved);
}

Symbol String_symbol(String);
static Type _builtin_typedef_scalar(Type key){
  if(! Type_is_bare_typedef_name(key)) return NULL;  String name = Var_string(List_car(Type_list(key)));  switch(String_symbol(name)){
    case 30065 : case 1036417972854761 : return List_type(_30331);  case 26993 : case 7275089256425 : return List_type(_30333);  case 3846509 : case 1036417972614847 : return List_type(_30336);  case 3453293 : case 931211394113513 : return List_type(_30335);  case 3847013 : case 1036417972679359 : return List_type(_30337);  case 3453797 : case 931211402371049 : case 49610332136 : return List_type(_2533);  case 3847785 : case 1036417972778175 : return List_type(sizeof(long) == 8 ? _30340 : _30342);  case 46829405509608 : case 1295658984 : return List_type(sizeof(long) == sizeof(void *) ? _30340 : _30342);  case 3454569 : case 931211415019497 : return List_type(sizeof(long) == 8 ? _30339 : _30341);  case 649917143016 : case 36597704046568 : case 42097848296 : return List_type(sizeof(long) == sizeof(void *) ? _30339 : _30341);  case 31864808 : case 1361915880 : return List_type(_30339);  case 492352113 : return List_type(_30342);  case 442020465 : return List_type(_30341);  case 3355493 : return List_type(_30344);  case 3356265 : return List_type(_30346);  case 429437553 : return List_type(_30347);
  }
  return NULL;
}

Symbol Sym_var_tag_for_type(Sym s, Type type, Type * resolved){
  if(! _init_guard_) _file_init_();  Type origin = Type_canonicalize(type);  return Sym__var_tag_chain(s, origin, origin, resolved, 0);
}

Symbol Type_var_tag(Type);
static Symbol Sym__var_tag_chain(Sym s, Type type, Type origin, Type * resolved, int hops){
  type = Type_canonicalize(type);  Symbol tag = Type_var_tag(type);  if(tag){
    if(resolved)(* resolved) = type;  return tag;
  }
  if(hops > RESOLVE_KEY_MAX_HOPS) Sym__typedef_budget_error(s, origin);  Type next = Sym__typedef_base_step(s, type);  if(List_truth(Type_list(next))) return Sym__var_tag_chain(s, next, origin, resolved, hops + 1);  if(resolved)(* resolved) = type;  return 0;
}

int Sym_is_var_type(Sym s, Type type){
  if(! _init_guard_) _file_init_();  return Sym_is_named_value_type(s, type, _30359);
}

int Sym_is_string_type(Sym s, Type type){
  if(! _init_guard_) _file_init_();  return Sym_is_named_value_type(s, type, _30360);
}

int Sym_is_array_type(Sym s, Type type){
  if(! _init_guard_) _file_init_();  return Sym_is_named_value_type(s, type, _30361);
}

int Sym_is_map_type(Sym s, Type type){
  if(! _init_guard_) _file_init_();  return Sym_is_named_value_type(s, type, _30362);
}

int Sym_is_named_value_type(Sym s, Type type, String name){
  if(! _init_guard_) _file_init_();  if(! List_truth(Type_list(type)) || ! String_truth(name)) return 0;  Type wanted = List_type(cons(String_var(name), NULL)), origin = Type_canonicalize(type);  type = Sym__resolve_chain(s, origin, wanted, origin, 0);  return List_equal(Type_list(type), Type_list(wanted));
}

int Var_truth(Var);
int Type_is_aggregate(Type);
Type Sym_lookup_field(Sym s, Type type, List field){
  if(! _init_guard_) _file_init_();  type = Sym_resolve_key(s, type);  if(! List_truth(Type_list(type)) || ! Type_is_aggregate_tag(type)) return NULL;  Type found = List_type(Sym_get(s, List_append(Type_list(type), List_append(field, NULL))));  if(List_truth(Type_list(found))) return found; {
    List row;  List _x2c_macro_object_9 = List_cdr(Sym_field_order(s, type));  List _x2c_macro_cursor_9 = _x2c_macro_object_9;  Var _x2c_macro_cursor_output_15;  while(List_try_next(_x2c_macro_object_9, &(_x2c_macro_cursor_9), &(_x2c_macro_cursor_output_15))){
      row = Var_list(_x2c_macro_cursor_output_15); {
        Type member = Var_type(List_cadr(row));  if(Var_truth(List_car(row)) || ! Type_is_aggregate(Sym_resolve_key(s, member))) continue;  found = Sym_lookup_field(s, member, field);  if(List_truth(Type_list(found))) return found;
      }

    }

  }
  return NULL;
}

Var List_caddr(List);
void Sym_declare_field_order(Sym s, Type type, List fields){
  if(! _init_guard_) _file_init_();  Array rows = Array_new(); {
    List declaration;  List _x2c_macro_object_11 = fields;  List _x2c_macro_cursor_11 = _x2c_macro_object_11;  Var _x2c_macro_cursor_output_17;  while(List_try_next(_x2c_macro_object_11, &(_x2c_macro_cursor_11), &(_x2c_macro_cursor_output_17))){
      declaration = Var_list(_x2c_macro_cursor_output_17); {
        while(Var_equal(List_car(declaration), Symbol_var(104))) declaration = Var_list(List_caddr(declaration));  if(Var_equal(List_car(declaration), Symbol_var(272838634664))) continue;  List bindings = Var_list(List_caddr(declaration)); {
          List declarator;  List _x2c_macro_object_10 = List_cdr(bindings);  List _x2c_macro_cursor_10 = _x2c_macro_object_10;  Var _x2c_macro_cursor_output_16;  while(List_try_next(_x2c_macro_object_10, &(_x2c_macro_cursor_10), &(_x2c_macro_cursor_output_16))){
            declarator = Var_list(_x2c_macro_cursor_output_16);  Array_push(rows, List_var(Sym__field_row(s, type, declaration, declarator)));
          }

        }

      }

    }

  }
  Sym_set(s, List_append(Type_list(type), _30350), cons(_30351, List_append(Array_list_free(rows), NULL)));
}

static List Sym__field_row(Sym s, Type type, List declaration, List declarator){
  String name = binding_identity_spelling(Var_list(List_cadr(declarator)));  Type declared = String_truth(name) ? List_type(Sym_get(s, List_append(Type_list(type), cons(String_var(name), NULL)))) : Type_declared(List_type_from_ast(cons(_2488, cons(List_cadr(declaration), cons(List_var(cons(_2489, cons(List_var(declarator), NULL))), NULL)))));  return cons(String_var(name), cons(List_var(declared), NULL));
}

List Sym_field_order(Sym s, Type type){
  if(! _init_guard_) _file_init_();  return Sym_get(s, List_append(Type_list(type), _30350));
}

void Sym_declare_delegate_field(Sym s, Type aggregate, String name){
  if(! _init_guard_) _file_init_();  Sym_set(s, List_append(Type_list(aggregate), cons(_30352, cons(String_var(name), NULL))), _30353);
}

int Type_is_pointer(Type);
Type Type_dereference(Type);
Type Sym_delegate_aggregate(Sym s, Type type){
  if(! _init_guard_) _file_init_();  type = Type_canonicalize(type);  int hops = 0;  while(List_truth(Type_list(type)) && ! Type_is_aggregate_tag(type)){
    if(Type_is_pointer(type)){
      type = Sym_resolve_key(s, Type_dereference(type));  break;
    }
    type = Sym_next_typedef(s, type, &(hops));
  }
  return List_truth(Type_list(type)) && Type_is_aggregate_tag(type) ? type : NULL;
}

SymTxn Compiler_begin_semantic_transaction(Compiler c){
  SymTxn transaction = Scope_calloc(1, sizeof(struct SymTxn));  transaction -> c = c;  transaction -> scope_index = Block_len(c -> sym -> scopes) - 1;  SymScope * scope = Sym__scope_at(c -> sym, transaction -> scope_index);  SymTxn__save(transaction, * scope);  if(transaction -> extended) SymTxn__save_effects(transaction);  if(c -> source_facts && c -> source_primary) SymTxn__save_sources(transaction);  SymTxn__stage(transaction, scope);  transaction -> active = 1;  return transaction;
}

static void SymTxn__save(SymTxn s, SymScope scope){
  Compiler c = s -> c;  s -> scope = scope;  s -> counters = c -> names -> counters;  s -> statics = c -> sym -> statics;  s -> binding_facts = Compiler_semantic_binding_facts(c);  s -> next_binding = c -> names -> next_binding;  s -> local_macro_names = c -> sym -> local_macro_names;  s -> initializer_name = c -> init_fn;  s -> shutdown_name = c -> fini_fn;  s -> extended = c -> macro_application > 0;
}

Map Map_copy(Map);
static void SymTxn__save_effects(SymTxn s){
  Compiler c = s -> c;  s -> adapters = c -> names -> adapters;  s -> base_bindings = Array_new();  s -> early_count = Array_len(c -> early_decls);  s -> init_count = Array_len(c -> inits);  s -> origin_count = Array_len(c -> origins);  s -> origin = c -> origin;  s -> needs_exception = c -> needs_exception;  c -> names -> adapters = Map_copy(c -> names -> adapters);  for(int i = 0;  i < c -> sym -> base_scopes;  i ++){
    if(i == s -> scope_index) continue;  SymScope * base = Sym__scope_at(c -> sym, i);  Array_push(s -> base_bindings, List_var(cons(int_var(i), cons(Map_var(base -> bindings), NULL))));  base -> bindings = Map_copy(base -> bindings);
  }

}

static void SymTxn__save_sources(SymTxn s){
  s -> source_definitions = Map_copy(s -> c -> source_definitions);  s -> source_occurrences = Array_len(s -> c -> source_occurrences);
}

void Compiler_merge_source_declarations(Compiler, Map, Map);
static void SymTxn__stage(SymTxn s, SymScope * scope){
  Compiler c = s -> c;  scope -> symbols = Map_copy(s -> scope.symbols);  Compiler_merge_source_declarations(c, scope -> symbols, s -> scope.symbols);  scope -> bindings = Map_copy(s -> scope.bindings);  scope -> enumerators = Map_copy(s -> scope.enumerators);  scope -> macros = s -> scope.macros != NULL ? Map_copy(s -> scope.macros) : NULL;  c -> sym -> statics = Map_copy(c -> sym -> statics);  c -> sym -> binding_facts = Map_copy(Compiler_semantic_binding_facts(c));  c -> names -> counters = Map_copy(c -> names -> counters);
}

int Map_equal(Map, Map);
int SymTxn_local_macros_changed(SymTxn s){
  SymScope * scope = Sym__scope_at(s -> c -> sym, s -> scope_index);  Map before = s -> scope.macros, after = scope -> macros;  if(before == NULL || after == NULL) return(void *) before !=(void *) after;  return ! Map_equal(before, after);
}

void SymTxn_commit(SymTxn s){
  if(! s || ! s -> active) return;  Compiler c = s -> c;  SymScope * scope = Sym__scope_at(c -> sym, s -> scope_index);  SymScope staged = * scope;  * scope = s -> scope;  Compiler__merge_scope(c, scope, staged);  if(s -> extended) SymTxn__commit_effects(s);  s -> active = 0;
}

static void Compiler__merge_scope(Compiler c, SymScope * scope, SymScope staged){
  Map_merge(scope -> symbols, staged.symbols);  Compiler_merge_source_declarations(c, scope -> symbols, staged.symbols);  Map_merge(scope -> bindings, staged.bindings);  Map_merge(scope -> enumerators, staged.enumerators);  if(staged.macros == NULL) return;  if(scope -> macros == NULL) scope -> macros = Map_new();  Map_merge(scope -> macros, staged.macros);
}

List Array_list(Array);
static void SymTxn__commit_effects(SymTxn s){
  Compiler c = s -> c;  Map adapters = c -> names -> adapters;  c -> names -> adapters = s -> adapters;  Map_merge(s -> adapters, adapters); {
    List row;  List _x2c_macro_object_12 = Array_list(s -> base_bindings);  List _x2c_macro_cursor_12 = _x2c_macro_object_12;  Var _x2c_macro_cursor_output_18;  while(List_try_next(_x2c_macro_object_12, &(_x2c_macro_cursor_12), &(_x2c_macro_cursor_output_18))){
      row = Var_list(_x2c_macro_cursor_output_18); {
        SymScope * base = Sym__scope_at(c -> sym, Var_int(Var_convert(List_car(row), 3453797)));  Map staged = base -> bindings, original = Var_map(List_cadr(row));  base -> bindings = original;  Map_merge(original, staged);
      }

    }

  }

}

void SymTxn_commit_transient(SymTxn s){
  Compiler c = s -> c;  Map statics = c -> sym -> statics, facts = Compiler_semantic_binding_facts(c);  Map counters = c -> names -> counters;  SymTxn_commit(s);  c -> sym -> statics = s -> statics;  c -> sym -> binding_facts = s -> binding_facts;  c -> names -> counters = s -> counters;  _replace_map(s -> statics, statics);  _replace_map(s -> binding_facts, facts);  _replace_map(s -> counters, counters);
}

Array Iter_array(Iter);
Iter Map_keys(Map, Iter);
void x2c_cleanup_push(X2CCleanup *);
int Array_try_next(Array, int *, Var *);
void x2c_cleanup_leave(X2CCleanup *);
static void _replace_map(Map original, Map staged){
  Array keys = Iter_array(Map_keys(original, &(struct Iter){
    int_var(0)
  }
  )); {
    _x2c_defer_env_0 _x2c_macro_environment_0 ={
      0
    }
    ;  _x2c_macro_environment_0._x2c_defer_capture_0 =(const void *) & keys;  X2CCleanup _x2c_defer_record_0 ={
      .fn = _x2c_defer_cleanup_0, .env = & _x2c_macro_environment_0
    }
    ;  x2c_cleanup_push(& _x2c_defer_record_0); {
      {
        Var key;  Array _x2c_macro_object_13 = keys;  int _x2c_macro_cursor_13 = 0;  Var _x2c_macro_cursor_output_19;  while(Array_try_next(_x2c_macro_object_13, &(_x2c_macro_cursor_13), &(_x2c_macro_cursor_output_19))){
          key = _x2c_macro_cursor_output_19;  if(! Map_contains(staged, key)) Map_del(original, key);
        }

      }
      Map_merge(original, staged);
    }
    x2c_cleanup_leave(& _x2c_defer_record_0);
  }

}

void SymTxn_rollback(SymTxn s){
  if(! s || ! s -> active) return;  Compiler c = s -> c;  SymTxn__restore(s);  if(s -> extended) SymTxn__restore_effects(s);  if(c -> source_facts && c -> source_primary) SymTxn__restore_sources(s);  s -> active = 0;
}

static void SymTxn__restore(SymTxn s){
  Compiler c = s -> c;  SymScope * scope = Sym__scope_at(c -> sym, s -> scope_index);  * scope = s -> scope;  c -> sym -> statics = s -> statics;  c -> sym -> binding_facts = s -> binding_facts;  c -> names -> next_binding = s -> next_binding;  c -> sym -> local_macro_names = s -> local_macro_names;  c -> names -> counters = s -> counters;  c -> init_fn = s -> initializer_name;  c -> fini_fn = s -> shutdown_name;
}

void Array_resize(Array, size_t);
static void SymTxn__restore_effects(SymTxn s){
  Compiler c = s -> c;  c -> names -> adapters = s -> adapters; {
    List row;  List _x2c_macro_object_14 = Array_list(s -> base_bindings);  List _x2c_macro_cursor_14 = _x2c_macro_object_14;  Var _x2c_macro_cursor_output_20;  while(List_try_next(_x2c_macro_object_14, &(_x2c_macro_cursor_14), &(_x2c_macro_cursor_output_20))){
      row = Var_list(_x2c_macro_cursor_output_20);  Sym__scope_at(c -> sym, Var_int(Var_convert(List_car(row), 3453797))) -> bindings = Var_map(List_cadr(row));
    }

  }
  Array_resize(c -> early_decls, s -> early_count);  Array_resize(c -> inits, s -> init_count);  Array_resize(c -> origins, s -> origin_count);  c -> origin = s -> origin;  c -> needs_exception = s -> needs_exception;
}

static void SymTxn__restore_sources(SymTxn s){
  Compiler c = s -> c;  Array_resize(c -> source_occurrences, s -> source_occurrences);  _replace_map(c -> source_definitions, s -> source_definitions);
}

void Array_cleanup(Array);
static void _x2c_defer_cleanup_0(void * _x2c_defer_opaque_0){
  _x2c_defer_env_0 * _x2c_defer_data_0 =(_x2c_defer_env_0 *) _x2c_defer_opaque_0;  Array_cleanup((*(Array *) _x2c_defer_data_0->_x2c_defer_capture_0));
}

