#define _x2c_initializer_choice_6E6B8BB0_0_expanded(_x2c_static_input_0) static void _x2c_static_initialize_0(void){\
  _x2c_static_input_0;\
}
#define _x2c_initializer_choice_6E6B8BB0_0(_x2c_static_input_0) _x2c_initializer_choice_6E6B8BB0_0_expanded(_x2c_static_input_0)
#define _x2c_initializer_choice_6E6B8BB0_1_expanded(_x2c_static_input_1) static void _x2c_static_initialize_1(void){\
  _x2c_static_input_1;\
}
#define _x2c_initializer_choice_6E6B8BB0_1(_x2c_static_input_1) _x2c_initializer_choice_6E6B8BB0_1_expanded(_x2c_static_input_1)
#define _x2c_initializer_choice_6E6B8BB0_2_expanded(_x2c_static_input_2) static void _x2c_static_initialize_2(void){\
  _x2c_static_input_2;\
}
#define _x2c_initializer_choice_6E6B8BB0_2(_x2c_static_input_2) _x2c_initializer_choice_6E6B8BB0_2_expanded(_x2c_static_input_2)
#define _x2c_initializer_choice_6E6B8BB0_3_expanded(_x2c_static_input_3) static void _x2c_static_initialize_3(void){\
  _x2c_static_input_3;\
}
#define _x2c_initializer_choice_6E6B8BB0_3(_x2c_static_input_3) _x2c_initializer_choice_6E6B8BB0_3_expanded(_x2c_static_input_3)
#define _x2c_initializer_choice_6E6B8BB0_4_expanded(_x2c_static_input_4) static void _x2c_static_initialize_4(void){\
  _x2c_static_input_4;\
}
#define _x2c_initializer_choice_6E6B8BB0_4(_x2c_static_input_4) _x2c_initializer_choice_6E6B8BB0_4_expanded(_x2c_static_input_4)
#define _x2c_initializer_choice_6E6B8BB0_5_expanded(_x2c_static_input_5) static void _x2c_static_initialize_5(void){\
  _x2c_static_input_5;\
}
#define _x2c_initializer_choice_6E6B8BB0_5(_x2c_static_input_5) _x2c_initializer_choice_6E6B8BB0_5_expanded(_x2c_static_input_5)
/* auto-generated by x2c.  Do not edit! */

#include "utils.h"

#include "exception.h"

static String _35, _34, _33, _32, _31, _30, _29, _28, _27, _26, _25, _24, _23, _22, _21, _20, _19, _18, _17, _16, _15, _14, _13, _12, _11, _10, _9, _8, _7, _6, _5, _4, _3, _2, _1, _0;

static int _init_guard_ = 0;

__attribute__((constructor)) static void _file_init_(void);

static void _initialize_environment(const char * argv0, String embedded_identity);

#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <sys/file.h>
#include <sys/wait.h>
#include <unistd.h>
static String x2c_executable_path, x2c_root_path;

_x2c_initializer_choice_6E6B8BB0_0((x2c_executable_path = NULL))
_x2c_initializer_choice_6E6B8BB0_1((x2c_root_path = NULL))
static String x2c_identity;

_x2c_initializer_choice_6E6B8BB0_2((x2c_identity = NULL))
static int x2c_root_found;

_x2c_initializer_choice_6E6B8BB0_3((x2c_root_found = 0))
static List x2c_base_include_dirs, x2c_repo_cpp_include_dirs;

_x2c_initializer_choice_6E6B8BB0_4((x2c_base_include_dirs = NULL))
_x2c_initializer_choice_6E6B8BB0_5((x2c_repo_cpp_include_dirs = NULL))
static String _executable(const char * argv0);

static String _identity(void);

static int _is_home(Path p);

static String _locate_home(Path p);

static void _prepare_repo_defaults(void);

typedef struct _x2c_defer_env_0{
  const void * _x2c_defer_capture_0;
  const void * _x2c_defer_capture_1;
}
_x2c_defer_env_0;

static void _x2c_defer_cleanup_0(void * _x2c_defer_opaque_0);

__attribute__((constructor)) static void _file_init_(void){
  x2c_initialize_protocols();
  if(_init_guard_) return;
  _init_guard_ = 1;
  _0 = String_new("command ");
  _1 = String_new(", driver ");
  _2 = String_new("compiler identity mismatch: ");
  _3 = String_new("/");
  _4 = String_new("/src/");
  _5 = String_new(".x");
  _6 = String_new("/packages");
  _7 = String_new("/libexec");
  _8 = String_new("/libexec/x2c");
  _9 = String_new("/builds");
  _10 = String_new(" ");
  _11 = String_new(": ");
  _12 = String_new("cannot lock ");
  _13 = String_new(".tmp.%ld");
  _14 = String_new("/proc/self/exe");
  _15 = String_new("%016llx");
  _16 = String_new("/");
  _17 = String_new("/include/x2c");
  _18 = String_new("/src");
  _19 = String_new("/lib");
  _20 = String_new("%08X");
  _21 = String_new("X2C_HOME");
  _22 = String_new(".");
  _23 = String_new("X2C_IDENTITY");
  _24 = String_new(".x");
  _25 = String_new(".xp");
  _26 = String_new(".c");
  _27 = String_new(".h");
  _28 = String_new(".o");
  _29 = String_new(".a");
  _30 = String_new(".xpmacro");
  _31 = String_new(":");
  _32 = String_new("PATH");
  _33 = String_new("/proc/self/exe");
  _34 = String_new("include");
  _35 = String_new("etc/compiler-sdk.xlisp");
  _x2c_static_initialize_0();
  _x2c_static_initialize_1();
  _x2c_static_initialize_2();
  _x2c_static_initialize_3();
  _x2c_static_initialize_4();
  _x2c_static_initialize_5();
}

int String_truth(String);

String Env_get(String);

int String_getindex(String, int);

String String_rstrip(String, char *);

Path Path_absolute(Path);

static void _initialize_environment(const char * argv0, String embedded_identity){
  if(String_truth(x2c_root_path)) return;
  x2c_executable_path = _executable(argv0);
  x2c_identity = String_truth(embedded_identity) ? embedded_identity : _identity();
  String home = Env_get(_21);
  if(String_truth(home) && ! String_getindex(home, 0)) home = NULL;
  String root = String_truth(home) ? String_rstrip(home, "/") : _locate_home(x2c_executable_path);
  if(! String_truth(root)) root = _locate_home(Path_absolute(_22));
  x2c_root_found = root != NULL;
  x2c_root_path = Path_absolute(String_truth(root) ? root : _22);
  _prepare_repo_defaults();
}

void x2c_initialize_environment(const char * argv0){
  if(! _init_guard_) _file_init_();
  _initialize_environment(argv0, NULL);
}

int String_equal(String, String);

Var String_var(String);

void x2c_initialize_command_environment(const char * argv0, String embedded_identity){
  if(! _init_guard_) _file_init_();
  String supplied = Env_get(_23);
  if(String_truth(supplied) && ! String_equal(supplied, embedded_identity)){
    String detail = String_join(NULL, cons(String_var(_0), cons(String_var(embedded_identity), cons(String_var(_1), cons(String_var(supplied), NULL)))));
    x2c_driver_error(String_join(NULL, cons(String_var(_2), cons(String_var(detail), NULL))));
  }
  _initialize_environment(argv0, embedded_identity);
}

void x2c_set_root(String root){
  if(! _init_guard_) _file_init_();
  x2c_root_path = Path_absolute(root);
  x2c_root_found = 1;
  x2c_base_include_dirs = NULL;
  x2c_repo_cpp_include_dirs = NULL;
  _prepare_repo_defaults();
}

String x2c_get_root(void){
  if(! _init_guard_) _file_init_();
  return x2c_root_path;
}

String x2c_get_executable(void){
  if(! _init_guard_) _file_init_();
  return x2c_executable_path;
}

int List_try_next(List, List *, Var *);

String Var_string(Var);

int String_startswith(String, String);

Var List_car(List);

List String_split(String, String);

String String_remove_prefix(String, String);

int String_is_identifier(String);

String x2c_package_directory(List roots, String path){
  if(! _init_guard_) _file_init_();
  String source = Path_absolute(path);
  {
    String root;
    List _x2c_macro_object_0 = roots;
    List _x2c_macro_cursor_0 = _x2c_macro_object_0;
    Var _x2c_macro_cursor_output_0;
    while(List_try_next(_x2c_macro_object_0, & _x2c_macro_cursor_0, & _x2c_macro_cursor_output_0)){
      root = Var_string(_x2c_macro_cursor_output_0);
      {
        String prefix = String_join(NULL, cons(String_var(Path_absolute(root)), cons(String_var(_3), NULL)));
        if(! String_startswith(source, prefix)) continue;
        String name = Var_string(List_car(String_split(String_remove_prefix(source, prefix), _16)));
        if(String_is_identifier(name) && ! String_equal(source, String_join(NULL, cons(String_var(prefix), cons(String_var(name), NULL))))) return String_join(NULL, cons(String_var(prefix), cons(String_var(name), NULL)));
      }

    }

  }
  return NULL;
}

int String_endswith(String, String);

int x2c_source_file(String path){
  if(! _init_guard_) _file_init_();
  if(String_endswith(path, _24) || String_endswith(path, _25)) return 1;
  if(String_endswith(path, _26) || String_endswith(path, _27) || String_endswith(path, _28) || String_endswith(path, _29)) return 0;
  FILE * file = fopen(path, "r");
  if(! file) return 0;
  char head[2];
  int shebang = fread(head, 1, 2, file) == 2 && head[0] == '#' && head[1] == '!';
  fclose(file);
  return shebang;
}

int x2c_layout_file(String path){
  if(! _init_guard_) _file_init_();
  return String_truth(path) &&(String_endswith(path, _25) || String_endswith(path, _30));
}

int String_rfind(String, String);

int x2c_package_source(String directory, String path){
  if(! _init_guard_) _file_init_();
  if(String_startswith(path, String_join(NULL, cons(String_var(directory), cons(String_var(_4), NULL))))) return 1;
  String name = String_getslice(directory, String_rfind(directory, _16) + 1, -2147483648, 1);
  return String_equal(path, String_join(NULL, cons(String_var(directory), cons(String_var(_3), cons(String_var(name), cons(String_var(_5), NULL))))));
}

List x2c_default_include_dirs(void){
  if(! _init_guard_) _file_init_();
  return x2c_base_include_dirs;
}

List x2c_cpp_include_dirs(void){
  if(! _init_guard_) _file_init_();
  return x2c_repo_cpp_include_dirs;
}

String x2c_home(void){
  if(! _init_guard_) _file_init_();
  return x2c_root_found ? x2c_root_path : NULL;
}

String x2c_home_packages(void){
  if(! _init_guard_) _file_init_();
  String home = x2c_home();
  return String_truth(home) ? String_join(NULL, cons(String_var(home), cons(String_var(_6), NULL))) : NULL;
}

String x2c_home_libexec(void){
  if(! _init_guard_) _file_init_();
  String stage = x2c_stage_dir();
  if(String_truth(stage)) return String_join(NULL, cons(String_var(stage), cons(String_var(_7), NULL)));
  String home = x2c_home();
  return String_truth(home) ? String_join(NULL, cons(String_var(home), cons(String_var(_8), NULL))) : NULL;
}

Path Path_dirname(Path);

String x2c_stage_dir(void){
  if(! _init_guard_) _file_init_();
  if(! String_truth(x2c_executable_path)) return NULL;
  String stage = Path_dirname(x2c_executable_path);
  return String_equal(Path_dirname(stage), String_join(NULL, cons(String_var(x2c_root_path), cons(String_var(_9), NULL)))) ? stage : NULL;
}

Path Path_join(Path, Path);

int Path_is_executable(Path);

String x2c_find_program(String name){
  if(! _init_guard_) _file_init_();
  {
    String directory;
    List _x2c_macro_object_1 = String_split(Env_get(_32), _31);
    List _x2c_macro_cursor_1 = _x2c_macro_object_1;
    Var _x2c_macro_cursor_output_1;
    while(List_try_next(_x2c_macro_object_1, & _x2c_macro_cursor_1, & _x2c_macro_cursor_output_1)){
      directory = Var_string(_x2c_macro_cursor_output_1);
      {
        Path candidate = Path_join(directory, name);
        if(Path_is_executable(candidate)) return candidate;
      }

    }

  }
  return NULL;
}

_Noreturn void x2c_driver_error(const char * message){
  if(! _init_guard_) _file_init_();
  fprintf(stderr, "x2c: error: %s\n", message);
  fflush(NULL);
  _exit(2);
}

Var List_assoc(List, Var);

Var Symbol_var(Symbol);

int Var_is_void(Var);

String String_new(const char *);

void x2c_host_error(List detail){
  if(! _init_guard_) _file_init_();
  Var subject = List_assoc(detail, Symbol_var(1051920));
  if(Var_is_void(subject)) subject = List_assoc(detail, Symbol_var(35599650906));
  long error = Var_long(Var_convert(List_assoc(detail, Symbol_var(11703198)), 818062));
  x2c_driver_error(String_join(NULL, cons(String_var(Var_str(List_assoc(detail, Symbol_var(34096809266140)))), cons(String_var(_10), cons(String_var(Var_str(subject)), cons(String_var(_11), cons(String_var(String_new(strerror(error))), NULL)))))));
}

int file_lock(Path p, int wait){
  if(! _init_guard_) _file_init_();
  int lock = open(p, O_RDWR | O_CREAT | O_CLOEXEC, 0666);
  if(lock < 0) x2c_driver_error(String_join(NULL, cons(String_var(_12), cons(String_var(p), NULL))));
  int operation = wait ? LOCK_EX : LOCK_EX | LOCK_NB;
  while(flock(lock, operation)){
    if(errno == EINTR) continue;
    close(lock);
    return - 1;
  }
  return lock;
}

String String_printf(String, ...);

int List_truth(List);

List List_cddr(List);

void Path_write_text(Path, String);

Var List_cadr(List);

void File_path_error(Var, String, int);

void file_publish(List outputs){
  if(! _init_guard_) _file_init_();
  String suffix = String_printf(_13, (long) getpid());
  {
  _x2c_defer_env_0 _x2c_defer_env_1 = {._x2c_defer_capture_0 =(const void *) & outputs, ._x2c_defer_capture_1 =(const void *) & suffix};

  X2CCleanup _x2c_defer_record_0 = {
    .fn = _x2c_defer_cleanup_0,
    .env = & _x2c_defer_env_1
  };
  x2c_cleanup_push(&_x2c_defer_record_0);
  {
    for(List rest = outputs;  List_truth(rest);  rest = List_cddr(rest)) Path_write_text(String_join(NULL, cons(String_var(Var_str(List_car(rest))), cons(String_var(suffix), NULL))), Var_string(List_cadr(rest)));
    for(List rest = outputs;  List_truth(rest);  rest = List_cddr(rest)){
      String target = Var_string(List_car(rest));
      if(rename(String_join(NULL, cons(String_var(target), cons(String_var(suffix), NULL))), target)) File_path_error(Symbol_var(1219365706), target, errno);
    }

  }
  x2c_cleanup_leave(& _x2c_defer_record_0);

}
}

int String_contains(String, String);

int Path_exists(Path);

static String _executable(const char * argv0){
  char buffer[PATH_MAX];
  ssize_t length = readlink("/proc/self/exe", buffer, sizeof(buffer) - 1);
  if(length >= 0){
    buffer[length] = 0;
    return String_new(buffer);
  }
  String name = String_new(argv0);
  if(String_truth(name) && ! String_contains(name, _16)) name = x2c_find_program(name);
  return Path_exists(name) ? Path_absolute(name) : NULL;
}

static String _identity(void){
  String path = Path_exists(_33) ? _14 : x2c_executable_path;
  int ok = path != NULL;
  uint64_t hash = UINT64_C(1469598103934665603);
  if(ok) hash = x2c_fnv_file(hash, path, & ok);
  return ok ? String_printf(_15, (unsigned long long) hash) : NULL;
}

int Path_is_dir(Path);

int Path_is_file(Path);

static int _is_home(Path p){
  return Path_is_dir(Path_join(p, _34)) && Path_is_file(Path_join(p, _35));
}

static String _locate_home(Path p){
  if(! String_truth(p)) return NULL;
  Path directory = Path_is_dir(p) ? p : Path_dirname(p);
  while(! _is_home(directory)){
    if(String_equal(directory, _16)) return NULL;
    directory = Path_dirname(directory);
  }
  return directory;
}

List cons(Var, List);

static void _prepare_repo_defaults(void){
  if(! String_truth(x2c_root_path)) return;
  String include_dir = String_join(NULL, cons(String_var(x2c_root_path), cons(String_var(_17), NULL)));
  String src_dir = String_join(NULL, cons(String_var(x2c_root_path), cons(String_var(_18), NULL))), lib_dir = String_join(NULL, cons(String_var(x2c_root_path), cons(String_var(_19), NULL)));
  x2c_base_include_dirs = cons(String_var(include_dir), NULL);
  x2c_repo_cpp_include_dirs = Path_is_dir(src_dir) ? cons(String_var(src_dir), cons(String_var(lib_dir), NULL)) : cons(String_var(lib_dir), NULL);
}

uint64_t x2c_fnv_bytes(uint64_t hash, const void * bytes, size_t length){
  if(! _init_guard_) _file_init_();
  const unsigned char * data = bytes;
  for(size_t i = 0;  i < length;  i ++){
    hash ^= data[i];
    hash *= UINT64_C(1099511628211);
  }
  return hash;
}

uint64_t x2c_fnv_file(uint64_t hash, String path, int * ok){
  if(! _init_guard_) _file_init_();
  File input = fopen(path, "rb");
  if(! input){
    * ok = 0;
    return hash;
  }
  unsigned char buffer[16384];
  size_t length;
  while((length = fread(buffer, 1, sizeof(buffer), input))) hash = x2c_fnv_bytes(hash, buffer, length);
  if(ferror(input)) * ok = 0;
  File_close(input);
  return hash;
}

String x2c_compiler_identity(void){
  if(! _init_guard_) _file_init_();
  return x2c_identity;
}

long worker_fork(void){
  if(! _init_guard_) _file_init_();
  fflush(NULL);
  pid_t pid = fork();
  return pid < 0 ? - 1 :(long) pid;
}

_Noreturn void worker_exit(int status){
  if(! _init_guard_) _file_init_();
  fflush(NULL);
  _exit(status);
}

int worker_wait_any(long * pids, int count, int * status){
  if(! _init_guard_) _file_init_();
  while(1){
    for(int i = 0;  i < count;  i ++){
      int raw;
      pid_t done = waitpid((pid_t) pids[i], & raw, WNOHANG);
      if(! done ||(done < 0 && errno == EINTR)) continue;
      * status = done < 0 ? - 1 : WIFEXITED(raw) ? WEXITSTATUS(raw) : WIFSIGNALED(raw) ? 128 + WTERMSIG(raw) : - 1;
      return i;
    }
    usleep(1000);
  }

}

int String_try_next(String, int *, int *);

String x2c_filename_hash(String filename){
  if(! _init_guard_) _file_init_();
  unsigned hash = 0;
  {
    char byte;
    String _x2c_macro_object_2 = filename;
    int _x2c_macro_cursor_2 = 0;
    int _x2c_macro_cursor_output_2;
    while(String_try_next(_x2c_macro_object_2, & _x2c_macro_cursor_2, & _x2c_macro_cursor_output_2)){
      byte = _x2c_macro_cursor_output_2;
      hash = hash * 31 +(unsigned char) byte;
    }

  }
  return String_printf(_20, hash);
}

void Path_remove_file(Path);

static void _x2c_defer_cleanup_0(void * _x2c_defer_opaque_0){
  _x2c_defer_env_0 * _x2c_defer_data_0 =(_x2c_defer_env_0 *) _x2c_defer_opaque_0;
  for(List rest =(*(List *) _x2c_defer_data_0->_x2c_defer_capture_0);  List_truth(rest);  rest = List_cddr(rest)) Path_remove_file(String_join(NULL, cons(String_var(Var_str(List_car(rest))), cons(String_var((*(String *) _x2c_defer_data_0->_x2c_defer_capture_1)), NULL))));
}

#undef _x2c_initializer_choice_6E6B8BB0_0_expanded
#undef _x2c_initializer_choice_6E6B8BB0_0
#undef _x2c_initializer_choice_6E6B8BB0_1_expanded
#undef _x2c_initializer_choice_6E6B8BB0_1
#undef _x2c_initializer_choice_6E6B8BB0_2_expanded
#undef _x2c_initializer_choice_6E6B8BB0_2
#undef _x2c_initializer_choice_6E6B8BB0_3_expanded
#undef _x2c_initializer_choice_6E6B8BB0_3
#undef _x2c_initializer_choice_6E6B8BB0_4_expanded
#undef _x2c_initializer_choice_6E6B8BB0_4
#undef _x2c_initializer_choice_6E6B8BB0_5_expanded
#undef _x2c_initializer_choice_6E6B8BB0_5
