/* auto-generated by x2c.  Do not edit! */

#pragma once

#ifndef __GUARD_0xD36B088C__
#define __GUARD_0xD36B088C__

#include "x2c.h"
typedef struct methodnames__Value{
  int number;
}
methodnames__Value;

int methodnames__Value_read(methodnames__Value _x2c_macro_value_0);

int methodnames__Value_direct(methodnames__Value value);


#endif /* __GUARD_0xD36B088C__ */
