/* auto-generated by x2c.  Do not edit! */

#include "c-annotation-macro.h"

Pair pair_make(int, int);

const char * pair_name(int);

int pair_sum(Pair);

int String_len(String);

int main(void){
  x2c_initialize();
  Pair pair = pair_make(3, 4);
  String name = String_new(pair_name(pair.left));
  printf("%d %s %d\n", pair_sum(pair), name, (int) String_len(name));
  return 0;
}

