/* auto-generated by x2c.  Do not edit! */

#define __GUARD_0xC0971362__
#include "x2c.h"

#include <stdio.h>
#include "c-linkage-split-values.h"
int scale(int value){
  return value * 7;
}

int main(void){
  x2c_initialize();
  printf("%d\n", scale(3));
  return 0;
}

