/* auto-generated by x2c.  Do not edit! */

#pragma once

#ifndef __GUARD_0xF93757E5__
#define __GUARD_0xF93757E5__

#include "x2c.h"
typedef struct Before{
  int value;
}
Before;

int before_size(Before value);

typedef struct After{
  int value;
}
After;

int after_size(After value);

int main(void);


#endif /* __GUARD_0xF93757E5__ */
