/* auto-generated by x2c.  Do not edit! */

#define __GUARD_0x02325D60__
#include "x2c.h"

#include "geo.h"
#include <stdio.h>
geo__Vec geo__Vec_new(double, double);

double geo__Vec_norm(geo__Vec);

double geo__span(geo__VecPair);

int main(void){
  x2c_initialize();
  geo__Vec v = geo__Vec_new(3.0, 4.0);
  geo__VecPair pair;
  pair.a.x = 1.0;
  pair.a.y = 0.0;
  pair.b.x = 0.0;
  pair.b.y = 2.0;
  printf("norm=%g span=%g\n", geo__Vec_norm(v), geo__span(pair));
  return 0;
}

