/* auto-generated by x2c.  Do not edit! */

#define __GUARD_0x7EA99A5F__
#include "x2c.h"

#include "geo.h"
typedef struct Grid{
  double span;
}
Grid;

double local_span(void){
  Grid g;
  g.span = 2.0;
  return g.span;
}

