/* auto-generated by x2c.  Do not edit! */

#define __GUARD_0x023233FA__
#include "x2c.h"

#include "x2c.h"
typedef unsigned char Byte;

typedef String Text;

static List _22, _20, _19, _17, _15, _10, _8, _7, _5, _3;

static String _13, _12, _11, _1;

static Var _21, _18, _16, _14, _9, _6, _4, _2, _0;

static int _init_guard_ = 0;

__attribute__((constructor, noinline, cold)) static void _file_init_(void);

static Byte increment(Byte value);

static Text echo(Text value);

static Var _x2c_func_adapt_0(Func _x2c_func_binding_0, const FuncArg * _x2c_func_argv_0);

static Var _x2c_func_adapt_1(Func _x2c_func_binding_1, const FuncArg * _x2c_func_argv_1);

__attribute__((constructor, noinline, cold)) static void _file_init_(void){
  x2c_initialize_protocols();
  if(_init_guard_) return;
  _init_guard_ = 1;
  _0 = Symbol_var(437126);
  _1 = String_new("Byte");
  _2 = String_var(_1);
  _3 = cons(_2, NULL);
  _4 = List_var(_3);
  _5 = cons(_4, NULL);
  _6 = List_var(_5);
  _7 = cons(_6, NULL);
  _8 = cons(_0, _7);
  _9 = List_var(_8);
  _10 = cons(_9, _3);
  _11 = String_new("increment");
  _12 = String_new("echo");
  _13 = String_new("Text");
  _14 = String_var(_13);
  _15 = cons(_14, NULL);
  _16 = List_var(_15);
  _17 = cons(_16, NULL);
  _18 = List_var(_17);
  _19 = cons(_18, NULL);
  _20 = cons(_0, _19);
  _21 = List_var(_20);
  _22 = cons(_21, _15);
}

static Byte increment(Byte value){
  return value + 1;
}

static Text echo(Text value){
  return value;
}

void install_bindings(Lisp lisp){
  if(! _init_guard_) _file_init_();
  Func _x2c_macro_callable_0 = Func_new(_x2c_func_adapt_0, _10);
  Lisp_bind(lisp, _11, _x2c_macro_callable_0);
  Lisp_bind(lisp, _12, Func_new(_x2c_func_adapt_1, _22));
}

static Var _x2c_func_adapt_0(Func _x2c_func_binding_0, const FuncArg * _x2c_func_argv_0){
  Byte a0 = Var_uchar(Var_convert(x2c_func_value_argument(_x2c_func_binding_0, _x2c_func_argv_0, 0, 30065), 30065));
  return Var_new(30065, increment(a0));
  ;
}

static Var _x2c_func_adapt_1(Func _x2c_func_binding_1, const FuncArg * _x2c_func_argv_1){
  Text a0 = Var_string(x2c_func_value_argument(_x2c_func_binding_1, _x2c_func_argv_1, 0, 1318210446));
  return String_var(echo(a0));
  ;
}

