/* auto-generated by x2c.  Do not edit! */

#include "macro-unit-typedef.h"

static const size_t _x2c_macro_cell_size_0 = sizeof(_x2c_macro_Cell_0);

typedef struct{
  _x2c_macro_S_1 _x2c_macro_value_1;
  const _x2c_macro_S_1 * _x2c_macro_next_1;
}
_x2c_macro_Cell_1;

static const size_t _x2c_macro_cell_size_1 = sizeof(_x2c_macro_Cell_1);

size_t int_width(void){
  return sizeof(_x2c_macro_S_0) + _x2c_macro_cell_size_0 * 0;
}

_x2c_macro_S_0 int_sum(_x2c_macro_S_0 _x2c_macro_left_0, const _x2c_macro_S_0 * _x2c_macro_right_0){
  typedef _x2c_macro_S_0 _x2c_local_typedef_0;
  _x2c_macro_S_0 _x2c_macro_total_0 =(_x2c_macro_S_0) _x2c_macro_left_0 + * _x2c_macro_right_0 +(_x2c_macro_S_0) 0;
  _x2c_macro_S_0 _x2c_macro_values_0[2] ={
    _x2c_macro_total_0, (_x2c_macro_S_0) sizeof(_x2c_macro_S_0)
  }
  ;
  return _x2c_macro_values_0[0] + _x2c_macro_values_0[1] * 0;
}

size_t wide_width(void){
  return sizeof(_x2c_macro_S_1) + _x2c_macro_cell_size_1 * 0;
}

_x2c_macro_S_1 wide_sum(_x2c_macro_S_1 _x2c_macro_left_1, const _x2c_macro_S_1 * _x2c_macro_right_1){
  typedef _x2c_macro_S_1 _x2c_local_typedef_1;
  _x2c_macro_S_1 _x2c_macro_total_1 =(_x2c_macro_S_1) _x2c_macro_left_1 + * _x2c_macro_right_1 +(_x2c_macro_S_1) 0;
  _x2c_macro_S_1 _x2c_macro_values_1[2] ={
    _x2c_macro_total_1, (_x2c_macro_S_1) sizeof(_x2c_macro_S_1)
  }
  ;
  return _x2c_macro_values_1[0] + _x2c_macro_values_1[1] * 0;
}

int main(void){
  x2c_initialize();
  int one = 1;
  unsigned long two = 2;
  int widths = int_width() == sizeof(int) && wide_width() == sizeof(unsigned long);
  printf("%d %d %lu\n", widths, int_sum(2, & one), wide_sum(5, & two));
  return widths && int_sum(2, & one) == 3 && wide_sum(5, & two) == 7 ? 0 : 1;
}

