#define _x2c_initializer_choice_0E898A17_0_expanded(_x2c_static_input_0) static void _x2c_static_initialize_0(void){\
  _x2c_static_input_0;\
}
#define _x2c_initializer_choice_0E898A17_0(_x2c_static_input_0) _x2c_initializer_choice_0E898A17_0_expanded(_x2c_static_input_0)
/* auto-generated by x2c.  Do not edit! */

#include "macro-export-transitive.h"

int delivered;

_x2c_initializer_choice_0E898A17_0((delivered = 7 + mid_value))
int summed = 6;

int replaced = 8;

static int _init_guard_ = 0;

__attribute__((constructor, noinline, cold)) static void _file_init_(void);

__attribute__((constructor, noinline, cold)) static void _file_init_(void){
  x2c_initialize_protocols();
  if(_init_guard_) return;
  _init_guard_ = 1;
  _x2c_static_initialize_0();
}

#undef _x2c_initializer_choice_0E898A17_0_expanded
#undef _x2c_initializer_choice_0E898A17_0
