#define _x2c_initializer_choice_47E55BD0_0_expanded(_x2c_static_input_0) static void _x2c_static_initialize_0(void){\
  _x2c_static_input_0;\
}
#define _x2c_initializer_choice_47E55BD0_0(_x2c_static_input_0) _x2c_initializer_choice_47E55BD0_0_expanded(_x2c_static_input_0)
/* auto-generated by x2c.  Do not edit! */

#include "match-arm-transfer-regions.h"

#include "exception.h"

static List _17, _16, _15, _13, _12, _11, _7, _5, _3, _1;

static Var _14, _10, _9, _8, _6, _4, _2, _0;

static int rounds;

_x2c_initializer_choice_47E55BD0_0((rounds = 0))
int arms = 0;

static int _init_guard_ = 0;

__attribute__((constructor)) static void _file_init_(void);

static int deferred(Var item);

static int guarded(List items);

typedef struct _x2c_defer_env_0{
  const void * _x2c_defer_capture_0;
}
_x2c_defer_env_0;

static void _x2c_defer_cleanup_0(void * _x2c_defer_opaque_0);

Var Symbol_var(Symbol);

List cons(Var, List);

Var List_var(List);

__attribute__((constructor)) static void _file_init_(void){
  x2c_initialize_protocols();
  if(_init_guard_) return;
  _init_guard_ = 1;
  _0 = Symbol_var(731488);
  _1 = cons(_0, NULL);
  _2 = Symbol_var(1268320);
  _3 = cons(_2, NULL);
  _4 = Symbol_var(1287136);
  _5 = cons(_4, NULL);
  _6 = Symbol_var(32784740);
  _7 = cons(_6, NULL);
  _8 = List_var(_3);
  _9 = List_var(_1);
  _10 = List_var(_7);
  _11 = cons(_10, NULL);
  _12 = cons(_9, _11);
  _13 = cons(_8, _12);
  _14 = List_var(_5);
  _15 = cons(_9, NULL);
  _16 = cons(_14, _15);
  _17 = cons(_9, _16);
  _x2c_static_initialize_0();
}

List Var_list(Var);

static int deferred(Var item){
  int n = 0;
  {
  _x2c_defer_env_0 _x2c_defer_env_1 = {._x2c_defer_capture_0 =(const void *) & n};

  X2CCleanup _x2c_defer_record_0 = {
    .fn = _x2c_defer_cleanup_0,
    .env = & _x2c_defer_env_1
  };
  x2c_cleanup_push(&_x2c_defer_record_0);
  {

  {
    List _x2c_match_expr = Var_list(item);
    MatchCaptureBuffer _x2c_match_capture = { 0 };

    switch (Var_symbol(car(_x2c_match_expr))) {
      case 731488: ;
    { List _x2c_match_cursor;
    if (_x2c_match_expr && _x2c_match_expr->car.u64 == 9224497936762349920ULL && (_x2c_match_cursor = _x2c_match_expr->cdr, 1) && !_x2c_match_cursor) {break;
    break; } } default: ;
    n = 1;
    break;

    }
  }
{
      int _x2c_return_value_0 = n;
      {
        x2c_cleanup_leave(& _x2c_defer_record_0);
        return _x2c_return_value_0;
      }

    }

  }
  x2c_cleanup_leave(& _x2c_defer_record_0);

}
}

int List_try_next(List, List *, Var *);

static int guarded(List items){
  int volatile kept = 0;
  {
    Var item;
    List _x2c_macro_object_0 = items;
    List _x2c_macro_cursor_0 = _x2c_macro_object_0;
    Var _x2c_macro_cursor_output_0;
    while(List_try_next(_x2c_macro_object_0, & _x2c_macro_cursor_0, & _x2c_macro_cursor_output_0)){
      item = _x2c_macro_cursor_output_0;
      {
        {
          ExceptionFrame _x2c_exception_frame_0;
          x2c_exception_push(& _x2c_exception_frame_0);
          if (!sigsetjmp(_x2c_exception_frame_0.env, 0)){

  {
    List _x2c_match_expr = Var_list(item);
    MatchCaptureBuffer _x2c_match_capture = { 0 };

    switch (Var_symbol(car(_x2c_match_expr))) {
      case 1268320: ;
            { List _x2c_match_cursor;
            if (_x2c_match_expr && _x2c_match_expr->car.u64 == 9224497936762886752ULL && (_x2c_match_cursor = _x2c_match_expr->cdr, 1) && !_x2c_match_cursor) {{
              if(x2c_exception_claim(& _x2c_exception_frame_0)){
                rounds ++;
              }
              x2c_exception_leave(& _x2c_exception_frame_0);
              continue;
            }
            break; } } case 731488: ;
            { List _x2c_match_cursor;
            if (_x2c_match_expr && _x2c_match_expr->car.u64 == 9224497936762349920ULL && (_x2c_match_cursor = _x2c_match_expr->cdr, 1) && !_x2c_match_cursor) {break;
            break; } } case 1287136: ;
            { List _x2c_match_cursor;
            if (_x2c_match_expr && _x2c_match_expr->car.u64 == 9224497936762905568ULL && (_x2c_match_cursor = _x2c_match_expr->cdr, 1) && !_x2c_match_cursor) {{
              int _x2c_return_value_1 = kept + 1000;
              {
                if(x2c_exception_claim(& _x2c_exception_frame_0)){
                  rounds ++;
                }
                x2c_exception_leave(& _x2c_exception_frame_0);
                return _x2c_return_value_1;
              }

            }
            break; } } default: ;
            kept += 100;
            break;

    }
  }
arms ++;
          }
          else {x2c_exception_landed(& _x2c_exception_frame_0);
          {
            if(x2c_exception_claim(& _x2c_exception_frame_0)){
              rounds ++;
            }
            x2c_exception_leave(& _x2c_exception_frame_0);
            __builtin_unreachable();
          }

        }
        if(x2c_exception_claim(& _x2c_exception_frame_0)){
          rounds ++;
        }
        x2c_exception_leave(& _x2c_exception_frame_0);
      }
      kept ++;
    }

  }

}
return kept;
}

int main(void){
  x2c_initialize();
  if(! _init_guard_) _file_init_();
  printf("%d %d\n", deferred(List_var(_1)), deferred(List_var(_7)));
  printf("%d %d %d\n", guarded(_13), rounds, arms);
  printf("%d %d\n", guarded(_17), rounds);
  return 0;
}

static void _x2c_defer_cleanup_0(void * _x2c_defer_opaque_0){
  _x2c_defer_env_0 * _x2c_defer_data_0 =(_x2c_defer_env_0 *) _x2c_defer_opaque_0;
  (*(volatile int *) _x2c_defer_data_0->_x2c_defer_capture_0) ++;
}

#undef _x2c_initializer_choice_47E55BD0_0_expanded
#undef _x2c_initializer_choice_47E55BD0_0
