/* auto-generated by x2c.  Do not edit! */

#include "match-loop-control.h"

static List _19, _18, _17, _15, _13, _10, _8, _6, _5, _3, _1;

static Var _16, _14, _12, _11, _9, _7, _4, _2, _0;

static int _init_guard_ = 0;

__attribute__((constructor)) static void _file_init_(void);

Var Symbol_var(Symbol);

List cons(Var, List);

Var List_var(List);

__attribute__((constructor)) static void _file_init_(void){
  x2c_initialize_protocols();
  if(_init_guard_) return;
  _init_guard_ = 1;
  _0 = Symbol_var(982);
  _1 = cons(_0, NULL);
  _2 = List_var(_1);
  _3 = cons(_2, NULL);
  _4 = List_var(_3);
  _5 = cons(_4, NULL);
  _6 = cons(_4, _5);
  _7 = Symbol_var(1268320);
  _8 = cons(_7, NULL);
  _9 = List_var(_8);
  _10 = cons(_9, NULL);
  _11 = List_var(_10);
  _12 = Symbol_var(731488);
  _13 = cons(_12, NULL);
  _14 = List_var(_13);
  _15 = cons(_14, NULL);
  _16 = List_var(_15);
  _17 = cons(_11, NULL);
  _18 = cons(_16, _17);
  _19 = cons(_11, _18);
}

int List_try_next(List, List *, Var *);

List Var_list(Var);

int main(void){
  x2c_initialize();
  if(! _init_guard_) _file_init_();
  List break_inputs = _6;
  int matched = 0, after = 0;
  {
    Var item;
    List _x2c_macro_object_0 = break_inputs;
    List _x2c_macro_cursor_0 = _x2c_macro_object_0;
    Var _x2c_macro_cursor_output_0;
    while(List_try_next(_x2c_macro_object_0, & _x2c_macro_cursor_0, & _x2c_macro_cursor_output_0)){
      item = _x2c_macro_cursor_output_0;
      {
        List value = Var_list(item);

  {
    List _x2c_match_expr = value;
    MatchCaptureBuffer _x2c_match_capture = { 0 };

    switch (0) {
      default: ;  static MatchCaptureSite _x2c_match_site_0;  if (x2c_match_site_try_capture(& _x2c_match_site_0, _x2c_match_expr, List_var(_3), &_x2c_match_capture)) {{
          matched ++;  break;
        }
        break;
      }

    }
  }
after ++;
    }

  }

}
List continue_inputs = _19;  int visited = 0, accepted = 0; {
  Var item;  List _x2c_macro_object_1 = continue_inputs;  List _x2c_macro_cursor_1 = _x2c_macro_object_1;  Var _x2c_macro_cursor_output_1;  while(List_try_next(_x2c_macro_object_1, & _x2c_macro_cursor_1, & _x2c_macro_cursor_output_1)){
    item = _x2c_macro_cursor_output_1; {
      List value = Var_list(item);  visited ++;
  {
    List _x2c_match_expr = value;
    MatchCaptureBuffer _x2c_match_capture = { 0 };
    switch (0) {
      default: ;  static MatchCaptureSite _x2c_match_site_1;  if (x2c_match_site_try_capture(& _x2c_match_site_1, _x2c_match_expr, List_var(_10), &_x2c_match_capture)) {continue;  break;
    }

    }
  }
accepted ++;
  }

}
}
printf("%d %d %d %d\n", matched, after, visited, accepted);  return matched == 2 && after == 2 && visited == 3 && accepted == 1 ? 0 : 1;
}

