/* auto-generated by x2c.  Do not edit! */

#define __GUARD_0xB3A48827__
#include "x2c.h"

#include "x2c.h"
typedef int MetaCount;

static double native_total(double value);

static int class_value(MetaCount value);

MetaCount MetaCount_new(int initial){
  int value = initial;
  return value;
}

Var MetaCount_var(MetaCount value){
  return int_var((int) value);
}

MetaCount Var_metacount(Var value){
  return(MetaCount) Var_int(Var_convert(value, 3453797));
}

static double native_total(double value){
  return sin(value) + sqrt(4.0);
}

static int class_value(MetaCount value){
  return value + 1;
}

int main(int argc, char * * argv){
  x2c_initialize();
  (void) argv;
  printf("%.1f %.1f %d\n", ((double) 0x1p+1L), native_total(argc - 1), 7);
  return 0;
}

