/* Native and meta scalar payloads and mutable containers agree. */
#include "x2c.x"

$(import "meta-core-operations.xmacro")

int main(int argc, char **argv) {
  (void) argv;
  printf("%d %d\n", $core_String_intern(0),
    core_String_intern(argc - 1));
  printf("%d %d\n", $core_String_parse(0),
    core_String_parse(argc - 1));
  printf("%d %d\n", $core_String_parse_char(0),
    core_String_parse_char(argc - 1));
  printf("%d %d\n", $core_String_withindex(0),
    core_String_withindex(argc - 1));
  printf("%d %d\n", $core_String_truth(0),
    core_String_truth(argc - 1));
  printf("%d %d\n", $core_Array_capacity(0),
    core_Array_capacity(argc - 1));
  printf("%d %d\n", $core_Array_remslice(0),
    core_Array_remslice(argc - 1));
  printf("%d %d\n", $core_Array_setslice(0),
    core_Array_setslice(argc - 1));
  printf("%d %d\n", $core_Array_splice(0),
    core_Array_splice(argc - 1));
  printf("%d %d\n", $core_Array_updateindex(0),
    core_Array_updateindex(argc - 1));
  printf("%d %d\n", $core_Array_postfixindex(0),
    core_Array_postfixindex(argc - 1));
  printf("%d %d\n", $core_Array_clear(0),
    core_Array_clear(argc - 1));
  printf("%d %d\n", $core_Array_heap_push(0),
    core_Array_heap_push(argc - 1));
  printf("%d %d\n", $core_Array_heapify(0),
    core_Array_heapify(argc - 1));
  printf("%d %d\n", $core_Array_pop(0),
    core_Array_pop(argc - 1));
  printf("%d %d\n", $core_Array_resize(0),
    core_Array_resize(argc - 1));
  printf("%d %d\n", $core_Array_truncate(0),
    core_Array_truncate(argc - 1));
  printf("%d %d\n", $core_Map_new_capacity(0),
    core_Map_new_capacity(argc - 1));
  printf("%d %d\n", $core_Map_updateindex(0),
    core_Map_updateindex(argc - 1));
  printf("%d %d\n", $core_Map_postfixindex(0),
    core_Map_postfixindex(argc - 1));
  printf("%d %d\n", $core_Map_set(0),
    core_Map_set(argc - 1));
  printf("%d %d\n", $core_Var_array(0),
    core_Var_array(argc - 1));
  printf("%d %d\n", $core_Var_map(0),
    core_Var_map(argc - 1));
  printf("%d %d\n", $core_Var_string(0),
    core_Var_string(argc - 1));
  printf("%d %d\n", $core_Var_symbol(0),
    core_Var_symbol(argc - 1));
  printf("%d %d\n", $core_Var_compare(0),
    core_Var_compare(argc - 1));
  printf("%d %d\n", $core_Var_contains(0),
    core_Var_contains(argc - 1));
  printf("%d %d\n", $core_Var_hash(0),
    core_Var_hash(argc - 1));
  printf("%d %d\n", $core_Var_same(0),
    core_Var_same(argc - 1));
  printf("%d %d\n", $core_Var_is_atom(0),
    core_Var_is_atom(argc - 1));
  printf("%d %d\n", $core_Var_is_atom_binder(0),
    core_Var_is_atom_binder(argc - 1));
  printf("%d %d\n", $core_Var_is_binder(0),
    core_Var_is_binder(argc - 1));
  printf("%d %d\n", $core_Var_is_list_binder(0),
    core_Var_is_list_binder(argc - 1));
  printf("%d %d\n", $core_Var_is_match_op(0),
    core_Var_is_match_op(argc - 1));
  printf("%d %d\n", $core_Var_is_floating(0),
    core_Var_is_floating(argc - 1));
  printf("%d %d\n", $core_Var_is_integer(0),
    core_Var_is_integer(argc - 1));
  printf("%d %d\n", $core_Var_is_object(0),
    core_Var_is_object(argc - 1));
  printf("%d %d\n", $core_Var_is_wide(0),
    core_Var_is_wide(argc - 1));
  printf("%d %d\n", $core_Var_is_nil(0),
    core_Var_is_nil(argc - 1));
  printf("%d %d\n", $core_Var_is_null(0),
    core_Var_is_null(argc - 1));
  printf("%d %d\n", $core_Var_add(0),
    core_Var_add(argc - 1));
  printf("%d %d\n", $core_Var_sub(0),
    core_Var_sub(argc - 1));
  printf("%d %d\n", $core_Var_mul(0),
    core_Var_mul(argc - 1));
  printf("%d %d\n", $core_Var_div(0),
    core_Var_div(argc - 1));
  printf("%d %d\n", $core_Var_mod(0),
    core_Var_mod(argc - 1));
  printf("%d %d\n", $core_Var_neg(0),
    core_Var_neg(argc - 1));
  printf("%d %d\n", $core_Var_truth(0),
    core_Var_truth(argc - 1));
  printf("%d %d\n", $core_Var_setindex(0),
    core_Var_setindex(argc - 1));
  printf("%d %d\n", $core_Var_updateindex(0),
    core_Var_updateindex(argc - 1));
  printf("%d %d\n", $core_Var_postfixindex(0),
    core_Var_postfixindex(argc - 1));
  printf("%d %d\n", $core_List_truth(0),
    core_List_truth(argc - 1));
  printf("%d %d\n", $core_Var_char(0),
    core_Var_char(argc - 1));
  printf("%d %d\n", $core_Var_short(0),
    core_Var_short(argc - 1));
  printf("%d %d\n", $core_Var_int(0),
    core_Var_int(argc - 1));
  printf("%d %d\n", $core_Var_long(0),
    core_Var_long(argc - 1));
  printf("%d %d\n", $core_Var_long_long(0),
    core_Var_long_long(argc - 1));
  printf("%d %d\n", $core_Var_unsigned(0),
    core_Var_unsigned(argc - 1));
  printf("%d %d\n", $core_Var_ushort(0),
    core_Var_ushort(argc - 1));
  printf("%d %d\n", $core_Var_uchar(0),
    core_Var_uchar(argc - 1));
  printf("%d %d\n", $core_Var_uint(0),
    core_Var_uint(argc - 1));
  printf("%d %d\n", $core_Var_ulong(0),
    core_Var_ulong(argc - 1));
  printf("%d %d\n", $core_Var_ulong_long(0),
    core_Var_ulong_long(argc - 1));
  printf("%d %d\n", $core_Var_float(0),
    core_Var_float(argc - 1));
  printf("%d %d\n", $core_Var_double(0),
    core_Var_double(argc - 1));
  printf("%d %d\n", $core_Var_long_double(0),
    core_Var_long_double(argc - 1));
  printf("%d %d\n", $core_Var_long_value(0),
    core_Var_long_value(argc - 1));
  printf("%d %d\n", $core_Var_ulong_value(0),
    core_Var_ulong_value(argc - 1));
  printf("%d %d\n", $core_Var_long_long_value(0),
    core_Var_long_long_value(argc - 1));
  printf("%d %d\n", $core_Var_ulong_long_value(0),
    core_Var_ulong_long_value(argc - 1));
  printf("%d %d\n", $core_Var_long_double_value(0),
    core_Var_long_double_value(argc - 1));
  printf("%d %d\n", $core_Symbol_first(0),
    core_Symbol_first(argc - 1));
  printf("%d %d\n", $core_Symbol_last(0),
    core_Symbol_last(argc - 1));
  printf("%d %d\n", $core_Var_list(0), core_Var_list(argc - 1));
  return 0;
}
