/* auto-generated by x2c.  Do not edit! */

#define __GUARD_0x5E5861BD__
#include "x2c.h"

#include "x2c.h"
#include "ordinary-interface-provider.h"
static List _13, _12, _8, _7, _2;

static String _14, _10, _5, _3, _0;

static Var _11, _9, _6, _4, _1;

static int _init_guard_ = 0;

__attribute__((constructor, noinline, cold)) static void _file_init_(void);

__attribute__((constructor, noinline, cold)) static void _file_init_(void){
  x2c_initialize_protocols();
  if(_init_guard_) return;
  _init_guard_ = 1;
  _0 = String_new("untouched");
  _1 = String_var(_0);
  _2 = cons(_1, NULL);
  _3 = String_new("abc");
  _4 = String_var(_3);
  _5 = String_new("de");
  _6 = String_var(_5);
  _7 = cons(_6, NULL);
  _8 = cons(_4, _7);
  _9 = List_var(_8);
  _10 = String_new("tail");
  _11 = String_var(_10);
  _12 = cons(_11, NULL);
  _13 = cons(_9, _12);
  _14 = String_new("included");
}

int main(void){
  x2c_initialize();
  if(! _init_guard_) _file_init_();
  List other = _2;
  List first = _8;
  List second = _8;
  List direct = _8;
  List nested = _13;
  String text = _14;
  printf("%d %d %d %d %d %d %d %s %s %s %s\n", 5, 7, 9, 41 + 1, 17, 19, 23, String_str(List_repr(first)), String_str(List_repr(other)), String_str(List_repr(nested)), String_str(text));
  return(void *) first !=(void *) second ||(void *) first !=(void *) direct ||(void *) Var_list(List_car(nested)) !=(void *) first;
}

