/* auto-generated by x2c.  Do not edit! */

#include "private-extern-declaration.h"

extern char * * environ;

int main(void){
  x2c_initialize();
  printf("environment %s\n", environ && environ[0] ? "visible" : "missing");
  return 0;
}

