/*  linked-meta.x -- shipped `meta` code compiled into the compiler

    Generated by tools/gen-linked-meta.sh; do not edit. Bodied `meta`
    functions and initialized static values from lib/meta.x and
    imported `.xmacro` files appear without their `meta` markers,
    so their functions and initializers execute as native code.
    `Compiler.bind_linked_meta` binds an imported definition to its
    copy only when the two texts hash the same, so a compiler built
    before a `.xmacro` edit stages the edited definition. The
    lib/meta.x builders with a run-time form bind to the runtime's
    own definitions and have no copy here.
*/

#pragma once

#include "x2c.x"
#include "meta.x"

/* --- lib/meta.x ---------------------------------------------------------- */

/** Returns the expression `receiver.name`. */
List x2c_expr_field(List receiver, String name) {
  List checked = x2c_ident(name);
  return %(expr () (op . $receiver (${checked[1]})));
}

/** Returns `expression` cast to `type`, which is a declared type rather
    than syntax. A generator needs it where the value it holds and the
    parameter it reaches differ in width or sign. */
List x2c_expr_cast(List type, List expression) {
  List parts = x2c_type_parts(type);
  return %(expr $type
    (cast (decl ${parts[0]} (bindings (bind () ${parts[1]}))) $expression));
}

/** Declares `name` with `type` and an optional initializer. */
List x2c_decl_make(List type, Var name, List initializer) {
  List parts = x2c_type_parts(type);
  List binding = %(bind ($name) ${parts[1]});
  if (initializer) binding = %(op = $binding $initializer);
  return %(declare ${parts[0]} (bindings $binding));
}

/** Returns a parameter named `name` with `type`. */
List x2c_param_make(List type, Var name) {
  List parts = x2c_type_parts(type);
  return %(param ${parts[0]} (bind ($name) ${parts[1]}));
}

static Var _meta_initializer(List node) {
  match (node) {
    case %(expr ? (literal ? ?text)): return text;
    case %(?text): return text;
  }
  return node;
}

static void _meta_fail(String message, Var value) {
  x2c_diagnostic_fail(message, %("value: ${value.repr()}"));
}

static List _meta_member(List node) {
  match (node) {
    case %(op = (?name) ?value):
      return %($name ${_meta_initializer(value)});
    case %(?name): return %($name ());
  }
  _meta_fail("x2c.type.members found an unreadable member", node);
  return %();
}

/** Returns enum members as `(name value)` rows in declaration order.
    An implicit value is nil; a literal value retains its spelling. */
List x2c_type_members(List type) {
  List resolved = x2c_type_resolve(type);
  if (resolved.car() != <enum>)
    _meta_fail("x2c.type.members requires an enum Type", type);
  List members = resolved.reverse().car();
  List rows = %();
  foreach (List member, members) rows = cons(_meta_member(member), rows);
  return rows.reverse();
}

/* --- src/builtin-errors.xmacro ------------------------------------------- */

static Map _builtin_error_rows(void) => {
  "scope.arity" :
  macro Statement() {
    x2c_diagnostic_fail("$scope accepts zero or one destination", %());
  },
  "foreach.bindings" :
  macro Statement() {
    x2c_diagnostic_fail(
      "foreach requires one binding or a two-name destructuring declaration",
      %());
  },
  "foreach.type" :
  macro Statement(Expr $printable) {
    x2c_diagnostic_fail(
      "type " + $printable.repr() + " is not iterable",
      %("declare an Iter protocol adoption or iterate an Iter directly"));
  },
  "class.enum" :
  macro Statement(Expr $owner) {
    x2c_diagnostic_fail(
      %"class ${$owner} cannot take an enum value " +
      "representation: Var has no fixed tag for an enum",
      %("give the enum a typedef and name that typedef instead"));
  },
  "class.ctor" :
  macro Statement(Expr $owner) {
    x2c_diagnostic_fail(
      %"class ${$owner} requires an explicit constructor", %());
  },
  "class.comparison" :
  macro Statement(Expr $owner) {
    x2c_diagnostic_fail(
      %"value class ${$owner} requires compatible equal " +
      "and hash methods", %());
  },
  "class.init" :
  macro Statement(Expr $owner, Expr $suffix) {
    x2c_diagnostic_fail(
      %"class ${$owner} requires void ${$owner}.init(${$owner}${$suffix}",
      %());
  },
  "binding.sealed" :
  macro Statement(Expr $group) {
    x2c_diagnostic_fail(
      "native Lisp binding appears after its group was installed",
      %("group: ${$group}"));
  },
  "binding.duplicate" :
  macro Statement(Expr $group, Expr $name) {
    x2c_diagnostic_fail(
      "duplicate native Lisp binding name",
      %("group: ${$group}" "name: ${$name}"));
  },
  "binding.name" :
  macro Statement(Expr $node) {
    x2c_diagnostic_fail(
      "native Lisp binding name requires a String literal",
      %("value: ${$node.repr()}"));
  },
  "binding.group" :
  macro Statement(Expr $group) {
    x2c_diagnostic_fail(
      "unknown native Lisp binding group", %("group: ${$group}"));
  },
  "try.cleanup" :
  macro Statement() {
    x2c_diagnostic_fail("try cleanup must be lowered statements", %());
  },
};

static List _builtin_error_expand(String key, List arguments) {
  Map rows = _builtin_error_rows();
  Var row = rows[key];
  if (row is void)
    x2c_diagnostic_fail(%"unknown builtin error '$key'", %());
  Macro selected = row;
  if (arguments.len() != selected.assoc(<parameters>).list().len())
    x2c_diagnostic_fail(%"wrong argument count for builtin error '$key'", %());
  return %(${Macro_apply(selected, arguments)});
}

/* --- lib/func-errors.xmacro ---------------------------------------------- */

static Map _func_error_rows(void) => {

  "apply.args" :
  macro Statement() {
    raise %(bad-arg (operation "Func.apply"));
  },

  "apply.arity" :
  macro Statement(Expr $sig, Expr $expected, Expr $actual) {
    raise %(bad-arity (sig ${$sig}) (expected ${$expected}) (actual ${$actual}));
  },

  "arg.value" :
  macro Statement(Expr $sig, Expr $index) {
    raise %(bad-types (sig ${$sig}) (index ${$index}) (want value));
  },

  "arg.void" :
  macro Statement(Expr $sig, Expr $index) {
    raise %(void-op (sig ${$sig}) (index ${$index}));
  },

  "apply.index" :
  macro Statement(Expr $index) {
    raise %(bad-arg (operation "Func.apply") (index ${$index}));
  },

  "arg.convert" :
  macro Statement(Expr $code, Expr $sig, Expr $index, Expr $want, Expr $lower) {
    raise %(${$code} (sig ${$sig}) (index ${$index}) (want ${$want})
            (cause ${$lower}));
  },

  "arg.type" :
  macro Statement(Expr $sig, Expr $index, Expr $actual, Expr $want) {
    raise %(bad-types (sig ${$sig}) (index ${$index}) (actual ${$actual})
            (want ${$want}));
  },

  "arg.pointer" :
  macro Statement(Expr $sig, Expr $index, Expr $actual) {
    raise %(bad-types (sig ${$sig}) (index ${$index}) (actual ${$actual})
            (want pointer));
  },

  "arg.unboxed" :
  macro Statement(Expr $sig, Expr $index, Expr $source) {
    raise %(bad-types (sig ${$sig}) (index ${$index}) (source ${$source})
            (want value));
  },

  "arg.ref" :
  macro Statement(Expr $sig, Expr $index, Expr $source, Expr $want) {
    raise %(bad-types (sig ${$sig}) (index ${$index}) (source ${$source})
            (want ${$want}));
  },

  "bind.sig" :
  macro Statement(Expr $sig) {
    raise %(bad-sig (sig ${$sig}));
  },

  "context.source" :
  macro Statement() {
    raise %(bad-arg (operation "Func.new_context"));
  },

  "context.size" :
  macro Statement(Expr $size) {
    raise %(size-limit (operation "Func.new_context") (size ${$size}));
  },

  "signature.null" :
  macro Statement() {
    raise %(bad-arg (operation "Func.signature"));
  },

  "context.null" :
  macro Statement() {
    raise %(bad-arg (operation "Func.context"));
  },

  "box.type" :
  macro Statement(Expr $actual) {
    raise %(bad-types (want func) (actual ${$actual}));
  }
};

static List _func_error_expand(String key, List arguments) {
  Map rows = _func_error_rows();
  Var row = rows[key];
  if (row == void)
    x2c_diagnostic_fail(%"unknown Func error '$key'", %());
  Macro selected = row;
  return %(${Macro_apply(selected, arguments)});
}

/* --- src/grammar.xmacro -------------------------------------------------- */

static List source_return_type(List node) {
  match (node) case %(return ?type ?): return type;
  return NULL;
}

static List source_conditional_statement(void) =>
  %((!or if while do for switch try match with foreach finally) *);

static List source_any_lambda(void) => %(expr ? (lambda *));

static List source_cast_content(List parts) => cons(<cast>, parts);

static List source_generic_content(List parts) => cons(<generic>, parts);

static List source_va_arg_content(List parts) => cons(<va-arg>, parts);

static List source_commas_content(List rows) => cons(<commas>, rows);

static List source_slice_content(List parts) => cons(<slice>, parts);

static List source_composite_content(List rows) =>
  %(composite ${source_commas_content(rows)});

static List source_string_content(List rows) => cons(<segments>, rows);

static List source_operator_content(List parts) => cons(<op>, parts);

static List source_operator_expression(List type, List parts) =>
  %(expr $type ${source_operator_content(parts)});

static List source_postfix_content(List parts) => cons(<postfix>, parts);

static List source_postfix_expression(List type, List parts) =>
  %(expr $type ${source_postfix_content(parts)});

static List source_content_pattern(Macro shape, List names) =>
  shape.pattern(names).caddr();

static List source_call_content(
  Macro call, List callee, List arguments) {
  List pattern = call.pattern(%(?callee *arguments));
  return pattern.caddr().list().replace(
    %((?callee $callee) (*arguments $arguments)));
}

static List source_return_content(List fields) =>
  cons(<return>, fields);

static List source_block_content(List fields) =>
  cons(<block>, fields);

static List source_identifier_content(List fields) =>
  cons(<ident>, fields);

static List source_literal_content(List fields) =>
  cons(<literal>, fields);

static List source_declarator_row(List fields) =>
  %(!or (bind @fields) (op = (bind @fields) ?));

static List source_pattern_with(
    Macro shape, List names, List replacements) {
  List pattern = shape.pattern(names);
  if (replacements) pattern = pattern.replace(replacements);
  match (pattern) case %(expr ? ?body): return %(!or $pattern $body);
  return pattern;
}

static List source_pattern(Macro shape, List names) {
  List pattern = shape.pattern(names);
  match (pattern) case %(expr ? ?body): return %(!or $pattern $body);
  return pattern;
}

static Var source_expression(Var value) {
  while (1) {
    match (value) {
      case %(expr ? (parens ?inner)): value = inner;
      case %(expr ? (cast ? ?inner)): value = inner;
      case %(parens ?inner): value = inner;
      case %(cast ? ?inner): value = inner;
      default: return value;
    }
  }
}

/** Returns the error handler the parser introduced for the catch arms of
    the parsed try `node`, or NULL for a try without catches. The arms read
    their captures through it, and no source form writes it. */
static List catch_handle(List node) {
  match (node) case %(try ? (catchcases ? ?handle) ?): return handle;
  return NULL;
}

static List retain_catch_handle(List rebuilt, List handle) {
  Var marker = rebuilt.caddr().caddr();
  return rebuilt.search_replace(%(!quote $marker), handle);
}

/* --- lib/job-errors.xmacro ----------------------------------------------- */

static Map _job_error_rows(void) => {

  "start.alloc" :
  macro Statement() {
    raise %(alloc-fail);
  },

  "start.empty" :
  macro Statement() {
    raise %(bad-arg (operation "Job.start") (why "empty command"));
  },

  "start.missing" :
  macro Statement(Expr $program, Expr $error) {
    raise %(not-found (operation "Job.start") (program ${$program})
            (errno ${$error}));
  },

  "start.program" :
  macro Statement(Expr $program, Expr $error) {
    raise %(io-fail (operation "Job.start") (program ${$program})
            (errno ${$error}));
  },

  "start.path" :
  macro Statement(Expr $path, Expr $error) {
    raise %(io-fail (operation "Job.start") (path ${$path}) (errno ${$error}));
  },

  "start.io" :
  macro Statement(Expr $error) {
    raise %(io-fail (operation "Job.start") (errno ${$error}));
  },

  "job.started" :
  macro Statement(Expr $operation) {
    raise %(bad-arg (operation ${$operation}) (why "the job has started"));
  },

  "options.key" :
  macro Statement() {
    raise %(bad-arg (operation "Job.options")
            (why "option keys are atoms"));
  },

  "options.unknown" :
  macro Statement(Expr $name) {
    raise %(bad-arg (operation "Job.options") (option ${$name}));
  },

  "check.both" :
  macro Statement(Expr $command, Expr $status, Expr $output, Expr $errors) {
    raise %(cmd-fail (command ${$command}) (status ${$status})
            (output ${$output}) (errors ${$errors}));
  },

  "check.output" :
  macro Statement(Expr $command, Expr $status, Expr $output) {
    raise %(cmd-fail (command ${$command}) (status ${$status})
            (output ${$output}));
  },

  "check.errors" :
  macro Statement(Expr $command, Expr $status, Expr $errors) {
    raise %(cmd-fail (command ${$command}) (status ${$status})
            (errors ${$errors}));
  },

  "check.status" :
  macro Statement(Expr $command, Expr $status) {
    raise %(cmd-fail (command ${$command}) (status ${$status}));
  },

  "text.nul" :
  macro Statement(Expr $operation) {
    raise %(bad-arg (operation ${$operation}) (why "embedded NUL"));
  },

  "wait.unstarted" :
  macro Statement() {
    raise %(bad-arg (operation "Job.wait_any")
            (why "a job has not started"));
  }
};

static List _job_error_expand(String key, List arguments) {
  Map rows = _job_error_rows();
  Var row = rows[key];
  if (row == void)
    x2c_diagnostic_fail(%"unknown job error '$key'", %());
  Macro selected = row;
  return %(${Macro_apply(selected, arguments)});
}

/* --- lib/json-errors.xmacro ---------------------------------------------- */

static Map _json_error_rows(void) => {

  "boolean.type" :
  macro Statement(Expr $tag) {
    raise %(bad-types (operation "Json.boolean") (tag ${$tag}));
  },

  "read.file" :
  macro Statement(
    Expr $path, Expr $why, Expr $offset, Expr $line, Expr $column) {
    raise %(bad-arg (operation "Json.read_file") (path ${$path})
            (why ${$why}) (offset ${$offset})
            (line ${$line}) (column ${$column}));
  },

  "read.text" :
  macro Statement(Expr $why, Expr $offset, Expr $line, Expr $column) {
    raise %(bad-arg (operation "Json.parse") (why ${$why})
            (offset ${$offset}) (line ${$line}) (column ${$column}));
  },

  "write.depth" :
  macro Statement() {
    raise %(size-limit (operation "Var.json")
            (why "nesting exceeds 512 levels"));
  },

  "write.type" :
  macro Statement(Expr $tag) {
    raise %(bad-types (operation "Var.json") (tag ${$tag}));
  },

  "write.key" :
  macro Statement(Expr $tag) {
    raise %(bad-types (operation "Var.json") (want "String object key")
            (tag ${$tag}));
  },

  "write.duplicate" :
  macro Statement(Expr $text) {
    raise %(bad-arg (operation "Var.json") (why "duplicate object name")
            (name ${$text}));
  },

  "write.nonfinite" :
  macro Statement() {
    raise %(conv-range (operation "Var.json")
            (why "JSON has no NaN or infinity"));
  },

  "read.trailing" :
  macro Statement(Expr $reader) {
    $reader._fail("unexpected text after the value");
  },

  "read.depth" :
  macro Statement(Expr $reader) {
    $reader._fail("nesting exceeds 512 levels");
  },

  "read.end" :
  macro Statement(Expr $reader) {
    $reader._fail("unexpected end of input");
  },

  "read.char" :
  macro Statement(Expr $reader) {
    $reader._fail("unexpected character");
  },

  "read.key" :
  macro Statement(Expr $reader) {
    $reader._fail("expected a string key");
  },

  "read.colon" :
  (macro Expression() => "expected ':'"),

  "read.object.sep" :
  (macro Expression() => "expected ',' or '}'"),

  "read.array.sep" :
  (macro Expression() => "expected ',' or ']'"),

  "read.string.end" :
  macro Statement(Expr $reader) {
    $reader._fail("unterminated string");
  },

  "read.control" :
  macro Statement(Expr $reader) {
    $reader._fail("control character in string");
  },

  "read.utf8" :
  macro Statement(Expr $reader) {
    $reader._fail("invalid UTF-8");
  },

  "read.escape" :
  macro Statement(Expr $reader) {
    $reader._fail("invalid escape");
  },

  "read.surrogate" :
  macro Statement(Expr $reader) {
    $reader._fail("unpaired surrogate");
  },

  "read.nul" :
  macro Statement(Expr $reader) {
    $reader._fail("U+0000 cannot appear in a String");
  },

  "read.unicode" :
  macro Statement(Expr $reader) {
    $reader._fail("invalid \\u escape");
  },

  "read.number" :
  macro Statement(Expr $reader) {
    $reader._fail("invalid number");
  },

  "read.range" :
  macro Statement(Expr $reader) {
    $reader._fail("number out of range");
  }
};

static List _json_error_expand(String key, List arguments) {
  Map rows = _json_error_rows();
  Var row = rows[key];
  if (row == void)
    x2c_diagnostic_fail(%"unknown json error '$key'", %());
  Macro selected = row;
  return %(${Macro_apply(selected, arguments)});
}

/* --- lib/lisp-form-errors.xmacro ----------------------------------------- */

static Map _lisp_form_error_rows(void) => {

  "eval.void" :
  macro Statement() {
    raise %(void-op (operation "eval"));
  },

  "eval.unbound" :
  macro Statement(Expr $expr) {
    raise %(unbound (name ${$expr}));
  },

  "call.type" :
  macro Statement(Expr $callable) {
    raise %(not-call (actual ${$callable.kind()}));
  },

  "def.arity" :
  macro Statement(Expr $actual, Expr $args) {
    raise %(bad-arity (operation "def") (expected 2) (actual ${$actual})
            (value ${$args}));
  },

  "def.protected" :
  macro Statement(Expr $name) {
    raise %(bad-state (operation "def") (name ${$name}));
  },

  "def.inherited" :
  macro Statement(Expr $name) {
    raise %(bad-state (operation "def") (why "inherited") (name ${$name}));
  },

  "def.frozen" :
  macro Statement(Expr $name) {
    raise %(bad-state (operation "def") (why "frozen") (name ${$name}));
  },

  "cond.empty" :
  macro Statement() {
    raise %(bad-arity (operation "cond") (expected 1) (actual 0));
  },

  "cond.type" :
  macro Statement(Expr $clause) {
    raise %(bad-types (operation "cond") (value ${$clause}) (want "List"));
  },

  "cond.arity" :
  macro Statement(Expr $actual, Expr $clause) {
    raise %(bad-arity (operation "cond-clause") (expected 2)
            (actual ${$actual}) (value ${$clause}));
  },

  "bind.signature" :
  macro Statement(Expr $signature) {
    raise %(bad-sig (operation "bind") (value ${$signature}));
  },

  "bind.missing" :
  macro Statement(Expr $name, Expr $sig) {
    raise %(no-symbol (name ${$name}) (sig ${$sig}));
  },

  "quote.shape" :
  macro Statement(Expr $expr) {
    raise %(bad-arity (operation "quasiquote") (value ${$expr}));
  },

  "splice.type" :
  macro Statement(Expr $value) {
    raise %(bad-types (operation "quasiquote-splice")
            (actual ${$value.kind()}));
  },

  "lambda.signature" :
  macro Statement(Expr $operation, Expr $args) {
    raise %(bad-sig (operation ${$operation}) (value ${$args}));
  },

  "apply.void" :
  macro Statement(Expr $index) {
    raise %(void-op (operation "apply") (index ${$index}));
  },

  "apply.rest" :
  macro Statement(Expr $body) {
    raise %(bad-sig (operation "apply") (value ${$body}));
  },

  "apply.arity" :
  macro Statement(Expr $body) {
    raise %(bad-arity (operation "apply") (value ${$body}));
  },

  "apply.interrupted" :
  macro Statement() {
    raise %(interrupt (operation "apply"));
  },

  "apply.steps" :
  macro Statement() {
    raise %(call-stack (operation "apply") (why "steps"));
  },

  "apply.stack" :
  macro Statement(Expr $body) {
    raise %(call-stack (operation "apply") (value ${$body}));
  },

  "form.arity" :
  macro Statement(Expr $operation, Expr $expected, Expr $actual) {
    raise %(bad-arity (operation ${$operation}) (expected ${$expected})
            (actual ${$actual}));
  },

  "form.string" :
  macro Statement(Expr $operation, Expr $value) {
    raise %(bad-types (operation ${$operation}) (actual ${$value.kind()})
            (want "String"));
  },

  "apply.list" :
  macro Statement(Expr $values) {
    raise %(bad-types (operation "apply") (actual ${$values.kind()})
            (want "List"));
  },

  "apply.procedure" :
  macro Statement(Expr $callable) {
    raise %(not-call (operation "apply") (actual ${$callable.kind()}));
  }
};

static List _lisp_form_error_expand(String key, List arguments) {
  Map rows = _lisp_form_error_rows();
  Var row = rows[key];
  if (row == void)
    x2c_diagnostic_fail(%"unknown Lisp form error '$key'", %());
  Macro selected = row;
  return %(${Macro_apply(selected, arguments)});
}

/* --- lib/lisp-session-errors.xmacro -------------------------------------- */

static Map _lisp_session_error_rows(void) => {

  "callback.absent" :
  macro Statement(Expr $operation) {
    raise %(bad-state (operation ${$operation}) (why "no session"));
  },

  "callback.wrong" :
  macro Statement(Expr $operation) {
    raise %(bad-state (operation ${$operation}) (why "wrong session"));
  },

  "entry.null" :
  macro Statement(Expr $operation) {
    raise %(bad-arg (operation ${$operation}));
  },

  "global.args" :
  macro Statement() {
    raise %(bad-arg (operation "Lisp.set_global"));
  },

  "global.frozen" :
  macro Statement() {
    raise %(bad-state (operation "Lisp.set_global") (why "frozen"));
  },

  "global.inherited" :
  macro Statement(Expr $name) {
    raise %(bad-state (operation "Lisp.set_global") (why "inherited")
            (name ${$name}));
  },

  "bind.args" :
  macro Statement() {
    raise %(bad-arg (operation "Lisp.bind"));
  },

  "source.callable" :
  macro Statement(Expr $callable) {
    raise %(bad-types (operation "lisp_source_function") (want "Lambda")
            (actual ${$callable.kind()}));
  }
};

static List _lisp_session_error_expand(String key, List arguments) {
  Map rows = _lisp_session_error_rows();
  Var row = rows[key];
  if (row == void)
    x2c_diagnostic_fail(%"unknown Lisp session error '$key'", %());
  Macro selected = row;
  return %(${Macro_apply(selected, arguments)});
}

/* --- lib/native-scalar-types.xmacro -------------------------------------- */

static Map native_scalar_types(void) => {
  %(char): %(i8 "Var_char" "x2c_var_update_i8"),
  %(signed char): %(i8 "Var_char" "x2c_var_update_schar"),
  %(unsigned char): %(u8 "Var_uchar" "x2c_var_update_u8"),
  %(short): %(i16 "Var_short" "x2c_var_update_i16"),
  %(unsigned short): %(u16 "Var_ushort" "x2c_var_update_u16"),
  %(int): %(i32 "Var_int" "x2c_var_update_i32"),
  %(unsigned): %(u32 "Var_uint" "x2c_var_update_u32"),
  %(long): %(long "Var_long" "x2c_var_update_long"),
  %(unsigned long): %(ulong "Var_ulong" "x2c_var_update_ulong"),
  %(long long): %(llong "Var_long_long" "x2c_var_update_long_long"),
  %(unsigned long long):
    %(ullong "Var_ulong_long" "x2c_var_update_ulong_long"),
  %(float): %(f32 "Var_float" "x2c_var_update_f32"),
  %(double): %(f64 "Var_floating" "x2c_var_update_f64"),
  %(long double):
    %(ldouble "Var_long_double" "x2c_var_update_long_double"),
};

/* --- src/sdk-errors.xmacro ----------------------------------------------- */

static Map _sdk_error_rows(void) => {
  "method.name" :
  macro Statement(Expr $name) {
    _sdk_reject_value(
      "x2c.method.resolve requires an identifier String", $name);
  },
  "method.ambiguous" :
  macro Statement(Expr $owner, Expr $name, Expr $notes) {
    MetaContext_reject(
      %"method '${$owner}.${$name}' is provided by multiple imported packages",
      $notes.list_free());
  },
  "fields.type" :
  macro Statement(Expr $value) {
    _sdk_reject_value(
      "x2c.type.fields requires a struct or union Type", $value);
  },
  "fields.incomplete" :
  macro Statement(Expr $value) {
    _sdk_reject_value(
      "x2c.type.fields requires a complete struct or union Type", $value);
  },
  "binding.spelling" :
  macro Statement(Expr $syntax) {
    _sdk_reject_value(
      "x2c.binding.spelling requires an identifier spelling", $syntax);
  },
  "binding.syntax" :
  macro Statement(Expr $syntax) {
    _sdk_reject_value("x2c.binding.spelling requires binding syntax", $syntax);
  },
  "binding.unknown" :
  macro Statement(Expr $value) {
    MetaContext_reject(
      "x2c.binding.spelling requires a known binding",
      %("binding: ${$value.repr()}"));
  },
  "binding.identifier" :
  macro Statement(Expr $syntax) {
    _sdk_reject_value(
      "x2c.binding.spelling requires an identifier or binding", $syntax);
  },
  "ident.spelling" :
  macro Statement(Expr $spelling) {
    _sdk_reject_value("x2c.ident requires an identifier spelling", $spelling);
  },
  "name.stem" :
  macro Statement(Expr $stem) {
    _sdk_reject_value("_x2c.name.unique requires an identifier stem", $stem);
  },
  "param.missing" :
  macro Statement(Expr $wanted, Expr $function) {
    MetaContext_reject(
      %"x2c.function.parameter cannot find '${$wanted}'",
      %("function: ${x2c_function_name($function).repr()}"));
  },
  "symbols.type" :
  macro Statement(Expr $value) {
    MetaContext_reject(
      "_x2c.symbol-set requires Symbols",
      %("value:" ${$value.repr()}));
  },
  "symbols.duplicate" :
  macro Statement(Expr $values, Expr $duplicate) {
    MetaContext_reject(
      "_x2c.symbol-set requires distinct Symbols",
      %("symbol:" ${$values.getindex($duplicate).repr()}));
  },
  "module.empty" :
  macro Statement() {
    MetaContext_reject(
      "native module sources declare no meta function",
      %("declare each exported function with a bodyless meta prototype"));
  },
  "source.capture" :
  macro Statement(Expr $bound, Expr $value) {
    MetaContext_reject(
      "x2c.source.text requires complete captured syntax",
      $bound ? NULL : %("value: ${$value.repr()}"));
  },
  "embed.empty" :
  macro Statement() {
    MetaContext_reject("x2c.embed.text requires a non-empty path", NULL);
  },
  "embed.literal" :
  macro Statement(Expr $requested) {
    _sdk_reject_value(
      "x2c.embed.text requires a String or captured String literal",
      $requested);
  },
  "embed.read" :
  macro Statement(Expr $c, Expr $path) {
    $c._embed_reject("cannot read embedded text", $path);
  },
  "embed.nul" :
  macro Statement(Expr $c, Expr $path) {
    $c._embed_reject("embedded text contains an embedded NUL", $path);
  },
  "embed.limit" :
  macro Statement(Expr $c, Expr $path) {
    $c._embed_reject("embedded text exceeds the String size limit", $path);
  },
  "embed.file" :
  macro Statement(Expr $c, Expr $path) {
    $c._embed_reject("embedded text is not a regular file", $path);
  },
  "embed.open" :
  macro Statement(Expr $c, Expr $path) {
    $c._embed_reject("cannot open embedded text", $path);
  },
  "literal.type" :
  macro Statement(Expr $syntax) {
    MetaContext_reject(
      "x2c.literal.value requires a String, int, or Symbol literal",
      %("value: ${$syntax.repr()}"));
  },
  "location.inactive" :
  macro Statement() {
    MetaContext_reject(
      "x2c invocation location used outside macro expansion", NULL);
  },
  "notes.type" :
  macro Statement(Expr $operation, Expr $note) {
    _sdk_reject_value(%"${$operation} notes must be Strings", $note);
  },
  "expansion.inactive" :
  macro Statement(Expr $operation) {
    MetaContext_reject(%"${$operation} used outside macro expansion", NULL);
  },
  "reference.inactive" :
  macro Statement() {
    raise %(bad-state (operation "_x2c.function.reference"));
  },
  "reject.inactive" :
  macro Statement(Expr $message) {
    raise %(bad-state (operation "x2c SDK rejection") (why ${$message}));
  },
};

static List _sdk_error_expand(String key, List arguments) {
  Map rows = _sdk_error_rows();
  Var row = rows[key];
  if (row is void)
    x2c_diagnostic_fail(%"unknown sdk error '$key'", %());
  Macro selected = row;
  if (arguments.len() != selected.assoc(<parameters>).list().len())
    x2c_diagnostic_fail(%"wrong argument count for sdk error '$key'", %());
  return %(${Macro_apply(selected, arguments)});
}

/* --- lib/system-macros.xmacro -------------------------------------------- */

static List _dedent_expand(List node) {
  String source = x2c_source_text(node);
  int length = source.len(), open = 0;
  if (length >= 3 && source.startswith("%\""))
    open = 2;
  else if (length >= 2 && source.startswith("\""))
    open = 1;
  if (open == 0 || !source.endswith("\"") || source.contains("\\") ||
      source.contains("$"))
    return x2c_expr_call(x2c_expr_field(node, "dedent"), %());
  String body = source.getslice(open, length - 1, 1);
  return x2c_literal_string(body.dedent());
}

static int _cases_label(List item) {
  match (item) {
    case %(at ? (case ?)): return 1;
    case %(at ? (default)): return 1;
  }
  return 0;
}

static int _cases_transfers(List item) {
  match (item) {
    case %(at ? (break)): return 1;
    case %(at ? (continue)): return 1;
    case %(at ? (goto ?)): return 1;
    case %(at ? (return ? ?)): return 1;
    case %(at ? (return ?)): return 1;
  }
  return 0;
}

static List _cases_split(List items, int labelled) {
  if (!items) return %();
  List item = items.car();
  if (_cases_label(item))
    return %($item @{_cases_split(items.cdr(), 1)});
  if (!labelled)
    return %($item @{_cases_split(items.cdr(), 0)});
  Array run = [];
  while (items && !_cases_label(items.car())) {
    run.push(items.car());
    items = items.cdr();
  }
  if (!_cases_transfers(run[-1])) run.push(%(break));
  return %((block @run) @{_cases_split(items, 0)});
}

static List _cases_switch(List condition, List body) =>
  %((switch $condition (block @{_cases_split(body.cdr(), 0)})));

static List _macros_location(void) =>
  x2c_literal_string(
    x2c_invocation_file() + ":" + x2c_invocation_line().str());

/* --- lib/var-tags.xmacro ------------------------------------------------- */

static List _tag_groups(void) => %(
  (
    (<u8>  "_u8_"  <integer>  0x8002 0x0001 0x0 8 1)
    (<i8>  "_i8_"  <integer>  0x8002 0x0002 0x0 8 1)
    (<u16> "_u16_" <integer>  0x8002 0x0003 0x0 16 2)
    (<i16> "_i16_" <integer>  0x8002 0x0004 0x0 16 2)
    (<u32> "_u32_" <integer>  0x8002 0x0005 0x0 32 3)
    (<i32> "_i32_" <integer>  0x8002 0x0006 0x0 32 3)
    (<f32> "_f32_" <floating> 0x8002 0x0007 0x0 32 7)
  )
  (
    (<u48> "_u48_" <integer>  0x8000 0x0000 0x0 48 4)
    (<i48> "_i48_" <integer>  0x8001 0x0000 0x0 48 4)
    (<p48> "_p48_" <pointer>  0x0000 0x0000 0x0)
    (<f64> "_f64_" <floating> 0x0000 0x0000 0x0 64 8)
  )
  (
    (<long>    "_long_"    <integer>  0x0005 0x0000 0x5 (long) 5)
    (<ulong>   "_ulong_"   <integer>  0x0005 0x0000 0x6 (unsigned long) 5)
    (<llong>   "_llong_"   <integer>  0x0005 0x0000 0x7 (long long) 6)
    (<ullong>  "_ullong_"  <integer>  0x0007 0x0000 0x6 (unsigned long long) 6)
    (<ldouble> "_ldouble_" <floating> 0x0007 0x0000 0x7 (long double) 9)
  )
  (
    (<u8*>      "_u8_p_"      <pointer> 0x0001 0x0000 0x0)
    (<i8*>      "_i8_p_"      <pointer> 0x0002 0x0000 0x0)
    (<u16*>     "_u16_p_"     <pointer> 0x0003 0x0000 0x0)
    (<i16*>     "_i16_p_"     <pointer> 0x0003 0x0000 0x1)
    (<u32*>     "_u32_p_"     <pointer> 0x0004 0x0000 0x0)
    (<i32*>     "_i32_p_"     <pointer> 0x0004 0x0000 0x1)
    (<f32*>     "_f32_p_"     <pointer> 0x0004 0x0000 0x2)
    (<ulong*>   "_ulong_p_"   <pointer> 0x0004 0x0000 0x3)
    (<long*>    "_long_p_"    <pointer> 0x0005 0x0000 0x0)
    (<f64*>     "_f64_p_"     <pointer> 0x0005 0x0000 0x1)
    (<ullong*>  "_ullong_p_"  <pointer> 0x0005 0x0000 0x2)
    (<llong*>   "_llong_p_"   <pointer> 0x0005 0x0000 0x3)
    (<ldouble*> "_ldouble_p_" <pointer> 0x0005 0x0000 0x4)
    (<p48*>     "_p48_p_"     <pointer> 0x0006 0x0000 0x0)
  )
  (
    (<u8**>      "_u8_pp_"      <pointer> 0x0006 0x0000 0x1)
    (<i8**>      "_i8_pp_"      <pointer> 0x0006 0x0000 0x2)
    (<u16**>     "_u16_pp_"     <pointer> 0x0006 0x0000 0x3)
    (<i16**>     "_i16_pp_"     <pointer> 0x0006 0x0000 0x4)
    (<u32**>     "_u32_pp_"     <pointer> 0x0006 0x0000 0x5)
    (<i32**>     "_i32_pp_"     <pointer> 0x0006 0x0000 0x6)
    (<f32**>     "_f32_pp_"     <pointer> 0x0006 0x0000 0x7)
    (<ulong**>   "_ulong_pp_"   <pointer> 0x0007 0x0000 0x0)
    (<long**>    "_long_pp_"    <pointer> 0x0007 0x0000 0x1)
    (<f64**>     "_f64_pp_"     <pointer> 0x0007 0x0000 0x2)
    (<ullong**>  "_ullong_pp_"  <pointer> 0x0007 0x0000 0x3)
    (<llong**>   "_llong_pp_"   <pointer> 0x0007 0x0000 0x4)
    (<ldouble**> "_ldouble_pp_" <pointer> 0x0007 0x0000 0x5)
  )
  (
    (<array>   "_array_"   <object> 0x0008 0x0000 0x0)
    (<block>   "_block_"   <object> 0x0008 0x0000 0x1)
    (<buffer>  "_buffer_"  <object> 0x0008 0x0000 0x2)
    (<bytes>   "_bytes_"   <object> 0x0008 0x0000 0x3)
    (<context> "_context_" <object> 0x0008 0x0000 0x5)
    (<error>   "_error_"   <object> 0x0008 0x0000 0x7)
    (<file>    "_file_"    <object> 0x0009 0x0000 0x0)
    (<func>    "_func_"    <object> 0x0009 0x0000 0x1)
    (<iter>    "_iter_"    <object> 0x0009 0x0000 0x2)
    (<lambda>  "_lambda_"  <object> 0x0009 0x0000 0x3)
    (<list>    "_list_"    <object> 0x0009 0x0000 0x4)
    (<logger>  "_logger_"  <object> 0x0009 0x0000 0x5)
    (<map>     "_map_"     <object> 0x0009 0x0000 0x6)
  )
  (
    (<mutex>  "_mutex_"  <object> 0x000A 0x0000 0x0)
    (<pipe>   "_pipe_"   <object> 0x000A 0x0000 0x1)
    (<proc>   "_proc_"   <object> 0x000A 0x0000 0x2)
    (<regexp> "_regexp_" <object> 0x000A 0x0000 0x3)
    (<rope>   "_rope_"   <object> 0x000A 0x0000 0x4)
    (<scope>  "_scope_"  <object> 0x000A 0x0000 0x5)
    (<slice>  "_slice_"  <object> 0x000A 0x0000 0x6)
    (<socket> "_socket_" <object> 0x000A 0x0000 0x7)
    (<stream> "_stream_" <object> 0x000B 0x0000 0x0)
    (<string> "_string_" <object> 0x000B 0x0000 0x1)
    (<symbol> "_symbol_" <symbol> 0x8004 0x800C 0x0)
    (<tensor> "_tensor_" <object> 0x000B 0x0000 0x3)
    (<thread> "_thread_" <object> 0x000B 0x0000 0x4)
    (<token>  "_token_"  <object> 0x000B 0x0000 0x5)
    (<var>    "_var_"    <object> 0x000B 0x0000 0x6)
  )
  (
    (<array*>   "_array_p_"   <reference> 0x000C 0x0000 0x0)
    (<block*>   "_block_p_"   <reference> 0x000C 0x0000 0x1)
    (<buffer*>  "_buffer_p_"  <reference> 0x000C 0x0000 0x2)
    (<bytes*>   "_bytes_p_"   <reference> 0x000C 0x0000 0x3)
    (<context*> "_context_p_" <reference> 0x000C 0x0000 0x5)
    (<error*>   "_error_p_"   <reference> 0x000C 0x0000 0x7)
    (<file*>    "_file_p_"    <reference> 0x000D 0x0000 0x0)
    (<func*>    "_func_p_"    <reference> 0x000D 0x0000 0x1)
    (<iter*>    "_iter_p_"    <reference> 0x000D 0x0000 0x2)
    (<lambda*>  "_lambda_p_"  <reference> 0x000D 0x0000 0x3)
    (<list*>    "_list_p_"    <reference> 0x000D 0x0000 0x4)
    (<logger*>  "_logger_p_"  <reference> 0x000D 0x0000 0x5)
    (<map*>     "_map_p_"     <reference> 0x000D 0x0000 0x6)
  )
  (
    (<mutex*>  "_mutex_p_"  <reference> 0x000E 0x0000 0x0)
    (<pipe*>   "_pipe_p_"   <reference> 0x000E 0x0000 0x1)
    (<proc*>   "_proc_p_"   <reference> 0x000E 0x0000 0x2)
    (<regexp*> "_regexp_p_" <reference> 0x000E 0x0000 0x3)
    (<rope*>   "_rope_p_"   <reference> 0x000E 0x0000 0x4)
    (<scope*>  "_scope_p_"  <reference> 0x000E 0x0000 0x5)
    (<slice*>  "_slice_p_"  <reference> 0x000E 0x0000 0x6)
    (<socket*> "_socket_p_" <reference> 0x000E 0x0000 0x7)
    (<stream*> "_stream_p_" <reference> 0x000F 0x0000 0x0)
    (<string*> "_string_p_" <reference> 0x000F 0x0000 0x1)
    (<symbol*> "_symbol_p_" <reference> 0x000F 0x0000 0x2)
    (<tensor*> "_tensor_p_" <reference> 0x000F 0x0000 0x3)
    (<thread*> "_thread_p_" <reference> 0x000F 0x0000 0x4)
    (<token*>  "_token_p_"  <reference> 0x000F 0x0000 0x5)
    (<var*>    "_var_p_"    <reference> 0x000F 0x0000 0x6)
  )
  (
    (<nan>  "_nan_"    <floating> 0x8003 0x0001 0x0)
    (<-inf> "_neginf_" <floating> 0x8003 0x0002 0x0)
    (<+inf> "_posinf_" <floating> 0x8003 0x0003 0x0)
    (<void> "_void_"   <void>     0x8003 0xFFFF 0x0)
  )
);

static List _tag_rows(void) {
  Array rows = [];
  foreach (List group, _tag_groups())
    foreach (Var row, group) rows.push(row);
  return rows;
}

static String _tag_id(List row)    => row[1];

static Symbol _tag_kind(List row)  => row[2];

static int _tag_top(List row)      => row[3];

static int _tag_middle(List row)   => row[4];

static int _tag_bottom(List row)   => row[5];

static int _tag_numeric(List row)  => row.len() > 6;

static Var _tag_bits(List row)     => row[6];

static int _tag_rank(List row)     => row[7];

static int _tag_floating(List row) => _tag_kind(row) == <floating>;

static int _tag_unsigned(List row) => row[0].str().startswith("u");

static List _tag_composite(List items) =>
  %(expr () (composite (commas @items)));

static List _tag_info_row(List row) =>
  _tag_composite([
    x2c_literal_symbol(row[0]),
    x2c_literal_symbol(_tag_kind(row)),
    x2c_literal_int(_tag_top(row)),
    x2c_literal_int(_tag_middle(row)),
    x2c_literal_int(_tag_bottom(row))]);

static List _tag_info_sentinel(void) =>
  _tag_composite([
    x2c_literal_int(0),
    x2c_literal_symbol(<void>),
    x2c_literal_int(0x8000),
    x2c_literal_int(0),
    x2c_literal_int(0)]);

static List _tag_info(void) {
  Array cells = [];
  foreach (List row, _tag_rows()) cells.push(_tag_info_row(row));
  cells.push(_tag_info_sentinel());
  return _tag_composite(cells);
}

static int _tag_descriptor(List row) =>
  _tag_kind(row) == <object> || _tag_kind(row) == <symbol>;

static List _tag_names(void) {
  Array names = [];
  foreach (List row, _tag_rows()) names.push(row[0]);
  return names;
}

static List _tag_numeric_rows(void) {
  Array rows = [];
  foreach (List row, _tag_rows()) if (_tag_numeric(row)) rows.push(row);
  return rows;
}

static List _tag_numeric_names(void) {
  Array names = [];
  foreach (List row, _tag_numeric_rows()) names.push(row[0]);
  return names;
}

static List _tag_bits_expr(List row) {
  Var bits = _tag_bits(row);
  /* `bits is <list>` would compile to the `Var.is_row` fast path, which has
     no compile-time meaning, so the tag is read directly. */
  if (bits.tag() == <list>)
    return %(expr () (op *
      (expr (unsigned)
        (sizeof (parens (decl $bits (bindings (bind () ()))))))
      ${x2c_expr_ident(%("CHAR_BIT"))}));
  return x2c_literal_int(bits);
}

static List _tag_numeric_row(List row) =>
  _tag_composite([
    x2c_literal_symbol(row[0]),
    x2c_literal_int(_tag_floating(row)),
    x2c_literal_int(_tag_unsigned(row)),
    _tag_bits_expr(row),
    x2c_literal_int(_tag_rank(row))]);

static List _tag_numeric_table(void) {
  Array cells = [];
  foreach (List row, _tag_numeric_rows()) cells.push(_tag_numeric_row(row));
  return _tag_composite(cells);
}

static int _tag_decode_row(List row) {
  Var tag = row[0];
  return !(tag == <f64> || tag == <symbol> || tag == <void>);
}

static List _tag_decode_rows(void) {
  Array rows = [];
  foreach (List row, _tag_rows()) if (_tag_decode_row(row)) rows.push(row);
  return rows;
}

static int _tag_group_mask(int count) {
  if (count == 1) return 0;
  if (count == 2) return 1;
  if (count == 4) return 3;
  return 7;
}

static List _tag_validated_ids(void) => %(
  "_long_" "_ulong_" "_llong_" "_ullong_" "_ldouble_" "_array_" "_map_"
  "_u8_" "_i8_" "_u16_" "_i16_" "_nan_" "_neginf_" "_posinf_");

static int _tag_constant_row(List row) {
  if (_tag_validated_ids().contains(_tag_id(row))) return 0;
  return _tag_top(row) != 0x8002 && _tag_top(row) != 0x8003;
}

static List _tag_list(List items) {
  List built = %(expr ("List") (nil));
  for (int i = items.len() - 1; i >= 0; i--)
    built = %(expr ("List") (cons ${items[i]} $built));
  return built;
}

static Map _tag_sibling_counts(List rows) {
  Map counts = {};
  foreach (List row, rows) {
    Var top = _tag_top(row);
    counts[top] = counts.getdefault(top, 0) + 1;
  }
  return counts;
}

static List _tag_row_entry(List row, Map counts) =>
  %(map-entry ${x2c_literal_symbol(row[0])}
    ${_tag_list([x2c_literal_int(_tag_top(row)),
                 x2c_literal_int(_tag_group_mask(counts[_tag_top(row)])),
                 x2c_literal_int(_tag_bottom(row))])});

static List _tag_constant_rows(void) {
  List rows = _tag_decode_rows();
  Map counts = _tag_sibling_counts(rows);
  Array entries = [];
  foreach (List row, rows)
    if (_tag_constant_row(row)) entries.push(_tag_row_entry(row, counts));
  return entries;
}

static int _tag_group_top(int slot) =>
  slot % 2 == 0 ? slot / 2 : 0x8000 + slot / 2;

static List _tag_decode_group(List rows, Map counts, int top) {
  int immediate = top == 0x8002 || top == 0x8003;
  int mask = _tag_group_mask(counts.getdefault(top, 0));
  Array ids = [];
  for (int i = 0; i < 8; i++)
    ids.push(x2c_expr_ident(x2c_ident("_invalid_")));
  foreach (List row, rows) {
    if (_tag_top(row) != top) continue;
    int selector = immediate ? _tag_middle(row) : _tag_bottom(row) & mask;
    ids[selector] = x2c_expr_ident(x2c_ident(_tag_id(row)));
  }
  return _tag_composite(%(${x2c_literal_int(mask)}
    ${x2c_literal_int(immediate)} ${_tag_composite(ids)}));
}

static List _tag_decode_groups(void) {
  List rows = _tag_decode_rows();
  Map counts = _tag_sibling_counts(rows);
  Array groups = [];
  for (int group = 0; group < 32; group++)
    groups.push(_tag_decode_group(rows, counts, _tag_group_top(group)));
  return _tag_composite(groups);
}

static List _tag_id_checks(void) {
  Array checks = [];
  int index = 0;
  List message = %(expr (* char)
    (literal (* char) "\"TagId matches the var tag ledger\""));
  foreach (List row, _tag_rows()) {
    List id = x2c_expr_ident(x2c_ident(_tag_id(row)));
    List same = %(expr () (op == $id ${x2c_literal_int(index)}));
    checks.push(%(c-assert $same $message));
    index++;
  }
  return checks;
}

static Map _tag_types(List native) {
  Map types = {};
  foreach (List row, native) types[row[0]] = row[1];
  Symbol star = <*>;
  foreach (List row, _tag_rows()) {
    if (!_tag_descriptor(row)) continue;
    String tag = row[0].str();
    String name = tag.capitalize();
    types[%($name)] = row[0];
    Symbol pointer = tag + "*";
    types[%($star $name)] = pointer;
  }
  return types;
}

/* --- lib/var-unbox.xmacro ------------------------------------------------ */

static int var_tag_top(List tag) =>
  (int) Var_tag_top(List_last((List) List_last(tag)));

static int var_tag_bottom(List tag) =>
  (int) Var_tag_bottom(List_last((List) List_last(tag)));

/* --- lib/varconvert-errors.xmacro ---------------------------------------- */

static Map _convert_error_rows(void) => {

  "encoding.bad" :
  macro Statement(Expr $bits) {
    raise %(bad-enc (value ${$bits}));
  },

  "convert.void" :
  macro Statement() {
    raise %(void-op (owner "Var.convert"));
  },

  "target.invalid" :
  macro Statement(Expr $target) {
    raise %(bad-target (target ${$target}));
  },

  "source.numeric" :
  macro Statement(Expr $source_tag, Expr $target) {
    using $lower;
    {
      List $lower = %(bad-types (source ${$source_tag}));
      raise %(no-convert (target ${$target}) (cause ${$lower}));
    }
  },

  "target.numeric" :
  macro Statement(Expr $source_tag, Expr $target) {
    raise %(no-convert (source ${$source_tag}) (target ${$target}));
  },

  "decode.output" :
  macro Statement() {
    raise %(bad-arg (owner "Var.numeric_decode"));
  },

  "decode.void" :
  macro Statement() {
    raise %(void-op (owner "Var.numeric_decode"));
  },

  "decode.type" :
  macro Statement(Expr $tag) {
    raise %(bad-types (source ${$tag}));
  },

  "convert.range" :
  macro Statement(Expr $source_tag, Expr $target) {
    raise %(conv-range (source ${$source_tag}) (target ${$target}));
  }
};

static List _convert_error_expand(String key, List arguments) {
  Map rows = _convert_error_rows();
  Var row = rows[key];
  if (row == void)
    x2c_diagnostic_fail(%"unknown convert error '$key'", %());
  Macro selected = row;
  return %(${Macro_apply(selected, arguments)});
}

/* --- lib/varops.xmacro --------------------------------------------------- */

static List _update_rows(void) => %(
  (char    (i8 "Var_box_i8" "Var_integer"
            (expr (int) (literal (int) "0")) (() (char))))
  (schar   (i8 "Var_box_i8" "Var_integer"
            (expr (int) (literal (int) "0")) ((char) (signed char))))
  (u8      (u8 "Var_box_u8" "Var_integer"
            (expr (int) (literal (int) "0")) (() ("uchar"))))
  (i16     (i16 "Var_box_i16" "Var_integer"
            (expr (int) (literal (int) "0")) (() (short))))
  (u16     (u16 "Var_box_u16" "Var_integer"
            (expr (int) (literal (int) "0")) (() ("ushort"))))
  (i32     (i32 "Var_box_i32_bits" "Var_integer"
            (expr (int) (literal (int) "0")) ((unsigned) (int))))
  (u32     (u32 "Var_box_u32" "Var_integer"
            (expr (int) (literal (int) "0")) (() ("uint"))))
  (long    (long "Var_box_long" "Var_long_value"
            (expr (int) (literal (int) "0")) (() ())))
  (ulong   (ulong "Var_box_ulong" "Var_ulong_value"
            (expr (int) (literal (int) "0")) (() ())))
  (llong   (llong "Var_box_long_long" "Var_long_long_value"
            (expr (int) (literal (int) "0")) (() ())))
  (ullong  (ullong "Var_box_ulong_long" "Var_ulong_long_value"
            (expr (int) (literal (int) "0")) (() ())))
  (f32     (f32 "Var_box_f32" "Var_decode_f32"
            (expr (float) (literal (float) "0.0f")) (() ())))
  (f64     (f64 "Var_box_f64" "Var_decode_f64"
            (expr (double) (literal (double) "0.0")) (() ())))
  (ldouble (ldouble "Var_box_long_double" "Var_long_double_value"
            (expr (long double) (literal (long double) "0.0L")) (() ())))
);

static List _update_row(List id) {
  match (id)
    case %(expr ? (literal ? ? ?key)): return _update_rows().assoc(key);
  return %();
}

static Symbol _update_tag(List id)     => _update_row(id)[0];

static String _update_boxer(List id)   => _update_row(id)[1];

static String _update_decoder(List id) => _update_row(id)[2];

static List _update_zero(List id)      => _update_row(id)[3];

static List _update_cast_in(List id)  => _update_row(id)[4].car();

static List _update_cast_out(List id) => _update_row(id)[4].cdr().car();

static List _update_box(List id, List lhs) {
  List value = x2c_expr_index(x2c_expr_ident(lhs), x2c_literal_int(0));
  List into = _update_cast_in(id);
  if (into) value = x2c_expr_cast(into, value);
  return x2c_expr_call(
    x2c_expr_ident(x2c_ident(_update_boxer(id))), %($value));
}

static List _update_decode(List id, List value) {
  List decoded = x2c_expr_call(
    x2c_expr_ident(x2c_ident(_update_decoder(id))), %($value));
  List back = _update_cast_out(id);
  if (back) return x2c_expr_cast(back, decoded);
  return decoded;
}

/* --- the linked inventory ------------------------------------------------ */

macro Statement $linked.row(Expr $rows, Expr $name, Expr $function) {
  $rows[$name] = Func.new(
    $function, $(_x2c.literal.list (_x2c.function.native-type $function)));
}

/** Returns the linked copies, and the runtime builders, by name. */
Map linked_meta_targets(void) {
  Map rows = {};
  $linked.row(rows, "x2c_expr_field", x2c_expr_field);
  $linked.row(rows, "x2c_expr_cast", x2c_expr_cast);
  $linked.row(rows, "x2c_decl_make", x2c_decl_make);
  $linked.row(rows, "x2c_param_make", x2c_param_make);
  $linked.row(rows, "_meta_initializer", _meta_initializer);
  $linked.row(rows, "_meta_fail", _meta_fail);
  $linked.row(rows, "_meta_member", _meta_member);
  $linked.row(rows, "x2c_type_members", x2c_type_members);
  $linked.row(rows, "_builtin_error_rows", _builtin_error_rows);
  $linked.row(rows, "_builtin_error_expand", _builtin_error_expand);
  $linked.row(rows, "_func_error_rows", _func_error_rows);
  $linked.row(rows, "_func_error_expand", _func_error_expand);
  $linked.row(rows, "source_return_type", source_return_type);
  $linked.row(rows, "source_conditional_statement", source_conditional_statement);
  $linked.row(rows, "source_any_lambda", source_any_lambda);
  $linked.row(rows, "source_cast_content", source_cast_content);
  $linked.row(rows, "source_generic_content", source_generic_content);
  $linked.row(rows, "source_va_arg_content", source_va_arg_content);
  $linked.row(rows, "source_commas_content", source_commas_content);
  $linked.row(rows, "source_slice_content", source_slice_content);
  $linked.row(rows, "source_composite_content", source_composite_content);
  $linked.row(rows, "source_string_content", source_string_content);
  $linked.row(rows, "source_operator_content", source_operator_content);
  $linked.row(rows, "source_operator_expression", source_operator_expression);
  $linked.row(rows, "source_postfix_content", source_postfix_content);
  $linked.row(rows, "source_postfix_expression", source_postfix_expression);
  $linked.row(rows, "source_content_pattern", source_content_pattern);
  $linked.row(rows, "source_call_content", source_call_content);
  $linked.row(rows, "source_return_content", source_return_content);
  $linked.row(rows, "source_block_content", source_block_content);
  $linked.row(rows, "source_identifier_content", source_identifier_content);
  $linked.row(rows, "source_literal_content", source_literal_content);
  $linked.row(rows, "source_declarator_row", source_declarator_row);
  $linked.row(rows, "source_pattern_with", source_pattern_with);
  $linked.row(rows, "source_pattern", source_pattern);
  $linked.row(rows, "source_expression", source_expression);
  $linked.row(rows, "catch_handle", catch_handle);
  $linked.row(rows, "retain_catch_handle", retain_catch_handle);
  $linked.row(rows, "_job_error_rows", _job_error_rows);
  $linked.row(rows, "_job_error_expand", _job_error_expand);
  $linked.row(rows, "_json_error_rows", _json_error_rows);
  $linked.row(rows, "_json_error_expand", _json_error_expand);
  $linked.row(rows, "_lisp_form_error_rows", _lisp_form_error_rows);
  $linked.row(rows, "_lisp_form_error_expand", _lisp_form_error_expand);
  $linked.row(rows, "_lisp_session_error_rows", _lisp_session_error_rows);
  $linked.row(rows, "_lisp_session_error_expand", _lisp_session_error_expand);
  $linked.row(rows, "native_scalar_types", native_scalar_types);
  $linked.row(rows, "_sdk_error_rows", _sdk_error_rows);
  $linked.row(rows, "_sdk_error_expand", _sdk_error_expand);
  $linked.row(rows, "_dedent_expand", _dedent_expand);
  $linked.row(rows, "_cases_label", _cases_label);
  $linked.row(rows, "_cases_transfers", _cases_transfers);
  $linked.row(rows, "_cases_split", _cases_split);
  $linked.row(rows, "_cases_switch", _cases_switch);
  $linked.row(rows, "_macros_location", _macros_location);
  $linked.row(rows, "_tag_groups", _tag_groups);
  $linked.row(rows, "_tag_rows", _tag_rows);
  $linked.row(rows, "_tag_id", _tag_id);
  $linked.row(rows, "_tag_kind", _tag_kind);
  $linked.row(rows, "_tag_top", _tag_top);
  $linked.row(rows, "_tag_middle", _tag_middle);
  $linked.row(rows, "_tag_bottom", _tag_bottom);
  $linked.row(rows, "_tag_numeric", _tag_numeric);
  $linked.row(rows, "_tag_bits", _tag_bits);
  $linked.row(rows, "_tag_rank", _tag_rank);
  $linked.row(rows, "_tag_floating", _tag_floating);
  $linked.row(rows, "_tag_unsigned", _tag_unsigned);
  $linked.row(rows, "_tag_composite", _tag_composite);
  $linked.row(rows, "_tag_info_row", _tag_info_row);
  $linked.row(rows, "_tag_info_sentinel", _tag_info_sentinel);
  $linked.row(rows, "_tag_info", _tag_info);
  $linked.row(rows, "_tag_descriptor", _tag_descriptor);
  $linked.row(rows, "_tag_names", _tag_names);
  $linked.row(rows, "_tag_numeric_rows", _tag_numeric_rows);
  $linked.row(rows, "_tag_numeric_names", _tag_numeric_names);
  $linked.row(rows, "_tag_bits_expr", _tag_bits_expr);
  $linked.row(rows, "_tag_numeric_row", _tag_numeric_row);
  $linked.row(rows, "_tag_numeric_table", _tag_numeric_table);
  $linked.row(rows, "_tag_decode_row", _tag_decode_row);
  $linked.row(rows, "_tag_decode_rows", _tag_decode_rows);
  $linked.row(rows, "_tag_group_mask", _tag_group_mask);
  $linked.row(rows, "_tag_validated_ids", _tag_validated_ids);
  $linked.row(rows, "_tag_constant_row", _tag_constant_row);
  $linked.row(rows, "_tag_list", _tag_list);
  $linked.row(rows, "_tag_sibling_counts", _tag_sibling_counts);
  $linked.row(rows, "_tag_row_entry", _tag_row_entry);
  $linked.row(rows, "_tag_constant_rows", _tag_constant_rows);
  $linked.row(rows, "_tag_group_top", _tag_group_top);
  $linked.row(rows, "_tag_decode_group", _tag_decode_group);
  $linked.row(rows, "_tag_decode_groups", _tag_decode_groups);
  $linked.row(rows, "_tag_id_checks", _tag_id_checks);
  $linked.row(rows, "_tag_types", _tag_types);
  $linked.row(rows, "var_tag_top", var_tag_top);
  $linked.row(rows, "var_tag_bottom", var_tag_bottom);
  $linked.row(rows, "_convert_error_rows", _convert_error_rows);
  $linked.row(rows, "_convert_error_expand", _convert_error_expand);
  $linked.row(rows, "_update_rows", _update_rows);
  $linked.row(rows, "_update_row", _update_row);
  $linked.row(rows, "_update_tag", _update_tag);
  $linked.row(rows, "_update_boxer", _update_boxer);
  $linked.row(rows, "_update_decoder", _update_decoder);
  $linked.row(rows, "_update_zero", _update_zero);
  $linked.row(rows, "_update_cast_in", _update_cast_in);
  $linked.row(rows, "_update_cast_out", _update_cast_out);
  $linked.row(rows, "_update_box", _update_box);
  $linked.row(rows, "_update_decode", _update_decode);
  $linked.row(rows, "x2c_literal_string", x2c_literal_string);
  $linked.row(rows, "x2c_literal_int", x2c_literal_int);
  $linked.row(rows, "x2c_literal_symbol", x2c_literal_symbol);
  $linked.row(rows, "x2c_expr_ident", x2c_expr_ident);
  $linked.row(rows, "x2c_expr_index", x2c_expr_index);
  $linked.row(rows, "x2c_expr_call", x2c_expr_call);
  $linked.row(rows, "x2c_expr_composite", x2c_expr_composite);
  $linked.row(rows, "x2c_stmnt_make", x2c_stmnt_make);
  $linked.row(rows, "x2c_stmnt_return", x2c_stmnt_return);
  $linked.row(rows, "x2c_block_make", x2c_block_make);
  $linked.row(rows, "x2c_function_body", x2c_function_body);
  $linked.row(rows, "x2c_parameters_arguments", x2c_parameters_arguments);
  return rows;
}

macro Expression $linked.calls() => $(_x2c.meta.definition.calls);

/** Returns each linked definition's hash and referenced names. */
Map linked_meta_hashes(void) {
  Map hashes = $x2c_meta_definition_hashes();
  Map calls = $linked.calls();
  foreach (Var (name, hash), hashes)
    hashes[name] = %($hash ${calls[name]});
  return hashes;
}
